### ISSUE TITLE
Copy of Value prop: Drafting statement

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#10108]
## Description 
Taking insights from the recent workshop, app store reviews, user research, and discovery phrase, we want to draft a value proposition for the mobile app that can be socialized across VA and applied directly to key parts of the user journey (particularly in marketing and first-run experiences). This is an important piece of work for our onboarding and product adoption strategy. We will share the draft(s) with stakeholders for feedback and alignment. 

## Tasks

- [x] Review workshop notes and Mural
- [x] Review discovery documentation
- [x] Draft and iterate on options
- [x] Document reasoning for word choices, etc.
- [x] Get feedback from team members

## Acceptance Criteria
  

-  [ ] Value proposition statement draft(s)
-  [ ] Drafts incorporate feedback from both workshop + discovery
-  [ ] Drafts include a full statement (1-3 sentences, no more than 50 words)
-  [ ] Drafts have explanation for important parts and/or how words tie back to workshop/discovery findings

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic
