### ISSUE TITLE
Automation - Clean up some things in scripts

### ISSUE THREAD

**Issue by lexicalninja** [department-of-veterans-affairs/va-mobile-app#10267]
# Automation Ticket

## Type of Change

A couple of things need some cleaning up in the scripts and this ticket will control for that work. 

### Tasks
- need to fix the bug in `native_build_check_android.yml` related to a whitespace issue
- Add description text to `app_store_check_apple.yml`, `app_store_check_android.yml`, and `check_max_size.yml`
- update the input names on `check_max_size.yml` because it checks more than files

- [x] Update existing automation
- [ ] Add new automation functionality
- [ ] Fix automation bug

## What systems/scripts are changing?
- [x] Git Hub Actions
- [ ] CircleCI
- [ ] Fastlane
- [ ] Bash Scripts
- [ ] Issues Templates

## Acceptability Criteria

- [x] need to fix the bug in `native_build_check_android.yml` related to a whitespace issue
- [x] Add description text to `app_store_check_apple.yml`, `app_store_check_android.yml`, and `check_max_size.yml`
- [x] update the input names on `check_max_size.yml` because it checks more than files
