### ISSUE TITLE
First-run onboarding: Content best practices + comp analysis

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#10299]
## Description 
To help develop a point of view around how the VA mobile app should approach content for the first-run onboarding flow, we want to better understand how other apps structure their content for their first-run onboarding flows by collecting examples from other apps with entity/user relationships and feature sets that are similar to the VA mobile app.

As part of this ticket, we want to determine:
- What content (messaging, tasks to do, etc.) other apps use during first-run onboarding
- The ordering and placement of content

## Tasks

- [ ] Gather screenshots of other apps' first-run onboarding
- [ ] Identify content best practices for first-run onboarding specific to copy/content
- [ ] Compare content best practices with [general onboarding best practices documentation](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Onboarding%20&%20Product%20Adoption/discovery/onboarding-best-practices.md) from August 2024
- [ ] Draft findings and recommendations doc

## Acceptance Criteria
  

- [ ] Comparative analysis updated in [Figma](https://www.figma.com/design/NYyLjyJr4cP6vL1CDM4jyy/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research-(FJ)---VA-Mobile?node-id=1-2&node-type=canvas&t=y8iu4cchNMctmhdb-0) and linked in GH
- [ ] Comparative analysis findings documented in GH

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by mistymg** [comment]
Today: Starting pulling screenshots of other apps' first-run onboarding flows in [Figjam](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile-OLD?node-id=573-274&t=2Eg3gp2jgCFZ557m-4)

**Comment by mistymg** [comment]
Work is being deprioritized for now. Will pick back up in a later sprint.
