### ISSUE TITLE
Content: Investigate bug 10095

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#10366]
## Description
Investigate and give recommendation for [bug 10095](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/10095#issuecomment-2532763605)

## Tasks

- [ ] Review bug ticket
- [ ] Collaborate with UX to align on solution
- [ ] Respond in bug ticket with solution

## AC

- [ ] Content recommendation noted in bug ticket
