### ISSUE TITLE
Personalization - Home Screen (MVP)

### ISSUE THREAD

**Issue by ashley-matthews** [department-of-veterans-affairs/va-mobile-app#3542]
# Project Status Overview

### Project Objective:

We believe that bringing personalized content to the VA mobile app’s home screen to new and current app users will help users to keep up with and manage their current interactions across VA and find value in the app that they aren’t discovering now.

 
### Monthly Update for Stakeholders
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Jan '24 | Green | High-fidelity mockups created. Development starting
|Feb '24| Green | Development in progress. Baseline analytics are being collected. User reserach plan has been created. Expected prod release for late March / early April
|Mar '24| Green | Development in progress. Expected prod release for early May. User research plan has been finalized and will be executed prior to prod release.
|Apr '24| Green | Development in progress. Expected prod release in June. User research plan and UAT plan will be executed prior to prod release.
|5/21/24| On track| UAT completed. User research sessions will be conducted the next two sprints. Minor design tweaks are in progress
|June '24| On track| User research has been completed. Remaining work includes minor bug fixes, QA, and research report. Expected to be ready for release in early July|
|6/26/24| On track| Development is complete and only detox UI tests remain. Deployment is being delayed until late July so that Appointments work can be released first|
|7/10/24| On track| Merged into develop and will be released to production on 7/30|
|7/23/24| On track| Merged into develop and will be released to production on 7/30|
|7/30/24| Delivered| Released to production on 7/30|

</details>

# Detailed Project Scope 

### Problem Statement
The VA Flagship mobile app was designed to help Veterans who are actively engaged with VA health and benefits services to keep track of their tasks and interactions across VA. We have observed that research participants report that they download the app to see if it can help them (but then don’t use it regularly) and metrics indicate that users who initially download the app do not actively use the app over time. As a result, the VA mobile app may not be successfully providing Veterans with a way to keep track of their activities across VA in a way that’s worth returning to.

Up to this point, the app has used a one-size-fits-all approach to the home screen that limits its perceived value to Veterans. In particular:

Veterans don’t have a way to get a quick overview of what VA is doing for them now or that something is needed from them in order to keep things moving.
Veteran expectations and understanding of what they think they can do in the mobile app are limited and often inaccurate (they want something to help them, and to know if the app is that thing).
We believe that these problems are making it more difficult for Veterans to realize how the app can help them which is resulting in decreased user retention.

### Assumptions 
- Personalized content relating to their interactions with VA is valuable to Veterans and will lead to higher app adoption.
- Veterans will value personalized content so highly that they keep returning to the app.
- Surfacing personalized information at a level above its corresponding feature will make it easier for Veterans to keep track of their interactions across the VA and be made aware of related critical actions, without having to seek out when their attention is needed.
- App users want to feel that ‘the app knows me’ and seeing information related to them on the home screen makes them feel known, supported, and reassured.
- Personalized content will help to accurately set expectations and increase understanding of what the app can do for them.

### Risks 

- We’re not sure that users will find value or greater convenience in surfacing personalized information outside the existing features.
- We’re not sure which pieces of personalized information will be most valuable for users to see on the home screen.
- Displaying personalized information from too many APIs in one place might cause app performance to suffer.
- The home screen becomes overgrown & a dumping ground over time without proper guidelines and governance.

### Definition of Done 
The home screen is updated to surface Personalized and actionable content 

### Project Scope
Updates to the home screen are in scope but other Personalization improvements, like Push Notifications or Personalized Onboarding, are out of scope

</details>

### Important Project Links 
<details>
<summary>Links</summary>

- [Github](url)
- [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/product/Personalized_homescreen-Product-Brief-2023.md)
- Design
   - [Personalized Home Screen - Design & UX strategy work ](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/design-personalization/ux#personalized-home-screen) 
- Research
   - [Personalized Home Screen - Evaluative Research - MVP](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/ux-research/personalized-homescreen/2024-04%20Personalized%20Home%20Screen%20-%20evaluative%20research/readme.md) 
- Analytics
   - [Home screen success tracking](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/data/Home%20Screen%20Quantitative%20Success%20Tracking.md) 
</details>

### Team Members

<details>
<summary>Contact List</summary>

- **OCTO Product Leads:** Rachel Han and Ryan Thurlwell
- **PM:** Ryan Thulrwell
- **Ad Hoc PM:** Ameet Sarkar
- **Engineering:** Jayson Perkins and Jon Bindbeutel
- **Design:** Holly Collier
- **External Team 1 & Role:**
- **External Team 1 & Role:**

</details>

### OKR and Analytic Metrics 
<details>
<summary>Metrics</summary>

|What we are measuring | Why | Event Name 
|-------| ---------| ----- |
| | | |
| | | |

</details>

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [x ] Project Kickoff session
   - [ x] Initiative Scope finalized
   - [x ] [Product Brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/product/Personalized_homescreen-Product-Brief-2023.md)
   - [ ] Link to Implementation Strategy
       - Implementation Plan
       - UAT Plan
       - Release Plan
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide
  - [ ] Coordinate with contact center support teams
- [ ] What’s New Content
- [ ] App Store/In App messaging (if applicable)
- [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
- [ ] App store images needed? Y/N
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? 
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>
