### ISSUE TITLE
Proof of Veteran Status 

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4270]
# Project Status Overview

### Project Objective:

Veterans would benefit from an easy-to-access official Veteran ID card to use for receiving discounts and other private-sector benefits.  There is currently no simple way to attain an ID like this.  The current processes are cumbersome and long and not well known by Veterans.  A widely accepted Veteran ID within the mobile app could prove a very useful feature for Veterans and greatly increase usage of the app.

Process experiment is to deliver in a single sprint for Sprint 77 includes discovery, research, design, and prototype 

Post MVP Epic [6547](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6547)
 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

Open Blockers 
|Blocker | Team / Owner | Est to Resolution | 
|-------|---------|-------| 
| NA | | | 

Resolved Blockers 
|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
|  8/16 VIC team identified risks with photo (inappropriate pictures) and also they are pushing to remove photo as a requirement from the VIC law  | PO  | Resolved removed Photo from MVP | 
| 8/16 VIC Dishonorable discharge Veterans should not have access to this feature  | PO   | Resolved - deemed as a future improvement to prevent Veteran status from access |  
|  8/22 Rachel shared there are legal concerns with using Veteran Status given dishonorably discharged Vets can access. Rachel approved of a new title and to change the title back when DD Vets are excluded but Mobile feedback recommended holding off release till its fully cause of impact with accessibility. Rachel appreciated the feedback and was going to take it back to see what direction to go | PO   |  ~8/23 - No longer an issue as it will only be Veteran Status and will exclude DD Veterans so we do not need 2 versions |   
| How to exclude Dishonorably Discharged Veterans? Originally thought about using existing API then POs shared a Title 38 specific API. | Ryan / Jayson | Resolved 9/7 - Melissa Rebstock Branch Chief, Digital Experience, POC for VIC part of VEO provided the logic via email for BE to use. BE to expose the data fields so that FE can filter out dishonorably discharged Veterans  | 

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

|Step | Timing | 
|-------| ---------| 
|Sprint 0 - Discovery | Done    |
|Step 1 - Strategy |  Completed Sprint 77 |
|Step 2 - Design  | Completed Sprint 77   |
|Step 3 - Building / Implementing | Sprint 77 - Sprint 79 |
| 100% Release |  10/10/23|
| Post production validation | 10/10/23 | 
|Step 4 - Post Verification|  TBD |
</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Aug '23| Yellow | Discovery, design and build completed. MVP confirmed. MVP shifted to exclude photo and per VA Legal to exclude Dishonorably Discharged Veterans |  PO agreed to do DD Veteran exclusion next sprint| 
| Sept '23 | Green | Feature was implemented and tested successfully in Sprint 81 and thus included in the next release for 10/10. Call Center guide was updated and submitted. Apple, Google, VA.gov app stores updated (feature description, whats new, images). Call center guide has been updated and In-App what's new has been updated. Release steps followed for implementation with Binny approval | None | 
| Oct '23 | Green | Feature is being released on 10/10.  Last remaining item is post validation on 10/10. Flagship team transitioning work to new contract team through Oct and Nov | None |
</details>

# Detailed Project Scope 

### Problem Statement
<details>
<summary> Problem Statement Details</summary>

- There are a variety of situations in which Veterans need to prove their Veteran status in order to receive a particular benefit (having [a way to prove Veteran status](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/profile/military-information/discovery-and-research/2023-military-info-discovery/findings-summary.md#though-they-may-not-need-their-dd214-in-all-cases-to-apply-for-va-benefits-having-a-copy-of-it-facilitates-the-benefit-application-process-and-helps-veterans-access-non-va-privileges-memberships-and-discounts) helps Veterans access non-VA privileges, memberships, and discounts). Veterans would benefit from an easy-to-access official Veteran ID card to use in these contexts. Because there is currently no simple way to attain an ID like this, a widely accepted Veteran ID within the mobile app could prove a very useful feature for Veterans and greatly increase usage of the app.

From VA.gov:
 
- “A Veteran ID Card (VIC) is a digital photo ID you can use to get discounts for Veterans at many stores, businesses, and restaurants. When you have this card, you won’t need to carry around your military discharge papers or share sensitive personal information to get discounts. And you don’t need to request another type of photo ID card to prove you’re a Veteran or to get retail or business discounts.” Veterans must have an honorable discharge to get the ID
</details>

### Risks and Assumptions
<details>
<summary> List and details of risks and assumptions</summary>

- Creating a ‘competitor’ to the VIC could anger certain stakeholders (?)
    - Need to ensure creating an ID card that is not technically the VIC does not interfere with the VIC law
- Not all facilities have the same requirements to give discounts
    - Some need disablity rating, some need service connected Y/N, some require id.me integration so no form of id or letter will work, sometimes letters work
    - Do not have data on the marketplace on how many allow veteran discounts to what form of identification is needed
    - Not every shop given Veterans discount - dont know the number
- Surfacing current VIC may not be technically possible and the owning group may not have interest in working with us
- If we aren't able to let the 3rd parties who currently accept VIC as a form of proof of Veteran status know that the digital VIC is an official form of Veteran ID, they may not accept it (and Veterans will be angry/disappointed/inconveniences in that moment, but it might also erode trust in VA & the app).
- We don't currently coordinate with VA comms team when we launch features.
- There are several other forms of ID that are currently accepted and used to get discounts(Veteran Health Identification Card (VHIC), Department of Defense (DoD) Identification Card—either a Common Access Card (CAC) or Uniformed Services ID Card, or a state-issued driver’s license or ID with a Veterans designation), and Veterans may find it easier to use those instead.
- A significant number of Veterans are in situations where they don't already have a way to prove their Veteran status (ex:one of several other forms of accepted ID, a store-controlled Veteran registration system).
- A Veteran Status card displayed on a phone/in the VA mobile app will be accepted by 3rd parties as official proof of Veteran status.
- There will be marketing support for the new Veteran status card (to drive new app downloads).
- 3rd parties will accept a Veteran ID card without a photo
- Not replacing VIC, but providing the same value
- Stolen valor argument related to Veteran ID card without a picture
- Creating another unique identification card the Veterans will need to use / understand
- Going from design to prototype in 2 weeks limits understanding and knowledge of the problem
</details>

### Definition of Done 
<details>
<summary>Following needs to be true</summary>

|Item | Completed | 
|-------| ---------|
| Veteran can easily discover and access it on the mobile app | Completed  | 
| Veteran status display name, branch logo, DOB, periods of service and disability rating | Completed | 
| Veteran can close out of it when they no longer need it  | Completed | 
| Exclude dishonorably discharged veterans | completed |

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Ability to find Veteran status in the app | Photo of user| 
| Display name, branch | Displaying number of years served| 
| Display period of service | Ability to export or print card| 
| Require internet connectivity | Unauthenticated experience / access |
| Use of existing components and data | adding new components ; integration to other services for info| 
| Service connected, disability rating | Integration with VIC |
| DOB | What to do if info is incorrect (was in MVP but Rachel agreed to pull it out for now) |
|VIC blurb regarding how to use it  | Digital wallet integration |
| | [Post MVP epic 6547](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6547)|

</details>

### Important Project Links 
<details>
<summary>Links</summary>

- [PO Product Brief ](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/VIC/MobileVIC_ProductBrief.md) Matt / Rachel shared 7/6 
- See[ Sprint 0 doc](https://docs.google.com/document/d/1Rg8dUiw7MtGlpnS5ZwdJUgmBF8Moi2JFC-aEaH-NvrQ/edit)
 - [Reddit Thread ](https://www.reddit.com/r/Veterans/comments/14gbu7g/would_people_actually_believe_this_if_i_presented/)- Would ppl actually believe this is I presented it to them for the sake of a discount
 - [Product Canvas](https://docs.google.com/presentation/d/1TlzLu1eYixyKLVZ5FeMbB3iJ_HSw0tsYr5gJWGzdstQ/edit)
- [Law H.R.91 - Veterans Identification Card Act 2015](https://www.congress.gov/bill/114th-congress/house-bill/91)
- [List of current approved forms of Veteran ID](https://www.va.gov/records/get-veteran-id-cards/)
- [Example of official VIC card](https://news.va.gov/117828/va-id-card-proof-discounts/)
- [Github](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Veteran%20Status%20Card/Overview.md) 
- [Final PO MVP Review on 8/14](https://docs.google.com/presentation/d/1OwFPJ7QHrd4BQWM-KC0ZMYMQEdJiwKOjbvaJSbK7KWY/edit#slide=id.g267a8e3ed98_0_6)

</details>

### Team Members

<details>
<summary>Contact List</summary>

Mobile
- **OCTO Product Leads:**  Ryan Thurlwell
- **Ad Hoc PM:** Adam Kasmier
- **Engineering:**  Jon Bindbeutel
- **Design:** Brea Blackwelder

Ad Hoc Web Contract
- **OCTO Product Leads:**  Rachel and Ryan 
- **Ad Hoc PM:** Matt Reilly 
- **Engineering:**  In the process of hiring
- **Design:** In the process of hiring

</details>

### OKR and Analytic Metrics 
<details>
<summary>Metrics</summary>

- MVP measuring screen navigation and Veteran engagement only
- MVP is only directional related data as well 
- Not measuring if the feature works at POS (have a backlog item for this) 

|What we are measuring | Why | Event Name |
|-------| ---------| ----- |
| Tap Veteran Status on name tag | How many Veteran users are engaging with it | |
| Tap close on the full panel of Veteran Status | see how the Veteran engages on the page and help with length of time on the page | |
| Length of time on the page  | See how long Veteran remains on the page | |

</details>

### Change Log
<details>
<summary>Decisions and Dates </summary>

|Decision | PO that made the decision | Date | 
| -------- | ---------- | ------- |
 | Pull in this unplanned work into Q3 and into Sprint 78 | Ryan | ~8/9 |
 | Feature does not have to be shown in a card form | Ryan | 8/4 |
 | Inclusion of photo and disability rating in MVP | Ryan | 8/14 |
 | Removing photo from MVP | Rachel | 8/16 |
 | Implement in Sprint 78 to include in release 9/12 | Rachel | 8/22 |
 | Dishonorably Discharged Veterans must by excluded for launch | Rachel | 8/22 |
| Melissa Rebstock confirmed logic to exclude DD Veterans - show Veteran Status to any Veteran with at least 1 service period with a Y value in characterOfStatusCode | Ryan 9/7 Email |
| Add in a blurb to Veteran Status to clarify that this “Veteran status” is not an entitlement to VA benefits | Ryan 9/7 Slack | 

</details>

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [x] Project Kickoff session
   - [x] Initiative Scope finalized
   - [X] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [X] Link to Implementation Strategy
       - Implementation Plan - feature flag to turn it on for all 
       - UAT Plan - no UAT 
       - Release Plan - turn it on for all 
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc) - see metrics; only out of the box Veteran navigations metrics approved for MVP (open, close, time of page, etc)

**Pre-Production Readiness**
- [X] Associate Readiness
  - [X] Update product guide - created Call Center ticket 9/19
  - [X] Coordinate with contact center support teams
- [X] What’s New Content -  [6548](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6548)
- [X] App Store/In App messaging (if applicable) [6548](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6548)
- [X] Coordinate with Release coordinator - notified Ameet and also Jennifer past couple sprints its coming 
- [X] App store Content changes required? Yes [6548](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6548)  
- [X] App store images needed? Yes - summary, home page, profile page
- [ ] QA Signed off - testing in progress 
- [X] UAT complete - NA
- [ ] Obtain Go/No Go decision - PO release approval

**Feature Go Live**
- [X] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [X ] Coordinate with content & release coordinator if what’s new in app is required - planning to use Whats New In App
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [X ] Design Intent & Feasibility discussions
- [X] Research needed? No, spent some of the discovery time researching but not a full research project
- [X ] UAT Needed? No
- [X ] Ticket creation 
- [X ] Demo feature (mid check, end of development) 8/16 by Brea
- [ X ] Unique private Slack for designated team - va-mobile-veteran-status-id
- [ ] Archive slack channel 
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [X ] Review problem/opportunity statement
- [X] Add questions and assumptions to product brief
- [X] Add research links to product brief
- [X ] Document high-level research/design plans
- [X ] Create lo/hi fi wireframes & user flows if applicable
- [X ] Add links to Epic & applicable GitHub folders
- [X ] Socialize designs - 3 different PO reviews with Ryan, then demo reviewed it with Rachel and the Digital VIC contacts
- [X] Sign off received - Ryan signed off on MVP after final view; during demo additional changes requested from Rachel; 8/23 waiting additional direction 
- [X] Complete Design QA
- [X ] Does it require component review? No new components where used - out of scope
- [X ] Accessibility review needed? Yes pre QA testing and will be in QA testing

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [X ] Review product brief and surface any questions, assumptions & risks
- [X ] Participate in project discovery and kickoff activities/ceremonies - limited discovery given the experiment we are doing
- [X ] Complete comparative analysis/content research activities for net-new content
- [X ] Review current content and determine where app may need to differ and potential improvements to share with web
- [X ] Review past VA research and decisions documentation - limited research; did not involve VIC per requirements
- [X ] Support Research & UX Design in research sessions and synthesis - NA 
- [X ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design - Yes
- [X ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off - NA
- [X ] Participate in FE hand off - Yes
- [X ] Complete content QA - Yes
- [X ] Write copy for What's New In App - Yes
- [X] Write copy for app stores' What's New sections.
- [X] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [X ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved) Yes see Figma documentations and tickets
- [X ] Are there any deadlines that need to be met? No 
- [X ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first) Originally did not plan for feature flag but decided to include it ~8/21
- [X ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body? No 
- [X ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture? Only out of the box metrics with the screens provide. 

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [X] Create test plan
  -  **Template: QA Test Plan**
- [X] Identify test data needs
- [X] Gotten & incorporated test plan review
- [x] QA Complete
- [x] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [x] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by mistymg** [comment]
Add a link to an example of the VIC card as a resource

**Comment by bischoffa** [comment]
Based on SoS on 8/22 project is on hold until Rachel comes back with additional direction. [Notes from SoS](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/operations/MobileAppSoS-RunningAgenda.md) pertaining to this: 

Veteran Status - Rachel - hot off the press

*   Just found out before this meeting that per VA Legal we cannot use the term Veteran or Veteran Status given dishonorably discharged (DD) Veterans can currently access this feature
    *   Rationale - doesn't follow Veteran definition; could lead to legal problems if DD Veteran has something that indicates they are a Veteran ; referred to VA communication toolkit on the web
*   With this - the recommendation was to change the name to Proof of Military Service then rename to Veteran Status once DD Vets are prevented from accessing
    *   Mobile recommended Proof of Service given the length of Proof of Military Service will cause UX issues in the app - Rachel agreed
    *   Mobile also sited concerns with the switching and changes impacting Veterans with cognitive disabilities
        *   Mobile's recommendation was to hold off releasing until the product works as expected vs pushing it out and making changes
        *   Mobile also concerned with hiding information and from conversation DD Veterans can access some information but just not have it say Veteran
        *   Mobile confirmed BE has access to statuses but FE does not use them to identify DD Vets
            *   Mobile will need help with understanding what statuses to use and when from external team
*   Rachel agreed to hold off on how to move forward with Veteran Status based on Mobile feedback and will get back with the Mobile team on next steps

**Comment by Samara-Strauss** [comment]
@chrisj-usds do we need a separate card to capture requirements around veteran status on VA.gov? Given that the mobile team is leading this work and requirements for VA.gov will come from them, I don't want to create a duplicative card if it's not necessary.

**Comment by chrisj-usds** [comment]
It's probably worth having a second card in the main OCTO project board @Samara-Strauss.

**Comment by bischoffa** [comment]
Logic for excluding DD Veterans per Melissa Rebstock

- Any Veteran with at least 1 period of service with a Y (characterOfStatusCode ) will see it - this veteran status card we should show it for anyone who has any Ys
  - BE expects their work to be completed by the end of this sprint   
- Melissa also recommended adding a blurb like VIC does to clarify that this “Veteran status” is not an entitlement to VA benefits - Ryan approved of adding this in on 9/7 
   - Blurb will require Content (Misty) involvement who will coordinate with Sitewide Content
   - Misty / Brea to work together on where to put the blurb from a design perspective   

I am estimating the FE implementation will happen next sprint along with QA work - so project will carryover. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBclo2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da4826b775d3940563e7e06e32ed5d599a94700f/image.png)

**Comment by Samara-Strauss** [comment]
@chrisj-usds [card added for the web experience to the OCTO board](https://github.com/orgs/department-of-veterans-affairs/projects/940/views/1?pane=issue&itemId=37994378).

**Comment by rachelhanster** [comment]
Archived related card in Digital Experience from 2020 https://github.com/orgs/department-of-veterans-affairs/projects/940/views/8?pane=issue&itemId=28670906
