### ISSUE TITLE
Patient Check-in

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#4315]
# Project Status Overview

### Project Objective: 

Provide veterans the ability to check in the day of for a VA In Person appt using the VA Health & Benefits Mobile app

[Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/patient-check-in/Requirements/2023.04.25%20Mobile%20app_Patient%20Check%20In%20MVP.pdf)

## Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Test Patient account for staging needed. Details [here](https://github.com/orgs/department-of-veterans-affairs/projects/984/views/1?pane=issue&itemId=33330662) | Appointments team (Kay Lawyer assisting)| TBD

</details>

## Project Timeline
<details>
<summary>Milestones</summary>

Step | Timing | 
|-------| ---------| 
|Sprint 0 - Discovery | Complete   |
|Step 1 - Strategy | Complete |
|Step 2 - Design  | Complete  |
|Step 3 - Building / Implementing | On Hold   |
| 100% Release |  |
|Step 4 - Post Verification|   |
</details>

## Monthly Update

<details>

|Month| Project Health|Progress & Key Accomplishments| Issues/Risks/Blockers
|-------| ---------|--------|---------|
|July '23| At Risk| Mobile & Check in team working closely to finalize check in api design/intent |Mobile  has dependency on Check in team's finalized API designs, 2 data fields (IEN & check in flag) to be exposed by Appt's team, and staging test user availability configuration needed by Appts team|
|Aug '23| At Risk| BE engineering started work to integrate with check in APIs. |  Open dependencies remain|
|Sept '23| At Risk| Development on hold| Tracking dependencies|

</details>

# Detailed Project Scope

Veteran's have the ability to use their VA Health & Benefits app to check-in for a VA In person appt

**User Story:**

As a veteran, with internet connectivity, who has a scheduled in person appt at a VA facility that offers echeck-in I want to have the ability to check in for my appt using my own mobile phone via the Health & Benefits mobile app. 

**MVP Scope** 

Check-in w/pre-registration tasks

The scope of this initiatives provides veterans the ability to check in the day of for a VA In Person appt.  The workflow may include 3 demographic Y/N questions if the Veteran has not reviewed within the last 7 days

Is this your current contact info correct?
Is this your current next of kin info
Is this your emergency contact?

If a Veteran answers No to any of the above questions they are not able to check in via the app and advised to see front desk

If a Veteran answers Yes to all the questions then they can be checked in and should be provided confirmation that they are checked in

This workflow would display a Check in button only (placement tbd) when the veteran is within the check in window (45 min prior to appt or 15 min after appt time) and meets the following criteria

- Insurance information is not needed
- Appt type =  VA In-Person 
- Facility offers eCheckin experience
- Veteran has not already checked in 

- All check-in APIs are avail and ready for BE to consume
- QA has everything they need to test (i.e. test accounts and manage/update test data conditions)
- Mobile will use existing components

**Not in Scope** 

-  Pre-Checkin 
- Updating Pre-registration data
- Push Notifications
- Deep Linking
- Multi-language capability

## Assumption/Risks

**Risks**

**Assumptions**

## OKR and Analytic Metrics 

<summary>Metrics</summary>

|What we are measuring | Why | Event Name 
|-------| ---------| ----- |
| | | |

</details>

## Definition of Done

- All Acceptance Criteria have been met to meet epic defined scope; tickets closed
- QA has provided sign off
- UAT has been completed and successful (if applicable)
- Go/No Go decision received

# Project Links

- [Mobile Patient Check-in Github Folders](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/patient-check-in)
- [ Decision & Q/A log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/patient-check-in/decision-log.md)
- [Check-in Sketch File](https://www.sketch.com/s/e79a827e-42cf-4a82-b554-874c75b5c70e))
- [Vets-api-modules checkin](https://github.com/department-of-veterans-affairs/vets-api/tree/master/modules/check_in#vets-api)
- [Check in Engineering folder](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/engineering)
- [Check in Testing Staging instructions](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/product/product-demos/staging-instructions.md)
- [Chip Design doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/checkin/engineering/full-auth-check-in/chip-design-doc.md)

# Supporting Team

<details>

- **OCTO Product Leads:** Rachel Han and Ryan Thurlwell

- **PM:** Rachel Han

- **Ad Hoc PM:** Meko Hong

- **Engineering:** Jayson Perkins and Jon Bindbeutel

- **Design:** Lauren Russell

</details>

## Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
- [X] Project Kickoff session
- [ ] Initiative Scope finalized
- [X] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
- [ ] Link to Implementation Strategy
   - Implementation Plan
   - UAT Plan
   - Release Plan
   - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide
  - [ ] Coordinate with contact center support teams
- [ ] What’s New Content
- [ ] App Store/In App messaging (if applicable)
- [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
- [ ] App store images needed? Y/N
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by bischoffa** [comment]
2 Blocker removed   
Add Check in e-flag to appts service. Details \[here\](https://github.com/orgs/department-of-veterans-affairs/projects/984/views/1?pane=issue&itemId=33311547)    
Surface IEN data field to appts service. Details \[here\](https://github.com/orgs/department-of-veterans-affairs/projects/984/views/1?pane=issue&itemId=33311621)

**Comment by Hallm13** [comment]
Excluding from Q1 24' plan until blocker is removed.

**Comment by BeccaTupaj** [comment]
This work is being tracked on the Mobile Team backlog in epic #10469 . Closing this ticket.
