### ISSUE TITLE
Sprint 0: Getting Out/Transitioning User State

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#4492]
## Description 
As a designer, I want to complete a Sprint 0 process/documentation for Getting Out/Transitioning User State, so that our team can understand the problem/risks as part of this project and so that leadership can determine whether to move forward.

## Acceptance Criteria
  

-  [x] Complete [Sprint 0 documentation](https://docs.google.com/document/d/1ECCgJNJ1edh8wjJ-sD9y2G86ds_Vd6i_a1bYlRJKLoA/edit#heading=h.91nw9c7vgyg2)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by timwright12** [comment]
@htcollier is this ticket complete? It looks like all the boxes are checked off

**Comment by htcollier** [comment]
The [Sprint 0 doc is complete](https://docs.google.com/document/d/1ECCgJNJ1edh8wjJ-sD9y2G86ds_Vd6i_a1bYlRJKLoA/edit#heading=h.91nw9c7vgyg2), but subsequent work never moved forward.
