### ISSUE TITLE
Offline access/connectivity issues

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#4493]
## Description 
The app currently relies on being connected to a cellular or WIFI network in order to function—or in some cases, provide any access—and treats offline/low connectivity situations as a roadblock or a series of error states (much like a web site) without explaining what’s causing the issue.

## Acceptance Criteria
  

-  [x] Complete [Sprint 0 documentation](https://docs.google.com/document/d/1j7UW1pc3gwNzsyUI7PDr_4bHxwSo17rFMBJkjUNYy9M/edit#)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by BeccaTupaj** [comment]
Closing this issue due to it being stake and documentation not accessible
