### ISSUE TITLE
Reducing Barriers in Form Inputs: Profile/Contact information Form Pattern Improvements 

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#4494]
## Description 
The Profile/Contact information section on the VA mobile app falls short of the best practices for collecting personal information recently presented by USWDS. Per USWDS, the VA mobile app should “Reduce barriers to participation through every interaction.” 

Currently, the app is not leveraging native mobile capabilities (such as autofill) or other time-saving capabilities (including but not limited to autocomplete) to make it less painful to fill out forms on a mobile device. Some of these gaps make the app less accessible, violating WCAG and USWDS guidelines. 

Beyond that, the VA mobile app (and VA.gov in some instances) forms are not providing the kind of flexibility with data input that allows users to accurately update their personal information easily and instantly.

## Acceptance Criteria
  

-  [x] Complete Sprint 0 documentation:  [Sprint 0 Product Brief: Reducing Barriers in Form Inputs
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/form%20inputs/%20reducing%20barriers%20in%20form%20inputs-sprint-0.md)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic
