### ISSUE TITLE
Appt List & Details content alignment - Phone and In Person

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#5136]
# Project Status Overview

During the Appointments V2 integration, we noticed some inconsistencies on how we (mobile) display or do not display information on the appointment list/detail views. Some highlights, to name a few
- Inconsistencies when displaying info such as type of care, reason for care,
- What info is avail for CC vs VA appts etc
- Missing info/instructions for video appts

Mobile POs prioritized changes to Phone and In Person for Q4 2023. Timing for changes to video will be revisited during Q1 2024 Mobile Quarterly Planning. 

**Veteran Pain Points**

1. Missing and confusing appointment information makes the list difficult for Veterans to prepare for their appointments
2. In past research studies, Veterans expressed that missing and or inconsistent appointment details such as type of care, clinic name, physical location, and provider information make it difficult for them to understand their appointments.
 
# Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------| 
|July '23| Green | Performed content gap review of web, mobile, and check in appt list/detail display
|Aug '23| Green |Completed gap review/consolidating all findings to prep for recommendation read out to POs
|Sept '23| Green |Working with appointment team on some of the inconsistency findings; engineering to sync on appt mismatch items. Finalizing doc to share with Rachel/Ryan
|Oct  23| Green | Mobile is working on formalizing alignment and improvement opportunities for In-Person Appointments while also working to size Phone Appointment work to be implemented in Nov 23 |
| Nov '23 | Green | Mobile implementing Person changes sprint 84 with the intent of implementing In-Person changes in Sprint 85. Confirmed no additional work this quarter from PM during Sprint 85 sprint planning. Updates will be made to the call center guide to reflect updates  | 
| Dec ' 23 | Green | Carryover work for both Phone and In-Person changes led to this project continuing on longer than planned. Focusing on getting those changes completed in Sprint 86 leading to a release on 1/2/24. |
</details>

# Project Timeline

<details>
<summary>Milestones </summary>
| Milestone | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Project Prioritized as alternative project for Q3 | Rachel and Ryan | Q4 Planning | 
| Project Prioritized a a prioritized project for Q4 | Rachel and Ryan | Q4 Planning | 
| Step 1 -  Phone - strategize / research | Health | Sprint 82 |
| Step 2 - Phone - define recommendations and draft tickets | Health | Sprint 83 |
| Step 3 - Phone - implement changes | Health | Sprint 84 |
| Phone changes implemented into project | Health | Targeting 12/5/2023 |
| Step 1 -  In Person - strategize / research | Health | Sprint 83 |
| Step 2 - In Person - define recommendations and draft tickets | Health | Sprint 84 |
| Step 3 - In Person - implement changes | Health | Sprint 85 |
| In Person changes implemented into project | Health | Targeting 12/19/2023 |
| Step 1 -  Video - strategize / research | Health | Not yet prioritized |
| Step 2 - Video - define recommendations and draft tickets | Health | Not yet prioritized  |
| Step 3 - Video - implement changes | Health | Not yet prioritized  |

</details>

# Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Product owner of Appointments are making changes to video appointments, thus identified by Mobile POs to do In-Person vs Video changes in the app. Will need Mobile POs to coordinate with VA Appt Team to determine readiness  | External VA Appt Team  & Mobile PO | 

</details>

# Project Links 

<details>
<summary>Links</summary>

- [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/appointments/product/AppointmentListEnhancements/AppointmentListEnhancement_ProductBrief.md)
- [Decsion Log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/appointments/product/AppointmentListEnhancements/decisionlog.md)
- [Figma Mapping](https://www.figma.com/file/k0Ny9KoP1prsI7o661Tyf3/%F0%9F%94%8D-Appointments-Content-Inventory-2.0---Working---VAMobile?type=whiteboard&node-id=0-1&t=OtdNGFckhpKwZsKm-0)

</details>

# Epic Scope

**Discovery & Define requirements** 
- Complete an content audit of appt list and detail view 

**Not in Scope** 

- Implementation; this is epic is to complete the content audit and make recommendation on opportunities to improve Appointment list & detail views.  We will look to create new epics for specific enhancement areas that are identified and prioritized

# Definition of Done 

(What needs to be true to complete epic)

# Supporting Team
<details>

| Name | Role |
| :--------- | :--------|
| Rachel Han | Product Owner, VA |
|Ryan Thurlwell | Design Lead, VA |
| Meko Hong | Sr. Product Manager, Ad Hoc|
| Misty Milliron-Grant | Sr. Content Designer, Ad Hoc|
| Lauren Russell | Sr. UX Designer, Ad Hoc|

</details>

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [x] Project Kickoff session
   - [x] Initiative Scope finalized
   - [x] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [X] Link to Implementation Strategy
       - Implementation Plan - rollout in phases - Phone then In Person
       - UAT Plan - QA testing only, no QA 
       - Release Plan - release updates by appointment type 
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc) - no new metrics 

**Pre-Production Readiness**
- [X] Associate Readiness
  - [ ] Update product guide - planned 
  - [ ] Coordinate with contact center support teams - planned 
- [X] What’s New Content - no
- [X ] App Store/In App messaging (if applicable) - no
- [X ] Coordinate with Release coordinator - planned 
- [X ] App store Content changes required? N
- [X ] App store images needed? N
- [ ] QA Signed off - planned part of standard release mgt 
- [X ] UAT complete - no UAT
- [ ] Obtain Go/No Go decision - PO signoff in release process 

**Feature Go Live**
- [X ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA  modifying existing work thus no waygate / feature flag 
  - **Template: Turn on Waygate/Turn off feature flag**
- [X ] Coordinate with content & release coordinator if what’s new in app is required - not being used 
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [X ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [X] UAT Needed? Yes/No - No 
- [X] Ticket creation 
- [X] Demo feature (mid check, end of development) as its developed
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [x] Review problem/opportunity statement
- [x] Add questions and assumptions to product brief
- [x] Add research links to product brief
- [x] Document high-level research/design plans
- [x] Create lo/hi fi wireframes & user flows if applicable
- [x] Add links to Epic & applicable GitHub folders
- [x] Socialize designs
- [x] Sign off received
- [ ] Complete Design QA
- [x] Does it require component review?
- [x] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [x] Review product brief and surface any questions, assumptions & risks
- [x]  Participate in project discovery and kickoff activities/ceremonies
- [x]  Complete comparative analysis/content research activities for net-new content
- [x] ] Review current content and determine where app may need to differ and potential improvements to share with web
- [x]  Review past VA research and decisions documentation
- [x] Support Research & UX Design in research sessions and synthesis - NA
- [x] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [x]Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [x] Participate in FE hand off
- [x] Complete content QA
- [x] Write copy for What's New In App - NA
- [x] Write copy for app stores' What's New sections.- NA
- [x] Write copy for updated screenshots in app stores  - NA

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [x] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [x] Are there any deadlines that need to be met?
- [x] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [x] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body? No 
- [x] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture? no new analytics 

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by kellylein** [comment]
On track to be completed in Q3 23 (per @MekoHong)

**Comment by bischoffa** [comment]
This epic is only for Q4 and is only looking at In-Person and Phone changes. Any future changes will need another epic

**Comment by bischoffa** [comment]
During FE Handoff in sizing In-Person work, it was identified and seconded that Appointments code needs to be updated and reworked as its a "spaghetti mess". In order to do so Video appointments work needs to be defined which it isn't now and as far as Mobile knows there is no ETA. Given this it was agreed upon to move forward with In-Person work and when Video work is prioritized we include code upkeep / tech debt / rewrite of appointments at that time.  This was mutually agree to by QA, FE, Product.

**Comment by bischoffa** [comment]
@ala-yna noticed I had not moved this over to you. This is the epic for the Appts In Person and Phone ticket work.
