### ISSUE TITLE
Claims: Including "decision review" wording

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#5561]
## Description 
As a Veteran with claims, I want to know that the app shows both my appeals and decision reviews, so that I can be assured that the app is showing all of my appeals, pre- and post-2019.

As part of this story we want to:   

- Create consistency between web and app by updating our "appeals" wording to include "decision review(s)" where appropriate in our copy.

## Tasks

- [ ] Audit instances in which we might need to add the words "decision review(s)" to our Claims experience (including errors & empty states)
- [ ] Meet with Laura W. from Sitewide Content to confirm...TBD
- [ ] Determine which json files I can change vs which Engineering needs to change
- [ ] Write and hand off tickets for Eng, if needed

## Acceptance Criteria
  

-  [ ] All appropriate instances of "appeals" now include the words "decision review(s)".

## Screenshots
**Text above active claims list**
![IMG-0057.jpg](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/5a2ae547-e044-4daf-ad69-1ee17deeb1a5)

**Text above closed claims list**
![IMG-0058.jpg](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/5948466a-4204-4a4a-9eda-06bfd799df1c)

**Text on appeals details screen (2 screenshots)**
![IMG-0059.jpg](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/21eded5e-2539-4745-9a6f-ef755c519a62)
![IMG-0060.jpg](https://images.zenhubusercontent.com/6266db4f486bbe5e4f5cd2fd/96a576de-5563-4a5a-8910-63c68ee90d86)

## Notes & Open Questions

- Per Laura W. on Sitewide Content, decision reviews are appeals. VA created a new name of appeals post-2019. She also confirmed that there are instances on VA.gov that have already included this wording. But not all places yet.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by mistymg** [comment]
Per [this unauth page](https://www.va.gov/resources/choosing-a-decision-review-option/) there are 3 types of decision reviews: Supplemental claim, higher-level review, board appeals. We do include these in the app.

**Comment by mistymg** [comment]
Appeal Details: "appealDetails.pageTitle": "{{appealType}} for {{programArea}}"

**Comment by mistymg** [comment]
Closing this ticket as it will be covered in the numerous copy updates we're making as part of epic 8688
