### ISSUE TITLE
Research & Analytics - Mobile App Retention 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#5952]
## Purpose: #

- During Q2 Mobile Audience work Research and Data discover quant data showing mobile user retention information including a first month drop off and subsequent decline 

## Teams involved: #

- UX Research - Liz Straghalis
- Data Analytics - Greta Opzt
- PM -  Ameet Sarkar

## Actions to be taken in this epic: #

- [ ] Qualitative research with Veterans - recruit
- [ ] Qualitative research with Veterans -host, 
- [ ] Qualitative research with Veterans - gather data
- [ ] Qualitative research with Veterans -present
- [ ] Login analytics 
- [ ] Login dashboard
- [ ] App version impact on retention

## Documentation:

- [2022 Mobile Customer Engagement Benchmark Report from Apptentive/Alchemer ](https://www.alchemer.com/wp-content/uploads/2023/02/Apptentive_Alchemer-2022-Mobile-Consumer-Engagement-Report.pdf)
- [VA Mobile App user Engagement over time April 22-Feb 23](https://docs.google.com/spreadsheets/d/16kMmtDDMDMw63UDvBavnmIRzlgooFP4WKhXV03bnbWY/edit#gid=394478712)
- [Research Brief for User Retention](https://docs.google.com/document/d/1L70Y-ILfyqX4VPrfbWXs64Ap-ldr4w6I154YI6WvRCc/edit)
- [User Retention Conversation Guide](https://docs.google.com/document/d/1nOtJP9Qv3_emugdbojF0z0rZ2dTigNg9ZYiwbsztKr8/edit#heading=h.o1b49rfssykx)
- [User Retention Analysis Demo 6/7](https://docs.google.com/presentation/d/1Ivx3I6Ne6FJ1EBlrPdkcDg4SAdYwgoYfbXaa5RhdD7A/edit#slide=id.g33cc3b02a5_0_49)
- [Mobile App Retention research session prep](https://docs.google.com/document/d/1WDmd9TngL9dxFeRfCwNNgWaMqFF9EGIBhAa7QxcxwT4/edit)
- [Mobile App Retention User Interview Sign Up](https://docs.google.com/spreadsheets/d/1Q-p3TkGTTYIMwqoot9B3p4UhDIe455ZN/edit#gid=1537074559)

**Comment by g-opzt** [comment]
Remaining work in this Epic is covered by other Epics. Closing to reflect completion of scoped work for the combined quant-qual analysis.

**Comment by g-opzt** [comment]
Reopening to reflect work ongoing for presentation to OCTO design group
