### ISSUE TITLE
Patient Check In: Prod Readiness Tracking

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6028]
## Description 
As a Product Manager, I want to track and monitor all tasks that are needed in order to roll out Patient Check-in feature to production

## Tasks
  

-  [ ] Update call center documentation
     - Update to add bullet Preferred Name & Gender Identity under profile section.  
     - Intake ticket: 
- [ ] QA complete & signoff
- [ ] Complete UAT Plan-
- [ ] Conduct UAT Session(s)
- [ ] App store what's new content
          - Approved content: 
          - Add to Release Notes: 
-  [ ] What's new Alert Box 
- [ ] Turn off feature flag/Turn on Waygate 

         

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
