### ISSUE TITLE
Terms of Use - Validation

### ISSUE THREAD

**Issue by Hallm13** [department-of-veterans-affairs/va-mobile-app#6120]
# Project Status Overview

### Project Objective:

VA would like all users utilizing VA.gov and its surrounding sites and services to be presented with a unified version of the Terms and Conditions.  Additionally, they want to be able to track acceptance on a user-by-user basis, including when revisions are made to the terms and conditions and updates are presented to the user.

**Mobile Objective:**

We have identified that the heavy lift of this work will be done by the identity team

**User Experience**

- Upon login; user will be prompted with VA Online Services Terms of Use
    * If the user Accepts, they are able to continue servicing on the VAHB app.
    * If the user Declines, they will be logged out of the VAHB app and messaging displayed explaining what’s next.
    * Users will have the opportunity to accept TOU if they previously declined.

When ready mobile will test in staging. 
 
# Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------| 
|Aug '23| Green| Identity team provided a demo of intended feature scope.  Most if not all of this work will be on the identity side| N/A
|Sep '23| Green|
|Oct '23| Green| mobile team started testing on 10/16 with identity team. Issue was identified and reported.  The identity team is currently working on the fix.
</details>

# Project Timeline

**Update from Identity Team:**  

The plan is to test all week, 9/11-9/15, with the intent of having a fully functioning terms of use page for all [VA.gov](http://va.gov/), MHV, MVH, OCC Mobile App, and VA Health and Benefits app users at the end of testing. 

We do not plan to go into production with this change before 10/5, the dates have not been finalized.

# Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Dependency: Feature avail in staging for mobile to test.  Identity team current focus is on va.gov with next flow mobile (possibly week of 9/18. |  Identity team  | 

</details>

# Project Links 

<details>
<summary>Links</summary>

- [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/identity/Terms%20of%20Use/Product%20Brief.md)

- [Web Figma Prototype]( https://www.figma.com/proto/Fhw9P7r6pyaCGXRmolruoQ/Terms-of-Use?type=design&node-id=381-37&t=D8gUnfhvZbyOxtRu-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A493)

</details>

# Definition of Done 

(What needs to be true to complete epic)

# Supporting Team
<details>

<summary>Contact List</summary>

- Tom Black, Core Identity Team
- Danielle Thierry, CAIA (Sitewide Content) Team
- Alexander Garcia, Identity Core Team Lead Frontend Engineer

Slack: #vsp-identity

</details>

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] Project Kickoff session
   - [ ] Initiative Scope finalized
   - [ ] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [ ] Link to Implementation Strategy - N/A
       - Implementation Plan
       - UAT Plan
       - Release Plan
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by MekoHong** [comment]
Follow thread for staging testing [here](https://dsva.slack.com/archives/C03DY3FN7HQ/p1696541395629659)

**Comment by kellylein** [comment]
POC: Joe Niquette from SiS team

**Comment by EricaRobbins** [comment]
@ajsarkar28 - please remove the "roadmap-DMC" label from this card, as requested by Chris Johnston. Thanks!

**Comment by TKDickson** [comment]
@ajsarkar28 I think we can close this epic.... right?
