### ISSUE TITLE
Veteran Status ID: Content support

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6159]
## Description 
As a Veteran, I want to quick access to a digital ID/status card in the VH&B mobile app, so that I can easily use it to receive discounts and other benefits without needing to carry around a physical card.

As part of this story, I will:   
- Provide content strategy/design support to Product & UX Design

## Tasks

- [x] Attend project kickoff meeting
- [x] Review copy in design files
- [x] Check copy labels against content we're using in app or VA.gov to ensure alignment

## Acceptance Criteria
  

-  [x] Sign off on copy

My recommendations and reasoning for decisions are in [this Figma file](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1707-38955&mode=design&t=3hS8jPVl4R34XL1x-0).

## Notes & Open Questions

8/2: Kickoff meeting. Chatted about scope. Since I will be out, trying to get as much content sign off before this Friday (8/4) but Sitewide Content/Danielle is always there as a resource. Also, since we're not actually shipping this, we could wait for a real final content sign off until I get back.
7/26: Chatted with Adam about this. Super low lift. Just basic data we already have on Veterans (name, branch, years of service, etc.). Should involve just a quick review and sign off. Did mention we need to account for any errors that might occur when we can't retrieve the data for some reason.

## Resources
- [Brea's Figjam exploration](https://www.figma.com/file/MxqpGSmpZrG5HlxB9wNoRP/%234270---Veteran-Status-Card?type=whiteboard&node-id=0-1&t=gf7iXeGvpnrJnsYs-0)
- [Brea's Figma designs](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1707-38955&mode=design&t=ROJQlEw7Gtvudip6-0)

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
