### ISSUE TITLE
Create template for component documentation

### ISSUE THREAD

**Issue by jessicawoodin** [department-of-veterans-affairs/va-mobile-app#6301]
### Description
The mobile design system should use as much as possible from the VADS. Currently, we have our own mobile component documentation template. As part of this ticket, we want to review our template against the VADS component documentation to find out if/where there are inconsistencies and determine if we can resolve any of them. Then, we will address any inconsistencies as part of this ticket.

### Tasks
- [x] Compare [mobile component documentation template](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/new?assignees=&labels=component-documentation%2C+ux&template=common_component.md&title=Common+Component+Ticket%3A%5BInsert+name+of+component+here%5D) to [VADS](https://design.va.gov/components/) and document any inconsistencies
- [x] Review inconsistencies with Jen and make decisions on how to proceed
- [x] Discuss inconsistencies with team to help inform #6276
- [x] Update template in [Google Docs](https://docs.google.com/document/d/1DJoTdwXxUrjmCv8S9XwNvn4uVbd66jyE0XUwqzgZtc4/edit?usp=sharing)
- [x] Update template in [GitHub](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/new?assignees=&labels=component-documentation%2C+ux&template=common_component.md&title=Common+Component+Ticket%3A%5BInsert+name+of+component+here%5D)
