### ISSUE TITLE
Health: allergies

### ISSUE THREAD

**Issue by rachelhanster** [department-of-veterans-affairs/va-mobile-app#6520]
## User Story
As a veteran, I want to view and share my allergies so that I and my health team are informed in managing my health

## Related OCTO Goals 
__________________________________________

## Key Takeaways

______________________________
### Product Checklist

- [ ] Link to Product Brief / Step 0 
- [ ] Link to Product Canvas / Step 1 (if available)
- [ ] Link to Github page
- [ ] Link to Implementation Strategy
  - [ ] Implementation Plan
  - [ ] UAT Plan Yes / No
  - [ ] Release Plan
  - [ ] Metrics identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)
- [ ] Pre-Production Readiness
  - [ ] Associate Readiness
    - [ ] Update product guide
    - [ ] Coordinate with contact center support teams
  - [ ] What’s New Content Y/ N
    - [ ] App Store/In App messaging (if applicable)
    - [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
  - [ ] App store images needed? Y/N
  - [ ] QA Signed off 
  - [ ] UAT complete
  - [ ] Obtain Go/No Go decision from PO 
- [ ] Feature Go Live
  - [ ] Add functionality in demo mode 
  - [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA
  - [ ] Coordinate with content & release coordinator if what’s new is required

### Design/UX Checklist

- [ ] Add questions and assumptions to product brief
  - [ ] Add research links to product brief
  - [ ] Note any related icebox tickets
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows & error handling 
  - [ ] Add links to Epic & applicable GitHub folders
  - [ ] Socialize designs internally
  - [ ] Socialize designs with POs 
  - [ ] Sign off received by POs 
  - [ ] Complete Design QA
- [ ] Component review (if applicable)
- [ ] Accessibility review
- [ ] Update internal documentation 
  - [ ] Add Hi Res files to Figma in Shipped Files
  - [ ] Docusaurous update  

### Research Checklist 
- [ ] Is there a research need for this feature
- [ ] Research plan
- [ ] Recruitment needs with Perigean
- [ ] Qual sessions 
- [ ] Synthesize data
- [ ] Share findings report 

### Content Checklist

- [ ] Discovery work - review / audit / sitewide discussions 
- [ ] Document content recommendations
- [ ] Complete content QA

### Engineering Checklist
- [ ] Are UI designs/ specs available/ready?
  - [ ] If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Update / create engineering documentation 
- [ ] Does this project require api integration?
  - [ ] if yes, what api endpoints are we integrating with and what is the expected response body?

### Analytics Checklist 
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?
  - [ ] If yes, what metrics would we like to capture?
- [ ] Creation of an engineering ticket with what events and their naming convention
- [ ] Dashboard creation / modification to include future changes 

### QA Checlist
- [ ] Create test plan
- [ ] Test accounts needs
  - [ ] List of what staging test accounts will be used 
- [ ] QA Complete
- [ ] Waygate tasks complete

**Comment by kellylein** [comment]
Moved to #6669 since this was an Issue instead of an Epic.
