### ISSUE TITLE
Veteran Status: Final copy review and sign off

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6545]
## Description 
As a Veteran, I want to quick access to a digital ID/status card in the VH&B mobile app, so that I can easily use it to receive discounts and other benefits without needing to carry around a physical card.

As part of this story, I will:

- Review any final copy changes that were made during my PTO and provide final sign-off for release

## Tasks

- [x] Meet with Adam, Brea, Binny about content changes while I was out
    - Everything is fine with MVP for release. 
    - There are a few items that need tweaking for post-MVP (Copy for how user can change incorrect info, alert box for analytics, and error for uploading photo)

## Acceptance Criteria
  

-  [X] Final sign off on all copy for Veteran Status project MVP

## Notes & Open Questions

- What has changed while I was out?
- When is this going to be released?

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
