### ISSUE TITLE
Remote disaster mitigation: Content discovery & strategy

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6602]
## Description 
As a Veteran using the VHAB mobile app, when there is a major error or issue with a feature in the app and my access to this feature is restricted, I want to be told I can't access this feature, why I can't access this feature, and when I might be able to access this feature again, so that I can continue to use the app to my benefit.

As part of this story we want to:   

- Complete initial UX/content strategy and discovery

## Tasks
- [X] Determine and get answers to open questions related to content (see questions below)
- [X] Develop a content-driven solution to solve problem as defined in epic
- [x] Sync with internal team on user flow and solutions 
- [x] Meet with PO to get sign-off on final solution/MVP

## Acceptance Criteria
  

-  [x] Sign off on our suggested use cases

## Open Questions & Answers
- [x] Ideally, we'd be specific about why a Veteran can't access a feature or tool. When we first turn off a feature/tool, we may not know exactly what's going on. Therefore, we might have to start with a generic message. Question: Could we do iterative messaging? Generic to start. And then updated messaging (as soon as we can) with more specifics?
- Per Binny, this is possible. He's pretty sure we can use variable strings to do this. Binny will confirm. 
- For now we'll move forward with this as part of our solution.
- [x] Can we confirm that the fix for whatever problem is happening from the user's perspective will always be to update the app (i.e., the final task is on the user to take action)? Can we confirm that this alert will never just disappear once we fix the issue?
- Per Binny, the vast majority of the time, for users to get access back to something we've restricted, they'll need to update the app.
- There is an edge case in which this won't be the case. This case would be in which the issue is resolved with a BE and they're updates can be made immediately/not require an update via app store.
- [X] If user must update the app, is it in scope to be able to enable that functionality (i.e., include a button that sends them to app store like we do for Encouraged Update)?
- Binny said the update button could be displayed at the exact timing the user can update to the app store (similar to how encourage update works).
- MVP Assumption: We will not need to worry about multiple waygates being turned off (within the same time frames ex: a couple hours apart a few things being broken).
- [X] Can we give users a date/time to update the app in the copy (much like a maintenance window alert)?
- For FE issues that requires an app store update, we would not know the exact time or even day a user could update because of dependency on app store release processes. But we could use copy to assure the user that the issue will be fixed soon and that we'll let them know when it is fixed.
- For BE issues (where an app update isn't needed), we could give an exact date and time the issue will be fixed.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Notes from 9/6 meeting:

Finalized Use Cases
Use case 1: A feature (or part of a feature) is broken in the mobile app but a screen can be rendered.
- Examples: We are showing the wrong personal information in Rx. The feature technically still works and we can show the UI, but it’s a critical enough error that we need to shut it down to fix it.

Use case 2: A feature (or part of a feature) is broken in the mobile app and a screen cannot be rendered.
- Examples: A coding error would mean mobile app would show code nonsense instead of UI or would force entire app to crash.


MVP Approach

Use case #1a: Front end issues
- Since we can render a screen in this use case, we suggest using the colored alert box. This will allow us to give the user an option of completing their task another way. 
- When it’s determined that we need to use remote disaster mitigation/waygate, we will show a (red?) alert box with copy that explains we’re fixing an issue (copy TBD).
- Once we have investigated the issue, if we find we need to update the copy to give further clarity on the problem to the user, we can do so. But this likely isn’t needed unless we can’t give the user another way to access their information.
- We’ll always give the user an alternative way to accomplish their task.
MVP: A general help desk phone number.
We are assuming such a thing exists. This might not work, and we might have to provide specific phone numbers for specific places in the app (i.e., a number for help with claims may not help with prescriptions).
Post-MVP: More specific phone numbers specific to features.
- Since the vast majority of these use cases involve the user needing to update the app (via the app store) to fully resolve the issue, we’re considering showing a button that will take the user to their app store to update once the issue is resolved and an update is available.
This is less essential as we’re already giving the user the ability to complete their task another way (phone number). But it’s still important as the user will eventually need to update the app.


Use case #1b: Back end issues
- This use case will not involve the need to update the app.
- We’ll use most of the same approach as a FE issue above, including:
Use (red?) alert box with general error message that provides a phone number for users to complete their task.
- We won’t need to include an update app button as it’s not applicable. But we could include a date/time when we anticipate the issue to be resolved since BE pushes its fixes regularly and they’re not dependent on a release/app store.


Use case #2 (likely very rare, if ever)
- Since this is an issue in which we can’t even produce a normal-looking screen to show the colored alert box, we suggest using a modal alert.
- The alert modal consists of a heading, body copy, and button(s). Copy (TBD) will explain to the user that we’re fixing an issue with the app. 
- We would likely only show one button, since we may not be sure what the user was attempting to accomplish when this happens, we won’t be able to provide any type of solution other than to wait it out.


Special Notes
- Already-existing error messages will always take precedence over the remote disaster/waygate message.
Example: If we know a user is not allowed access to secure messages because they don’t have a premium MHV account, we wouldn’t use remote disaster/waygate in this instance but the current error message we have in place that explains that to the user.
