### ISSUE TITLE
Travel claims: Content discovery

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6607]
## Description 
As a Veteran, I want to be able to submit and track travel reimbursement claim(s) for eligible past appointments using the VA: Health & Benefits mobile app.

As part of this story, I want to:   

- Complete discovery work from a content point of view for this project.

## Tasks

- [X] Attend kick-off meeting
- [x] Get understanding of scope of work
- [x] Review all docs/resources in epic
- [x] Get latest content from web team, including errors

## Acceptance Criteria
  

-  [x] Estimation of time needed/delivery timeline for Content for whole project
-  [x] Latest web content artifacts for Lauren to use in designs

## Open Questions & Notes
- Which experience are we loosely basing ours off of? The new VA.gov experience the Check In team created? Answer: Basing copy off VA.gov Check In team copy and will modify for our instance as needed.
- Scope is just "simple claim."

## Ticket Checklist

- [X] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Some thoughts after reading resources in epic:
- From Check In team's research, Veterans may still think they have to file a travel pay claim in BTSSS. Could we use wording that communicates to the Veteran that no other action is needed from them (no paper file, no BTSSS, etc.)?

**Comment by mistymg** [comment]
Updated epic with most recent links and added some notes around these links for context.

**Comment by mistymg** [comment]
Met with Lauren on Friday (9/1) and agreed to use most recent Check In content for our Travel Pay instance and modify copy as we design for our needs. Most recent content from Check In team is in our Travel Pay epic. I estimate our Travel Pay instance to take me 2 sprints to complete content design. This includes updating wires/designs with latest copy, writing new copy to suit our needs, and getting sign-off from Danielle/Sitewide Content team. This 2-sprint estimate doesn't include Content QA while Eng is building.
