### ISSUE TITLE
Rx: Content recommendations for Rx problems

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6611]
## Problem statement and possible solutions from PO

- **Problem A**: Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill.Participants did not use any other prescription status besides Active to determine what to refill. When prompted to define them, participants provided their own interpretation when scanning the list and the Filter options. Veterans view a list of “actionable” scripts, defined as medications they currently take or are looking to refill, without having to use “Filter by.”

_POs Proposed solutions_:
As a veteran, I easily view scripts I’m currently taking or am looking to refill.
1. Status quo, no change to veteran’s view of Health/Prescriptions default list
2. Change default list to all Active statuses. Use plain language content to lead 
veterans to see other scripts.
3. All Active statuses as a group. Keep option to select individual Active status. 

- **Problem B**: When a filter is on, header 1 and header 2 counts are unequal. _PO's Proposed Solution_: Update second header, so it’s dynamic. E.g. 13 of 31

- **Problem C**: Two statuses need to be deleted: (Active: Suspended & Non-verified) NO ACTION NEEDED HERE

- **Problem D**: Veterans know that medications documented but not dispensed by a VA pharmacy is not listed in app, so they can use the list to ?. Veterans may not understand the app’s usage of “VA prescriptions.” Many of those non-VA meds are prescribed by VA Providers and sent to non-VA pharmacies so they are technically VA prescriptions (just not dispensed by VA) _PO's Proposed Solution_: Update “Help” content

**As part of this story, I will:**

- Deliver content recommendations for Problems A, B & D

## Tasks

- [X] Sync with Meko and/or Lauren to understand PO asks/problem statement
- [x] Review Medications team most recent designs/content
- [x] Sync with Lauren on Problems A, B & D
- [x] Document final recommendations for problems in [Figma](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1203-44&mode=design&t=tK3MQkMl8fRS4FMx-0)

## Acceptance Criteria
  

-  [x] Documented content recommendations to solve Problems, A, B & D

## Resources

- [Ryan's Figma design](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1203-44&mode=design&t=QqUqzE2ytu8zHZzl-0)
- [Medications team most recent designs](https://www.sketch.com/s/11f59942-a697-451c-ac26-6624754b2616/a/kKdalrA)

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Problem D clarification: We're not showing all "VA prescriptions". A VA provider can prescribe to a Veteran and it could be filled/refilled at a non-VA pharmacy.
