### ISSUE TITLE
UX Discovery: Prescription List View Enhancements

### ISSUE THREAD

**Issue by MekoHong** [department-of-veterans-affairs/va-mobile-app#6625]
# Description

As part of this story we want to explore solutions to help solve the following problems as outlined in the Design Requirements doc [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/medication/Product/Prescription%20List%20View%20Enhancements/Discovery%20Sprint%20Requirements.md)

- Problem A:
Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill.

- Problem B: 
When a filter is on, header 1 and header 2 counts are unequal.

- Problem D:
Veterans know that medications documented but not dispensed by a VA pharmacy is not listed in app, so they can use the list to . Veterans may not understand the app’s usage of “VA prescriptions.” Many of those non-VA meds are prescribed by VA Providers and sent to non-VA pharmacies so they are technically VA prescriptions (just not dispensed by VA)

[Figma](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1203-44&mode=design&t=hBCwYKZStguV3zmJ-0) draft provided by Ryan 

# Action Steps

- [x]  Identify and make recommendations for potential UX solutions for the above problem statements. 
- [x]  Share recommendations with Rachel/Ryan

Post first review with Rachel/Ryan below outline of next steps to explore,  let's focus on the following:

- [x] 1. Design/content: how might we get users to use the "start refill" button more? the most valuable part of the feature is getting users to the list of refillable scripts, and yet users aren't getting there. e.g. What would the design look like, if we had the "start refill" button at the bottom of the screen 
Discussed these points with POs in 9/21 call:
- **Request and track refills**: Get to the list of refillable scripts, we can surface that information within the list. See [Concept sketches](https://balsamiq.cloud/s4uw4la/pnnwuqv/r3B0C) for ways we can do that.
- Positioning the button at the bottom of the screen due to a11y / IA-Nav patterns. 
- The primary action is a pattern established in the [IA/Nav 2.0 work](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/UX/Foundations/Information-Architecture)
- This placement would conflict with the pattern set for Messages
- This placement would sit on top of the tab navigation
- The current placement works well for AT users (VoiceOver and TalkBack navigation) 

- [ ] 2. Analytics: in service of getting users to submit refill requests, what value is there to A/B test default list? A) status quo, All scripts. B) all Active plus Active subset scripts 
        - [Figma UI design supporting Test B](https://www.figma.com/file/Si4LF4t8VOv8emdCovv3U3/%F0%9F%94%8D-Prescriptions-2.0---Working---VAMobile?type=design&node-id=1339-5160&mode=design&t=pKDVsSIjmUeGWVdy-4)

- [ ] 3. bring in any app store reviews related to Rx, especially june/july/august reviews

- [ ] 4. additional ideas as lauren/greta/misty strategize

**Comment by kidlaurenpeace** [comment]
Discussed with Meko, reopened the ticket. Added labels and sprint.

**Comment by kidlaurenpeace** [comment]
Corrected the sprint label (had the wrong date)

**Comment by MekoHong** [comment]
Added new next steps as a result of 9/14 review session with Rachel & Ryan.  Continuing discover through sprint 80 and potentially sprint 81.

**Comment by kidlaurenpeace** [comment]
Added link to recommendation after 9/21 call. Will look to close this by the end of sprint 80. Will preserve more expansive design options for a future state.
