### ISSUE TITLE
UX - Availability Framework (Remote Config) - Design phase 

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#6637]
## Description 
As a Veteran using the VHAB mobile app, when there is a major error or issue with a feature in the app and my access to the feature I want to use is restricted, I want to be told I can't access this feature, why I can't access this feature, when I might be able to access this feature again (if applicable) and how I can accomplish my task another way, so that I can solve the problem I intended to use a feature in the app for & continue to use the app to my benefit.

As part of this story we want to:   
Design the flow and component we will use to communicate each of the following use cases, keeping in mind the large system of ways we currently use components to communicate messages from the app:
1. A screen is so broken in the mobile application that it can’t be rendered without crashing app/red screen of death.
2. A screen element, feature (or part of feature) is broken in the mobile application—and the feature entry point can still be accessed & a screen can still be rendered.
    A. and we are working to resolve it remotely
    B. it is now resolved and installing a new version of the app will correct the problem
3. A problem exists with a feature for a certain subset of users, and due to technical limitations we need to restrict access to the entry point for them—but not all users.

## Tasks
Create comps for each of the various usecases, indicated how many variations in copy there need to be

## Acceptance Criteria
  

-  [x] Design for all use cases complete

## Notes & Open Questions
[See Availability Framework (Remote Config) - Discovery - VA Mobile](https://www.figma.com/file/0Z8pARNjQdDrOJCxtJUyG0/Availability-Framework-(Remote-Config)---Discovery---VA-Mobile?type=whiteboard&node-id=0%3A1&t=anemetuo2eFKrWGo-1)
## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by StacyB2023** [comment]
@brea11y @htcollier: Just adding the use cases here also discussed on 9/11 for reference. Also in the overall epic

[FINALIZED USE CASES]([Uploading... Availability Framework Use Cases-MVP 9_11_23.pdf]
)

**Comment by bischoffa** [comment]
@StacyB2023 I did not move this from Next Sprint column to Current Sprint as I didn't see a sprint tagged. If it needs moved can you tag it with the sprint and move it?

**Comment by StacyB2023** [comment]
@bischoffa Thanks Adam. Updated to current sprint and added tags. cc: @brea11y
