### ISSUE TITLE
Veteran status: Adding disclaimer text

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6666]
## Description 
As a Veteran using the veteran status tool, I need to know that this tool only proves my service and doesn't prove I can get VA benefits.

As part of this story we want to:   

- Provide final copy for disclaimer text

## Tasks

- [x] Rewrite copy provided by Melissa Rebstock
- [x] Get Danielle/Sitewide Content feedback
- [x] Add final copy in [Figma](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1710-39009&mode=design&t=nyDqqzfkCAHlZ1fH-0#549489699)
- [x] Get sign-off from PO (Ryan)
- [x] Make sure Eng has correct copy

## Acceptance Criteria
  

-  [x] Final copy in [Figma](https://www.figma.com/file/Wjq9DkQ3ulXlHhbMrpNHME/%F0%9F%94%8D-Profile-2.0---Working---VAMobile?type=design&node-id=1710-39009&mode=design&t=nyDqqzfkCAHlZ1fH-0#549489699)
-  [x] Danielle/Sitewide Content approval
-  [x] PO (Ryan's) approval

## Notes & Open Questions

Melissa Rebstock (PoC for the VIC card at VA. Branch Chief, Digital Experience. she is part of VEO) suggested the following blurb: Veteran status is verification of proof of service in the Uniformed Services of the United States and does not serve as proof of entitlement to any benefit administered by the Department of Veterans Affairs.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Final approved copy for disclaimer: 
You can use this Veteran status to prove you served in the United States Uniformed Services. This status doesn’t entitle you to any VA benefits.
