### ISSUE TITLE
Personalized Home Screen: High level MVP Wireframes

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#6667]
## Description 
Document MVP approach for personalized home screen recommendation.

## Tasks
Create wireframes for recommended for home screen approach (based on outcome of [Personalized home screen: High level UI concept creation & audit #6594](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6594), preliminary ENG feasibility review, and PO feedback):

- [x] Wireframe recommended approach for home screen UI architecture (selected from audit finalists & based on collaboration with ENG & PM) and flesh out additional high level states (How direction behaves in various situations (loading, no data, health only, claims only, etc))
  - [x] Share recommendation with POs
- [x] Iterate on recommendation based on PO feedback 
  - [x] Feasibility review & input from ENG, PM
  - [x] Share recommendation with POs

## Acceptance Criteria
  

-  [x] Initial wireframes for recommended home screen direction
    -  [x] High level MVP recommendation

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x]  Linked to an Epic

**Comment by htcollier** [comment]
Created & shared [recommended approach for home screen UI architecture](https://balsamiq.cloud/s4uw4la/pnnwuqv/rFAC0) with PO 9/14.

**Comment by htcollier** [comment]
Began exploring an alternate approach to personalized home screen based on PO feedback received 9/18. Work in progress: https://balsamiq.cloud/s4uw4la/pnnwuqv/rB0B9

**Comment by bischoffa** [comment]
Adding Sprint 81 as the ticket was not closed out in 80. Carryover work.

**Comment by bischoffa** [comment]
Carryover Sprint 81 into 82

**Comment by htcollier** [comment]
Round 2: Shared alternate approach with ENG on 10/6 to discuss feasibility.
- [Personalization - round 2: ENG feasibility](https://balsamiq.cloud/s4uw4la/pnnwuqv/r1735)

**Comment by htcollier** [comment]
Shared recommended direction with POs 10/12: [Personalization - round 2 - recommendation](https://balsamiq.cloud/s4uw4la/pnnwuqv/r47B3)
- Made some minor edits based on feedback.
- Next step: share high level version with external teams: [Personalization - round 2 - recommendation - for external sharing](https://balsamiq.cloud/s4uw4la/pnnwuqv/r3A0B)
