### ISSUE TITLE
Availability framework: Copy for use cases

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6676]
## Description 
As a Veteran using the VHAB mobile app, when there is a major error or issue with a feature in the app and my access to the feature I want to use is restricted, I want to be told I can't access this feature, why I can't access this feature, when I might be able to access this feature again (if applicable) and how I can accomplish my task another way, so that I can solve the problem I intended to use a feature in the app for & continue to use the app to my benefit.

As part of this story we want to:   

- Write copy for approved use cases

## Use Cases
USE CASE 1: A screen is broken and it cannot be rendered without crashing app/red screen of death (for ALL users) 
USE CASE 2: A feature (or part of a feature) is broken in the mobile app but a screen can be rendered (for ALL users) 
USE CASE 3: A screen element, feature, or part of feature is broken (for SOME users, not all). The feature entry point can still be accessed and a screen can still be rendered, but some folks can see data within the feature and others can’t.

## Tasks
- [x] Sync with UX designers (Brea/Holly) to ensure understanding of scope, use cases, and content strategy
- [x] Write copy for use case 1
- [x] Write copy template for use case 2a and 2b
- [x] Write copy template for use case 3a and 3b
- [x] Get and incorporate feedback from Danielle
- [x] Review with PO (Rachel)

## Acceptance Criteria
  

-  [x] Final copy for [in Figma](https://www.figma.com/file/L702ULyDKZbO2WBIHdJbyX/%F0%9F%94%8D-GlobalFeatures-2.0---Working---VAMobile?type=design&node-id=1212-806&mode=design&t=NLxyiPXIcNKbGXrh-0) for use cases

## Notes & Open Questions

- Should we start to set up governance around this now?

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Got Danielle approval/feedback during 1:1 today

**Comment by mistymg** [comment]
Met with Rachel today and got her sign off on copy approach.

**Comment by mistymg** [comment]
Will do governance piece next sprint.
