### ISSUE TITLE
Rx: Continued work on prescriptions list view enhancements

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6726]
## Problem statement and possible solutions from PO

- **Problem A**: Veterans struggle to review their full list of prescriptions to identify the correct prescription they were looking to refill.Participants did not use any other prescription status besides Active to determine what to refill. When prompted to define them, participants provided their own interpretation when scanning the list and the Filter options. Veterans view a list of “actionable” scripts, defined as medications they currently take or are looking to refill, without having to use “Filter by.”

_POs Proposed solutions_:
As a veteran, I easily view scripts I’m currently taking or am looking to refill.
1. Status quo, no change to veteran’s view of Health/Prescriptions default list
2. Change default list to all Active statuses. Use plain language content to lead 
veterans to see other scripts.
3. All Active statuses as a group. Keep option to select individual Active status. 

- **Problem B**: When a filter is on, header 1 and header 2 counts are unequal. _PO's Proposed Solution_: Update second header, so it’s dynamic. E.g. 13 of 31

- **Problem C**: Two statuses need to be deleted: (Active: Suspended & Non-verified) NO ACTION NEEDED HERE

- **Problem D**: Veterans know that medications documented but not dispensed by a VA pharmacy is not listed in app, so they can use the list to ?. Veterans may not understand the app’s usage of “VA prescriptions.” Many of those non-VA meds are prescribed by VA Providers and sent to non-VA pharmacies so they are technically VA prescriptions (just not dispensed by VA) _PO's Proposed Solution_: Update “Help” content

**As part of this story, I will:**

- Provide content support as work continues

## Tasks

- [X] Meet with POs to share recommendations
- [X] Get sign off on content for Problem D
- [ ] Align with internal team on solutions for Problems A and B 

## Acceptance Criteria
  

-  [X] Final copy for Problem D ([Eng ticket 6804](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/6804))
-  [ ] Final agreement on solution for Problem A and B 

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
