### ISSUE TITLE
Travel: Cont. content support for design phase

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6802]
## Description 
As a Veteran, I want to be able to submit and track travel reimbursement claim(s) for eligible past appointments using the VA: Health & Benefits mobile app.

As part of this story we want to:   

- Continue to provide content support for wireframes

## Tasks

- [X] Show initial content/wires to stakeholders (Rachel, Mark D)
- [x] Continue to edit and update content in [Figma wireframes](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=1619-6511&mode=design&t=yp8xJEbLFpT3CEpb-0)
- [x] Find copy (if any) for communicating the following:
- If user has questions, where do they go? Is there a phone number?
- If claim is denied, how do they appeal?
- Are there timeframes user can expect to wait to get paid (from approved for payment to in bank account)?
- [x] Review content with Danielle for initial feedback/concerns
- Address all comments in Figma with her
- [ ] Update Figma with Danielle's feedback

## Acceptance Criteria
  

-  [x] Approved copy in Figma wireframes for this stage of project
-  [x] Updates to copy that account for bringing timeframe of filing claim further up the user journey

## Notes

**PO requests from 9/28 meeting**
Rachel would like:
- Eligibility tag to be more active
- Veterans to understand they have 30 days to file claim earlier up in the user journey than at the end

**MVP AC for inclusion in Appointments**

1. User navigates to Health/Appointment/Past
2. For an eligible appointment, user sees option to start a travel claim
- Eligible appointment = Veteran is checked in and appointment date is < 30 days old
3. User sees messages on tasks to do before submitting a claim and getting reimbursed. User is redirected to do these tasks
4. For users who have already successfully submitted a claim and got reimbursed, do not show message(s) in step 3
5. User submits a claim
6. User tracks claim status

**Status casing**
- From Chris A (FE Eng) on our team, we can change the BTSSS statuses from title case to sentence case in the code.

## Other resources
[Mural of processes/checkpoints/user journeys](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1695227510793/07687c25d2782e5e1fef633f9bbd02b8a4d937f3?wid=0-1695231173756&sender=u85a35f55e50d7c375c782462)
[Sketch of BTSSS travel reimbursement claims statuses](https://www.sketch.com/s/50c13762-b34d-44df-a657-6a75872faf82/a/My3nJvl)
[BTSSS screens](https://www.sketch.com/s/50c13762-b34d-44df-a657-6a75872faf82)

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
[Great Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1696005901410659) between me, Mark Dewey, and Ben Brasso on statuses, definitions, and appeals.

**Comment by mistymg** [comment]
Things still needed from BTSSS

**Comment by mistymg** [comment]
Update:
Per Adam, we will wait for a faster API so we're not waiting 30-60 seconds for the status.
Also, got a PDF of Veteran-facing definitions of statuses from Mark Dewey. Uploaded to epic links section.
