### ISSUE TITLE
MHV Health Service Premium Account Bug Login Issue - Preventing Premium Accounts from seeing Secure Messaging & RX in the App

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6852]
# Project Status Overview

### Problem

- A user has an MHV account and a logingov/IDME account. The user has never used their logingov/IDME account to sign into MHV's site. When the user signs into the mobile app or MHV with their MHV credentials their account shows up as premium, but when the user signs into the mobile app with their  logingov/IDME account they don't show up as premium until they use that account to sign into MHV's site since MHV has logic in place to upgrade logingov/IDME accounts.
- Messages is the only one that's surfacing this issue  because it's the only one of the services we offer that requires premium. Appts doesn't fall under MHV, RX is available for advanced users, which logingov/IDME accounts seem to be by default, and vaccines has no account level check in place
- Mobile identified the issue in July 2023 which originally thought it was a biometrics issues, but later found out its been a known pre-2023 issue within MHV 
- Mobile estimates this impacts ~9000 veterans each month which is ~1% of mobile app users monthly active users
- Originally thought to only impact SM back in July but in Oct/Nov believe RX feature is now impacted 

### Project Objective:
- Resolve issue within SM in VAHB; as of Nov 2023 now need to resolve within SM and RX 
- Attempt to have MHV implement long term solution that would take MHV and SIS changes involving API Account Creation (solution was backlogged 10/4/2023 no ETA on implementation) 
- Mobile to attempt to implement MHV's proposed solutions from [MHV shared a write up of the problem and solution options](https://github.com/department-of-veterans-affairs/va-mobile-app/files/14298349/2023.09.27.MHV.account.problem.and.solutions.5.docx) 
1.	Direct users to a phone number, and users info are verified to get accounts connected. We know this works for web, but 1) it’s asking veterans to do a lot of work; 2) no one in MHV world or VA Identity know how veterans are being directed to get this done except that a message is shown.
2.	tell a user to go to MHV classic, sign in with their ID.me or Login.gov account. They'll be prompted to sign MHV's T&C. That will create teh MHV account under the hood. And they'll be able to use SM in VA.gov and the mobile app. we don’t know if this works.
- Attempt to implement MHV Solution 1 (call help desk) (deemed not viable as MHV is unable to provide documentation on how web handles it today) 
- Attempt to implement MHV Solution 2 

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Long Term Solution - MHV SM to expose upgrade endpoint to SIS for them to use to upgrade account. 10/4 Rachel confirmed that she has reached out to the relevant health business owners for MHV to prioritize this and also that Identity / SIS has this on their backlog.   | MHV SM & Identity / SIS | None |
| Short Term Solution 1  - Mobile to add messaging in the app to help Veterans resolve the issue. Mobile in need of content and information from MHV SM on how they are solving today on the web. Mobile has reached out through 4 different slack channels, coordinators from MHV Weekly Standup, and 5 different MHV SM contacts but was unable to find what was needed. 10/25 - Danielle reached out our last hope in Solution 1 - MHV SM Sylvia - but they too couldn't find any materials or documentation. Though MHV is doing this today unable to find any materials to support it. Thus Rachel Han approved of not pursing this option any longer and moving to Solution 2. | MHV SM  | None | 
| Short term solution 2 - Per documentation from MHV it was unsure if it will work but something POs have asked Mobile to moved forward with.  Per discussions with CAIA and others in MHV this is not the ideal solution, however given its our only option we must proceed with it. Mobile needs to validate it using MHV test accounts and test data.  MHV provided test data and Mobile could log into MHV now needs to log into id.me and login.gov which requires SIS help.  | MHV & SiS   | Unknown |
| Jayson (Mobile BE Lead) and Patrick Bateman had discussions early Feb which brought up a couple other known login issues that may be relevant here. Also may be part of Carnetta's 10 login issue list.  | MHV | no ETA | 

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

| Milestone / Item | Timing | 
|-------| ---------| 
| Rachel notified Mobile team of a login / biometric issue via [Slack](https://dsva.slack.com/archives/C018V2JCWRJ/p1689177271601149) | July 2023   |
| BE Discovery of Issue. Details in[ ticket 5986](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/5986)  | Aug 2023   |
| Short Term Mobile Only Solution Idea - Mobile to Add Messaging   | Aug 2023   |
| [MHV shared a write up of the problem and solution options](https://github.com/department-of-veterans-affairs/va-mobile-app/files/14298349/2023.09.27.MHV.account.problem.and.solutions.5.docx) | 9/27/23 |
| Long Term MHV and Mobile Solution - MHV and Identity Backlog Request  | Backlogged - 10/4/2023 Implementation - No ETA   | 
| Short Term Solution 1 (call Help Desk to fix) deemed not viable as MHV can't find documentation on how they handle this with veterans today on web | [11/20/24](https://dsva.slack.com/archives/C04DRS3L9NV/p1701183270795589?thread_ts=1698242434.940089&cid=C04DRS3L9NV)
| Confirmed Mobile will use Short Term Solution 2 (Veteran to self service but going to MHV class, sign in with id.me/login.gov and sign T&CS. Then go back to sign into the mobile app and it should work)  | [11/28/23](https://dsva.slack.com/archives/C04DRS3L9NV/p1701183270795589?thread_ts=1698242434.940089&cid=C04DRS3L9NV) |
| Short Term Solution 2 Copy Completed and Approved by CAIA. Note it may need to be changed depending on findings from Mobile trying to validate the proposed solution.  | Dec 2023 |
|  Short Term Solution 2  Testing - For Mobile to test, Mobile needed MHV to provide test accounts and data prepping to proceed. Mobile had to get MHV test account and needs MHV/ SiS help with next steps  | Started Nov - ongoing |
Short Term Mobile Only Solution Implementation  | TBD | 
| MHV identified there may be other login issue relevant. Patrick Bateman to investigate and trace example MHV users to understand why each mhv id was blocked. Discussions that it may be relevant to Carnetta's list of 10+ login issues | [January 31st](https://dsva.slack.com/archives/C018V2JCWRJ/p1706195087269779) | 
|  Short Term Solution 2 Implementation | TBD | 
| Short Term Solution 2 Release date | | 
| Long Term MHV and Mobile Solution Implementation - MHV has known it for some time but work not prioritized | TBD   |

</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|July '23| Green | Mobile notified of a possible bug that was submitted to the VA on 1/23/2023 ; believe its tied to Biometric log in; Mobile created bug ticket [5986](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5986); ticket prioritized and BE Discovery work started  | 
|Aug '23| Yellow  | BE Discover work wrapped up. Confirmed this is not a biometrics issue. Confirmed this was a known MHV SM login issue, was first Mobile was aware. MHV SM current provides messaging to the Veteran to call into Support and Support manually upgrades their account to premium and ties it to their existing MHV account. Long term solution MHV SM needs expose an upgrade endpoint to SIS for them to consume. MHV SM has not prioritized the long-term work. Mobile planned to add messaging and use existing message but informed to use what MHV SM has. Mobile worked with MHV SM and unable to find content / message or any MHV SME with knowledge of the message. | Mobile unable to get content / messaging from MHV SM; LT solution not prioritized  |  
|Sep '23| Yellow | Mobile continued to work to find the content. Posted in 4 different Slacks, talked with 5 individual people, talked about it in MHV SM but could not find the messaging. MHV SM recommended reaching out to Carnetta Scruggs who Rachel will initiate communication with ; 9/25 Rachel brings up this being tied to Account Creation API and part of Terms and Conditions ; 9/26 Rachel shares a new contact Jason Boire and shares a word doc on the overall context of this; bug ticket migrate to this project epic for management and prioritization | Mobile unable to get content / messaging from MHV SM; LT solution not prioritized  
|Oct '23| Yellow | Met with CAIA on 10/25. Using mhv-health-portal-coordination for async updates. Danielle (CAIA) to reach out to a contact for more information on the doc's 1st solution. Confirmed with the group that we will use Solution 2 if we cannot find information |
| Nov '23 | Yellow | MHV unable to find copy / messaging for the call center solution thus its no longer a viable solution. Mobile and CAIA team drafted up dynamic solution for the user to self-service the issue (solution 2). This solution has been tested on MHV website and works, but it has not been tested in context with the mobile app error. | Mobile testing needs test accounts from MHV |
| Dec' 23 | Yellow | Coordinating with Janie Tankard-Carnock and Dimitar Tzvetanov to get a test account in order to test MHV's proposed solution for mobile to use. 2 test accounts created on 12/4 and Jayson (Mobile) and Dimitar collaborating on how to properly set-up the test accounts. |  
| Jan '24 | Yellow | Due to holidays and other Mobile projects prioritized this fell through the crack but got picked back up late January. Mobile timeboxed this work for a couple days until Mobile Leads prioritize this work with a Flagship Team. Mobile QA worked with MHV to sign into MHV staging which had various challenges. Mobile was able to login and validate MHV test accounts has SM has expected. Now have to set them up in id.me login.gov which requires SiS work. Timebox work ended, waiting new team to prioritize this work.  | Prioritization , test findings , user reports that RX may be impacted by this issue |
| Feb 24 | Yellow | Stacy Blackwood the Mobile PM from the Mobile Platform API Team will be the lead PM for now on this project.  Positive conversations between Jayson (Mobile BE) and Patrick Bateman in [DSVA Slack ](https://dsva.slack.com/archives/C018V2JCWRJ/p1706195087269779). Patrick to trace down a sample set of MHV ids that were blocked from SM across all methods, has engaged Janie. | Prioritization , Mobile BE Lead out for a couple weeks, could be tied to other log in issues. 
| May 24 | Yellow | This issue has been solved for Secure Messaging. It cannot be solved for RX until MHV creates a new endpoint. | Total resolution is blocked indefinitely until a fix for RX can be created by MHV.
</details>

# Detailed Project Scope 

### Problem Statement

There are 2 things that could have been causing the issue based on discussion with Identify and MHV SMEs:

1.  If a user creates an id proofed account but doesn't use it to sign into MHV's site then their account won't be upgraded. Thread of details. This is handled by web by showing users an error message requesting that they call MHV to have support manually upgrade their account to premium and tie it to their existing MHV account.
   -  Logs indicate a small % of people hitting MHV have all the correct attributes but are still getting denied access to SM. I will create a ticket to investigate this. The % is extremely small. 32 total instances in the last week and some are the same user multiple times.

3. Longterm solution - MHV needs to expose the upgrade endpoint for SIS to consume and use to upgrade accounts. No ETA, MHV needs to prioritize exposing the upgrade API , SIS needs to prioritize consuming and using the API

### Assumptions 

- If unable to direct Veterans to call and get their account fixed, we will provide directions to the Veterans on how to resolve (go to MHV classic, sign in with id.me/login.gov, sign MHV T&Cs (which will given them the appropriate access) so that they can access SM in VA.gov and mobile app. 

### Risks 

- How VA decides to resolve the situation could impact Veteran relationship - making them take steps to resolve vs calling in 
- MHV saying there is a solution but been unable to find the solution messaging 

### Definition of Done 
<details>
<summary>Following needs to be true</summary>

|Item | Completed | 
|-------| ---------|
| Mobile adds new messaging in App to inform Veteran what to do when the issue arises | | 
| | | 

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Mobile to add new messaging | MHV SM to prioritize long term solution with MHV | 
|  | Terms and Conditions work - that is in a separate epic | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>

- [2023.09.27 MHV account problem and solutions.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXJpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f07e6c9eb815cfeabcc96aeb8de2c588134dd428/2023.09.27%20MHV%20account%20problem%20and%20solutions.docx)

### Team Members

<details>
<summary>Contact List</summary>

Mobile
- **OCTO Product Leads:** Rachel Han
- **Ad Hoc PM:** Adam Kasmier
- **Engineering:** Jayson Perkins 
- **Content:** Misty Milliron-Grant

MHV SM 

- Individuals
   - Kay Alexanderson - PO 
   - Bryan Riley - PM 
   - Christy Gales - PM 
   - David Rawlins
   - Haritha Cheruvu - Lead Engineer
   - Jason Boire 

- Slack Channels Threads
   - [MHV-Secure-Messaging](https://dsva.slack.com/archives/C03ECSBGSKX/p1694702796051919)
   - [MHV-Portals-Access](https://dsva.slack.com/archives/C04HPLCRVMG/p1695231012351369)
   - [MHV-SM-Backend](https://dsva.slack.com/archives/C05TU9FPZU0/p1695225402506559)

Identity

- Joe Niquette - Surge Identity Team - Lead Engineer
- Trevor Bosaw - Surge Identity Team - Engineer
- [VSP -Identity Slack](https://dsva.slack.com/archives/CSFV4QTKN/p1689959585422909?thread_ts=1689608324.102329&cid=CSFV4QTKN)

Content 

- Danielle
- Laura
- Intake Request Ticket

</details>

### OKR and Analytic Metrics 
<details>
<summary>Metrics</summary>

|What we are measuring | Why | Event Name 
|-------| ---------| ----- |
| | | |
| | | |

</details>

### Questions 
<details>
<summary>Open Questions</summary>

</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer |
|--------|----------|
| | |
| | |

</details>

### Change / Decision Log 

<details>
<summary>Change & Decision Log Details </summary>

| Change | Rationale | Decision Maker |  Date Change |
|-------|------- | -------- | -------- | 
|  New request. Mobile to initiate CAIA request on behalf of MHV SM and lead the convo. Request by POs  | Mobile asked to help lead the effort to find it for MHV SM given Mobile raised the bug | Lauren and Rachel | MHV Standup Meeting early October | 
| Mobile to lead push on finding content for both Web and Mobile | This challenge impacts Mobile more, so Mobile should help push it along  | Rachel | 10/24 Sprint Planning |
| | | | |

</details>

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [X] Identify short term and long term solutions 
   - [ ] Gather requirements and details from MHV - in progress
   - [ ] Draft tickets for Mobile team 
   - [X] Create Epic 

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide - add to the error message section 
  - [ ] Coordinate with contact center support teams
- [X] What’s New Content NA
- [X] App Store/In App messaging (if applicable) NA
- [ ] Coordinate with Release coordinator
- [X] App store Content changes required? No
- [X] App store images needed? No
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>
- [ ] Review MHV messaging and content used on the web 
- [ ] Content Team Intake Request Form 
- [ ] Draft messaging / design 
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Content Checklist</summary>

- [X] Participate in project discovery and kickoff activities/ceremonies
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by bischoffa** [comment]
MHV Standup 9/27 POCs   
 

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/805d89e2-a2e8-4917-929d-36e7a13c4d82)

**Comment by TKDickson** [comment]
Marking with scrubbed label just to get the epic out of the bug scrub view :)

**Comment by bischoffa** [comment]
This project is being worked in Q4 but was not part of Q4 planning or on the Kanban board. Just added it to the board.

**Comment by bischoffa** [comment]
[Slack thread with more details](https://dsva.slack.com/archives/C04DRS3L9NV/p1698242434940089)

**Comment by bischoffa** [comment]
Confirmed that we will go with solution 2 from OCTO's original solution doc. This is because MHV cannot find any messaging that would be needed for solution 1. 

<img width="698" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnluQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c94d51e9c18f7831660a0942e8305c7ef36e9d5/image.png" alt="image.png" />

Next step is to make sure Solution 2 works - which VA was unsure of per original solution doc.

**Comment by bischoffa** [comment]
Added Health to it given Ameet removed global but didn't add a team back in. Assuming Ameet thinks this should be Health of the Flagship team

**Comment by bischoffa** [comment]
Been working with Janie Tankard-Carnock to get applicable test accounts to validate VA MHV's Solution 2. Worked with Dimitar Tzvetanov.  Jayson from Mobile was involved originally but work expected to shift to new team structure and likely fall into QA's hands of that team.

Originally thought it was a global issue given login, given Ameet removed it I am assuming its Health which has not been tagged.  Slack post to @Hallm13 @ala-yna on how they want to move forward.

**Comment by bischoffa** [comment]
Test accounts: 

asfourteen1/Tester1&

astestnine1/Tester1&

![](https://github.com/department-of-veterans-affairs/va-mobile-app/assets/116006847/2e2c0e84-c02c-4124-a006-570c0c97af87)

**Comment by bischoffa** [comment]
Rachel has shared anticipation that RX may be having the same issue as SM. [Based on initial research ](https://dsva.slack.com/archives/C018V2JCWRJ/p1696430066112269) only SM was impacted but given some feedback and comments back in Dec 2023 there is some VA thought that its now included. 

https://dsva.slack.com/archives/C018V2JCWRJ/p1704821315749209

**Comment by bischoffa** [comment]
I picked this up from Health given H*B do not have the bandwidth to pick it up now. I am pulling in Therese to do testing work for a couple days this week. 

Plan: 
- Pulling in Therese to perform testing between 1/24 - 1/26 to see if MHV's proposed but not validated solution works 
- Note Mobile has not logged into MHV in staging has historically we were told all 3 login methods should be the same and MHV was very difficult to get through (above thread used for mHV login conversations) 
- Results of the findings will be revisited early next week on how to proceed 
  - Expect that Flagship team will need to manage engineering resources will be needed to modify or complete changes

**Comment by bischoffa** [comment]
Update from Jan 25th [Slack Thread](https://dsva.slack.com/archives/C018V2JCWRJ/p1706195087269779) with more conversation between Jayson and Patrick Bateman 

Mobile QA has been attempting to test MHV proposed solution to see if it will work the last couple days.  Hope was we can do some simple testing to validate the solution.
Unfortunately that has been a more challenging endeavor than expected. It wasn't as simple as login and validate. Based on time spent testing the last couple days there was some findings that need to be worked out before proceeding to test MHV's possible solution which are going to take more time and dedicated resources to work through.  Because of this I am working with Matt to see how to best proceed.

Rationale:

- Testing has found a few [findings](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/7650) that need more time and focus on to validate or debunk
- Possible that some base assumptions on the issue may be incorrect
- Testing has been difficult as Mobile as historically told to use anyway to login as all methods should be equal so experience and familiarity and knowledge of MHV staging login is low
- Currently facing challenges on how to remote into VA network on a test device
- Sporadic login issues with test accounts provided - not sure if its a system limitation thing or something else

**Comment by bischoffa** [comment]
Sent Matt and Alayna updates on 1/25 with the intent of its being transitioned from Platform QA and Release Team to Health - [Ad Hoc PM Only Channel ](https://adhoc.slack.com/archives/C05S1S1MQ3G/p1706194776875809?thread_ts=1706194400.131179&cid=C05S1S1MQ3G)

**Comment by bischoffa** [comment]
Work needs to transition to a Flagship Team to manage based on Mobile's new structure as Platform QA and Release is not built to handle this project. Also needs to be prioritized against all other projects vs worked between them.  Additionally I am going out on leave soon and won't be able to manage it so it needs to move PMs. 

Shared recommendations with Matt on how to handle. Flagship Teams deemed not feasible as there current work would not be deprioritized for this. Matt said on 1/31 he would reach out to Stacy to discuss if Backend Team could handle it.

**Comment by bischoffa** [comment]
Less than 1% ~ 9000 Veterans impacted a month

**Comment by StacyB2023** [comment]
**3/15/24** BE team @jperk51 is following this issue. Next steps with  this issue is with the MHV team:  patricks working the BL team to pull the MHV SM API logs and analyze. 

Related Thread for History: https://dsva.slack.com/archives/C018V2JCWRJ/p1706195087269779

Primary ownership **is not** BE team. Ownership will be will MHV but BE team will be following this issue closely.

**Comment by jperk51** [comment]
For secure messaging we already put in a fix that seems to have solved the issue but for RX there's no easy solution so we are blocked until the MHV provides an endpoint which can tell us if a user should have RX access or not. 

RX Thread: https://dsva.slack.com/archives/C04PRFEJQTY/p1712850076921339

**Comment by ala-yna** [comment]
Moving this over to `Later` since there's no further work we can do at this point.

**Comment by BeccaTupaj** [comment]
Closing this bug due to MHV login sunset on 3/4/2025
