### ISSUE TITLE
Travel claims: Content - stakeholder review and feedback

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6893]
## Description 
As a Veteran, I want to be able to submit and track travel reimbursement claim(s) for eligible past appointments using the VA: Health & Benefits mobile app.

As part of this story we want to:   

- Present latest content/designs to stakeholders and gather feedback for future implementation

## Tasks
- [x] Prepare any final changes to content before stakeholder review
- [x] Attend stakeholder review (Demo and other reviews) and present designs in collaboration with designer
- [x] Gather and document feedback

## Acceptance Criteria
  

-  [x] Documented feedback from stakeholder review in this ticket

## Scope

- Only feedback will be gathered; feedback won't be implemented until later sprint.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Feedback from 10/11 demo specific to Content

1. On the question of needing a possible agreement notice/checkbox, Mark Dewey will ask business stakeholders if this is needed and if so what parts are legally required to include in the wording. Ryan Thurlwell also mentioned possibility of a checkbox and short "You agree to terms and conditions blah blah" and that T&C could link to somewhere else. All this is still TBD but first order of business is for stakeholders to determine if it is actually needed in our experience.
2. Question from Dylan N (Eng) on where snackbars would occur upon API success/fail. Will work with Lauren on that.
3. How to approach contextual info on claim status on Details screen. Adam and I agreed to go with a short (1-2 sentence) description of a status to give user more context but not the full description BTSSS uses now as some of them are quite long. I will rewrite just one status definition (probably Denied) to show stakeholders in further reviews. But full rewriting of all definitions will occur in later sprint when I have more capacity (likely sprint 84).

Something else that was noted by Lauren after the demo was need for cancel confirm messages. I reviewed all our current messages like this to see if we could reuse something similar. Posted my copy suggestion in the Figma designs for these action sheets.

Next up: More stakeholder reviews...
