### ISSUE TITLE
RX: Content - stakeholder review and feedback

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6908]
## Description 

As part of this story, I will:   

- Present latest content/designs to stakeholders for filter/sort options in Prescriptions

## Tasks
- [ ] Attend stakeholder review and present designs in collaboration with designer
- [ ] Gather and implement feedback
- [ ] Meet with Laura W for input on new copy

## Acceptance Criteria
  

-  [ ] Final copy in Figma

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Updating this ticket to 2 points as it became clear after meeting with POs that I needed to implement feedback and make more changes to content. Points now account for work I wasn't planning on.

FYI: @jennb33 @MekoHong
