### ISSUE TITLE
Appointments: Phone appt updates to content

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6910]
## Description 
As a Veteran checking all my phone appointments (upcoming, past, canceled) in the mobile app, I want to get only the most important information depending on the type of appointment I'm reviewing, so that I'm prepared for my appointment or I know what next steps I need to (or don't need to) take related to these appointments.

As part of this story, we want to:   

- Use our finding from the content audit from Q3 2023 to update all phone appointments in the mobile app.

## Tasks

- [x] Get screenshots of our pending/pending canceled for phone appointments
- [x] Input information into Meko's [use case spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=0)
- [x] Sync with UX designer to align on [Figma designs](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=731-2493&mode=design&t=FPsC5JqzSRVET4fO-0)
- [x] Review screens created by UX designer
- [x] Edit copy on screens as needed
- [x] Share final designs with PM for hand-off to Eng

## Acceptance Criteria
  

**1. Updated screens/content for UPCOMING phone appointment - LIST VIEW**

- [x] Change appointment modality from "Phone call" to "Phone"
- [x] Add `type of care` with `provider`, when available
- [x] Content/UI is accounted for when type of care and provider is unavailable

**2. Updated screens/content for UPCOMING phone appointment - DETAILS VIEW**

- [X] First header/field should read "Phone appointment", not "VA appointment"
- [x] Add instructions for how to "attend" the appointment
- [x] Add type of care, when available
- [x] Add provider name, when available
- [x] Remove facility address
- [x] Remove directions link
- [x] Add details about why appt was scheduled (reason for visit)

**3. Updated screens/content for PAST (CONFIRMED) phone appointment - LIST VIEW**

- [X] Change appointment modality from "Phone call" to "Phone"
- [x] Add `type of care` with `provider`, when available
- [x] Content/UI is accounted for when type of care and provider is unavailable

**4. Updated screens/content for PAST (CONFIRMED) phone appointment - DETAILS VIEW**

- [X] Add banner about past appointment and reads "This appointment happened in the past"
- [X] First header/field should read "Phone appointment", not "VA appointment"
- [x] Do not include how to attend appointment
- [x] Add type of care, when available
- [x] Add provider name, when available
- [x] Do not include any facility information
- [x] Remove directions link
- [X] Update copy for content block that tells user how to scheduling another appointment

**5. Updated screens/content for CANCELLED (CONFIRMED) phone appointment - LIST VIEW**

- [X] Change appointment modality from "Phone call" to "Phone"
- [x] Add `type of care` with `provider`, when available
- [x] Content/UI is accounted for when type of care and provider is unavailable

**6. Updated screens/content for CANCELLED (CONFIRMED) phone appointment - DETAILS VIEW**

- [X] Banner for canceled appointments reads "[Canceler] canceled this appointment"
- [X] First header/field should read "Phone appointment", not "VA appointment"
- [x] Remove "Canceled appointment for" from before the date
- [x] Do not include how to attend appointment
- [x] Add type of care, when available
- [x] Add provider name, when available
- [x] Do not include any facility information
- [x] Remove directions link
- [X] Update copy for content block that tells user how to reschedule appointment

## Important resources
- [Web's content matrix for upcoming/past/canceled phone appointments - DETAILS](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1710-94269&mode=design&t=esCV9k7EOHftI156-4)
- [Web's content matrix for pending phone appointments - DETAILS](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=2102-17112&mode=design&t=esCV9k7EOHftI156-4)
- [Our audit of phone appointments - DETAILS](https://www.figma.com/file/k0Ny9KoP1prsI7o661Tyf3/%F0%9F%94%8D-Appointments-Content-Inventory-2.0---Working---VAMobile?type=whiteboard&node-id=149-1075&t=3vzfYqa8uP0i0yLU-4)
- [Out audit of LIST view](https://www.figma.com/file/k0Ny9KoP1prsI7o661Tyf3/%F0%9F%94%8D-Appointments-Content-Inventory-2.0---Working---VAMobile?type=whiteboard&node-id=102-1869&t=3vzfYqa8uP0i0yLU-4)

## Out of scope
We will not be doing an overhaul or total redesign of these appointments to align with the Web Appointments team. The purpose of the audit and implementing its findings is to make small updates to copy and to add or remove fields to better align with web.
We will also not focus on pending phone appointments.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Final content from use case spreadsheet as PDFs
[Phone appointment details updates as of 10-24-24.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHBqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--91a08b365702eb0aa47d419787915a320d253647/Phone%20appointment%20details%20updates%20as%20of%2010-24-24.pdf)
[Phone appointment list view updates as of 10-24-24.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36d02b06d6df5a2afc921c57a8b8dfde488d78f5/Phone%20appointment%20list%20view%20updates%20as%20of%2010-24-24.pdf)

**Comment by mistymg** [comment]
Follow up to this ticket: Lauren and I chose to use this opportunity to make a few further adjustments. Therefore, what we did in the ACs of this ticket has changed a bit. For most recent updates, see [Figma designs](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=731-2493&mode=design&t=cQQI8UJSbn8neQ09-0) and [Phone appointment details view updates as of 10-26-24.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelIxQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12f293e6fa8ae6c47e12ac192d1613b4f599b189/Phone%20appointment%20details%20view%20updates%20as%20of%2010-26-24.pdf)
