### ISSUE TITLE
Personalization: Content support for design phase (part 1)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6916]
## Description 
As a Veteran using the VA: Health and Benefits mobile app, I want to get personalized information as soon as I open the app (on the home screen), so that I can manage my information and complete tasks that are most relevant to me without needing to "drill down" further into the app to find this information or complete these tasks.

As part of this story, I will:   

- Get up to speed on what's happened with Personalization project so far

Note: I'll take a more supportive role for this project and let the UX designer take the first couple stabs at content before my final sign off.

## Tasks

- [x] Meeting with UX designer and PM to review wires

## Acceptance Criteria
  

NO DELIVERABLES NEEDED

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Notes from meeting with Ameet and Holly 10/18:
[Approved recommendation as of today](https://balsamiq.cloud/s4uw4la/pnnwuqv/r47B3)

**Comment by mistymg** [comment]
Per Slack thread on 10/19, no content needs for next sprint (83). Hi-fi designer still needs to be determined and Holly/Ameet still working out MVP. Removed my 3 points for sprint 83 for this project. Ameet is aware that the pushing back of needing my support means PMs may need to negotiate on what I focus on in later sprints if I'm at capacity.
