### ISSUE TITLE
Support for Veteran Status Web and Mobile team

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#6929]
# Project Status Overview

### Project Objective:

- Purpose is for Flagship Mobile to provide support to the newly established Digital ID team that will be working on both web and mobile. 

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
|  |   |
|  |   |
|  |   |

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

|Step | Timing | 
|-------| ---------| 
| Kickoff | ~ October    |
| Knowledge Transition | ~November  |
| Digital ID Team Takes over   |  ~November |

</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Oct '23| Green | 10/6 Initial kickoff meeting and discussions. Digital ID team working on a transition plan | Team not fully set up as people are still being hired or start dates are a few week away | 
</details>

# Detailed Project Scope 

### Problem Statement

- A new contract was awarded to Ad Hoc who is sitting up a new team responsible for Veteran Status both on web and mobile as of 10/5 (originally it was just web but scope has changed) 
- Flagship App Mobile Team that worked on Veteran Status to support Digital ID team as needed 

### Assumptions 
 - Digital ID team will eventually take over all of Veteran Status
 - Digital ID team will make changes to Mobile's Veteran Status as needed ; work will not be done by Mobile but Mobile may support

### Risks 
- Contract scope changed from just web to also including Mobile
     - Thus scope change post hire
     - A single team managing mobile / web has not been done before - viewed as an experiment from both Ad Hoc and VA 

### Definition of Done 
<details>
<summary>Following needs to be true</summary>

Digital ID team to take over Veteran Status from Mobile, then Mobile will close this epic. Future work and needed from Mobile to be separate epics that will be added as needed and when the work is prioritized. 

|Item | Completed | 
|-------| ---------|
| Identify discipline pairing between Mobile and Digital ID | Completed | 
| Discipline pairings to meet and discuss | Pairing identified, they are to schedule meetings as needed |
| Flagship App transitions knowledge, documents and information to Digital ID Team | In Progress |
| Digital ID team takes over the project | Not Started | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>
- Links related to Veteran Status can be found in Veteran Status epic [4270](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/4270)
- [Transition doc](https://docs.google.com/document/d/11s0_xZRYDR0kqb4wKoDl5BW5LU_1MZXz75p7uLWeW_o/edit#heading=h.o1b49rfssykx) 
</details>

### Team Members

<details>
<summary>Contact List</summary>

Flagship App
- **OCTO Product Leads:** Rachel Han and Ryan Thurlwell
- **Ad Hoc PM:** Meko Hong
- **Engineering:** Tim Wright
- **Designer & Research:** Brea Blackwelder

Digital ID Team 
- **OCTO Product Leads:** Rachel Han and Ryan Thurlwell
- **Ad Hoc PM:** Matt Reilly
- **Engineering:** Liz Townsend
- **Design:** In process of hiring
- **Researcher** - Cara Frissell

</details>

### Change / Decision Log - not applicable for this support epic; will be managed by Digital ID team 

# Checklist 

<details>
  <summary>Toggle Product Checklist</summary>

- [ ] Add Digital ID team to Ad Hoc's Va-mobile-veteran-status-id Slack channel
- [ ] Provided Digital ID team with documentation for Veteran Status
    - [ ]  PO Product Brief
    - [ ]  Epic
    - [ ]  Sprint 0 
    - [ ]  Product Canvas
    - [ ]  Figma
    - [ ]  Research 
- [ ] Identify and Meet with our discipline pairings 
    - [ ] Product - Adam Kasmier and Matt Reilly 
    - [ ] Design - Brea Blackwelder & new hirer to be named later
    - [ ] Research - Brea Blackwelder & Cara Frissell
    - [ ] Engineering - Liz Townsend & Tim Wright 
- [ ] Discussions on how Mobile has worked with VA
    - [ ] Sprint Planning  - Product
    - [ ] Ticket Management  - Product
    - [ ] Mobile SoS Board   - Product
    - [ ] Demo  - Product
    - [ ] Retro  - Product
    - [ ] App Store Release - Engineering
    - [ ] Feature Flag / Waygate - Engineering
    - [ ] Research proposal and approvals - Design
    - [ ] Call Center Guide - Product
    - [ ] App Store Update - Product 
    - [ ] UAT - Product
    - [ ] Content Approval - Design
    - [ ] Testing / QA - Product
- [ ] Attend Digital ID ceremonies for transition

**Comment by bischoffa** [comment]
Confirmed by POs on 10/10 not to reference Digital ID, instead call it Veteran Status. Updated naming convention cause of that.
