### ISSUE TITLE
Travel claims: Rewrite status definitions

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#6984]
## Description 
As a Veteran viewing my travel claim status on a past appointment details screen, I want to read additional context about the status of my claim, so that I understand where my claim is in the process and if there's anything else I need to/can do.

As part of this story we want to:   

- Rewrite status definitions are travel claims to shorter versions

## Tasks

- [ ] Determine which statuses will definitely be shown in the app
- [ ] Create a spreadsheet/comparison of all possible definitions (see resources below)
- [ ] Rewrite/edit definitions to 1 or 2 sentences
- [ ] Meet with Sitewide Content for approval

## Acceptance Criteria
  

-  [ ] Rewritten status definitions for all applicable statues definitions that will appear in the app
-  [ ] New status definitions clearly communicate any important information about the status as well as if there is any action the Veteran needs to take

## Open questions
- [ ] Which statuses are going to show up in the app?

## Resources

**PDF of "plain language" status definitions from BTSSS**

[What does my status claim mean?.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0V0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1deb95add496b480644972b03611b9cbb16c08c1/What%20does%20my%20status%20claim%20mean%3F.pdf)

**2 places where BTSSS user guide mentions statuses/definitions**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDR0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--910390e9908b219d6f9c7bf237ea379b885ce067/Statuses%20and%20definitions%20from%20BTSSS%20user%20guide%20%28place%201%29.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDh0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac659e910c2f7a77973b3dca3765468d8d0ddffb/Statuses%20and%20definitions%20from%20BTSSS%20user%20guide%20%28place%202%29.png)

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
From call with OCTO stakeholders and Travel Pay team on 4/18, we got this list of statuses/definitions as "final and the only ones shown to Veterans."

Still open questions: Which ones will actually show in the app?

Told Kay I'd like to rewrite these for plain language in collab with CAIA.

<img width="1082" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGwvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51379273847691e31918bdf0c1bca23b12b07c34/image%20%285%29.png" alt="image (5).png" />

**Comment by mistymg** [comment]
Screenshot from meeting chat:

**Comment by mistymg** [comment]
Per Matt Hall/Rachel Han, Travel is being pulled out of our roadmap right now until BTSSS and UAE are further along and we reprioritize.

**Comment by mistymg** [comment]
Determining if this ticket is still necessary as we pick travel pay work back up. New statuses/definitions may not be part of MVP.

**Comment by ala-yna** [comment]
@mistymg, let me know if we can go ahead and close this ticket!

**Comment by mistymg** [comment]
@ala-yna Per my comment in this ticket last week, I'm still determining that. I'll close it out once I know for sure.

**Comment by mistymg** [comment]
Closing this as web Travel team is working with CAIA to rewrite statuses/definitions. That work won't be ready for our MVP version though.
