### ISSUE TITLE
Copy of Personalized Home Screen: High level concept refinement - Wireframes

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#7038]
## Description 
Document high level approach for personalized home screen recommendation.

## Tasks
Create wireframes for recommended for home screen approach (based on outcome of [Personalized home screen: High level UI concept creation & audit #6594](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/6594), preliminary ENG feasibility review, and PO feedback):

- [x] Wireframe recommended high-level approach for home screen UI architecture (selected from audit finalists & based on collaboration with ENG & PM) and flesh out additional high level states (How direction behaves in various situations (loading, no data, health only, claims only, etc))
  - [x] Share recommendation with POs
- [x] Iterate on high-level concept recommendation based on PO feedback 
  - [x] Feasibility review & input from ENG, PM 
  - [x] Share recommendation with POs

## Acceptance Criteria
  

-  [x] Initial wireframes for recommended home screen direction
    -  [x] High level concept MVP recommendation

## Notes & Open Questions
- [VA Mobile App - Personalization - UX - Home screen work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/design-personalization/ux#personalization---home-screen)
- [Success Criteria for Evaluating Personalized Home Screen Approaches](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/ux/home-screen-success-criteria.md#success-criteria-for-evaluating-personalized-home-screen-approaches)
- [VA Mobile App - Personalized Home Screen - Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/product/Personalized_homescreen-Product-Brief-2023.md)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x]  Linked to an Epic

**Comment by htcollier** [comment]
Reviewed [proposed MVP approach](https://balsamiq.cloud/s4uw4la/pnnwuqv/rEDDF) with ENG on 10/20—no modifications needed.

**Comment by ajsarkar28** [comment]
Carrying over to sprint 83 since final MVP has not been selected by PO

**Comment by htcollier** [comment]
Shared rec & got a greenlight on the MVP scope approach on 10/31. [Meeting notes](https://docs.google.com/document/d/1ucqnrsa-7PzmHKfk5XqcC_SMhV2Mbxvthjc0rL-wcZs/edit#heading=h.krcdrl2rnaan)
