### ISSUE TITLE
Appointments: VA in-person appt updates to content

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7102]
## Description 
As a Veteran checking all my VA in-person appointments (upcoming, past, canceled) in the mobile app, I want to get only the most important information depending on the type of appointment I'm reviewing, so that I'm prepared for my appointment or I know what next steps I need to (or don't need to) take related to these appointments.

As part of this story, we want to:

- Use our findings from the content audit from Q3 2023 to update all VA in-person appointments in the mobile app.

## Tasks
- [x] Input information into [use case spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=0)
- [x] Sync with UX designer to align on [Figma designs](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=731-2493&mode=design&t=FPsC5JqzSRVET4fO-0)
- [x] Review screens created by UX designer
- [x] Edit copy on screens as needed
- [x] Share final designs with PM for hand-off to Eng

## Acceptance Criteria
  

**1. VA IN-PERSON - LIST VIEW**
- [x] Modality field now reads: [building icon] At [facility name]
- [x] Type of care field included
- [x] Provider name included
- [x] Empty states for type of care, provider name, and facility name accounted for

**2. VA IN-PERSON - UPCOMING - DETAILS VIEW**
- [x] "VA appointment" heading now reads: "In-person appointment"
- [x] How to attend appointment "Go to [facility name] for this appointment." is included below heading
- [x] Type of care field included
- [x] Provider name included
- [x] Empty states for type of care and provider name accounted for
- [x] "Details you shared with your provider", [Reason] field, and [Booking note] included
- [x] Canceling/rescheduling content block updated for when an appointment can and can't be canceled in app

**3. VA IN-PERSON - PAST - DETAILS VIEW**
- [x] "VA appointment" heading now reads: "Past in-person appointment"
- [x] How to attend appointment is "This appointment happened in the past."
- [x] Type of care field included
- [x] Provider name included
- [x] Empty states for type of care and provider name accounted for
- [x] "Details you shared with your provider", [Reason] field, and [Booking note] included
- [x] Exclude add-to-calendar and get-directions links for past appt.
- [x] Scheduling another appt content block updated

**4. VA IN-PERSON - CANCELED - DETAILS VIEW**
- [x] "VA appointment" heading now reads: "Canceled in-person appointment."
- [x] How to attend appointment is "[Canceler] canceled this appointment."
- [x] Remove "Canceled appointment for" from before the date
- [x] Type of care field included
- [x] Provider name included
- [x] Empty states for type of care and provider name accounted for
- [x] "Details you shared with your provider", [Reason] field, and [Booking note] included
- [x] Exclude add-to-calendar and get-directions links for canceled appts.
- [x] Rescheduling content block updated

## Resources
[Our audit of VA in-person](https://www.figma.com/file/k0Ny9KoP1prsI7o661Tyf3/%F0%9F%94%8D-Appointments-Content-Inventory-2.0---Working---VAMobile?type=whiteboard&node-id=143-1011&t=VkA88R2lGXXszrhH-4) (3 yellow sections)
[Web's detail designs](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1212-35309&mode=design&t=Nqhb633oppaAIO50-0)
[Web's content matrix for in-person appts](https://www.figma.com/file/RcDljBwThbwVDkNrDH2xiA/Appointment-Details-Redesign?type=design&node-id=1710-94259&mode=design&t=QNHqPNRZr30v9m9U-4)

## Open questions
- How do we handle unknown facility name and address info currently?
Accounted for this in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=0) and also see convo with FE engineer in [Slack thread](https://adhoc.slack.com/archives/C0212B872MT/p1698333646855129) on nuances of this.

## Out of scope
We will not be doing an overhaul or total redesign of these appointments to align with the Web Appointments team. The purpose of the audit and implementing its findings is to make small updates to copy and to add or remove fields to better align with web.
We will also not focus on pending appointments.
We will only focus on VA in-person appointments for this ticket and complete in-person CC appointments as part of future work.
We will not do claim exam appointments as part of this ticket. Content is not finalized on web for these.

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Met with Lauren today to align on Appts stuff

**Comment by mistymg** [comment]
PDFs of spreadsheet for VA access
