### ISSUE TITLE
Push Notifications: UX Discovery - push notification approaches

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7113]
## Description
Explore push notification approaches in other mobile apps (including but not limited to those with similar feature sets and/or data needs).

## Tasks
- [x]  Conduct exploratory research on push notifications and document:
   - [x]  Push notification content & structure: 
       - [x]  High-level categories of message content apps send
       - [x]  How push notification message content is structured
   - [x] Push notification app functionality:
       - [x]  how users manage which notifications they receive (and where that lives in the app)
       - [x]  whether a historical notifications list is kept within the app (and where that lives in the app, if applicable)
- [x]  Summarize findings
- [x]  Present desk research findings to team (PM)

## Acceptance Criteria
- [x] Findings report created & posted to Github

## Notes & Open Questions
[Push Notification Strategy - Sprint 0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/Push%20Notification%20Strategy%20-%20Sprint%200.md)

## Ticket Checklist
- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by htcollier** [comment]
[WIP: VA Mobile App - Comparative Analysis: Push Notifications](https://docs.google.com/document/d/10vncvfgJxaVUG2d9JYUfOvz-_NSXwwpl5wSDC0iklrw/edit)

**Comment by htcollier** [comment]
Findings uploaded to github: [VA Mobile App - Comparative Analysis: Push Notifications](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-comparative-analysis-2023.md)
