### ISSUE TITLE
Push Notifications: UX Strategy

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7114]
## Description
Document UX strategy for implementing push notifications in the VA mobile app.

## Tasks
- [x]  Document UX strategy for implementing a push notification strategy that outlines Business + User Assumptions, the problem being solved, and our hypothesis.
- [x]  Revise based on PM collab, Greta & Liz feedback
- [x]  Post to Github

## Acceptance Criteria
- [x] UX strategy created & posted to Github

## Notes & Open Questions
[Push Notification Strategy - Sprint 0](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/Push%20Notification%20Strategy%20-%20Sprint%200.md)

## Ticket Checklist
- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by htcollier** [comment]
First pass complete: [WIP Design Strategy Worksheet: VA Mobile App - Push notifications ](https://docs.google.com/document/d/1uCZLfew4tnqn8Zy2RUski6ldtTjYaH9T/edit#heading=h.gjdgxs)

**Comment by htcollier** [comment]
Feedback from @ajsarkar28 & @lstraghalis folded in, updated doc posted to github: [VA Mobile app: Push Notifications Design Strategy Worksheet
](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/Push%20Notifications/ux#va-mobile-app---push-notifications---ux)

**Comment by htcollier** [comment]
Finished drafting, gathered feedback & posted to github: [VA Mobile app: Push Notifications Design Strategy Worksheet
](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/ux/push-notifications-design-strategy-worksheet.md)
