### ISSUE TITLE
Personalization: Spike for content work

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7115]
## Description 
As a Veteran using the VA: Health and Benefits mobile app, I want to get personalized information as soon as I open the app (on the home screen), so that I can manage my information and complete tasks that are most relevant to me without needing to "drill down" further into the app to find this information.

As part of this story we want to:   

- Complete a spike on possible options for content needs for this project.

## Tasks

- [x] Check out Mobbin for content ideas
- [x] Chat with Danielle and/or Laura to get their ideas/feedback
- [x] Get resources for web's use of loading/empty/error

## Acceptance Criteria
  

No deliverables as part of this ticket

## Notes & Open Questions

- MVP still TBD

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Met with Lauren to chat her part of the work and her explorations
