### ISSUE TITLE
Personalized Home Screen: Visual Design discovery & typography exploration

### ISSUE THREAD

**Issue by ajsarkar28** [department-of-veterans-affairs/va-mobile-app#7116]
## Description
Collect inspiration for visual design approaches for Personalized Home Screen and explore typography approaches.

## Tasks
**Collect inspiration for visual design approach**
- [x] Using a visual design lens, review existing [VA Mobile Comparative Analysis: Personalized & contextual Home screen content](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/discovery/research/personalization-comparative-analysis-2023.md#va-mobile-comparative-analysis-personalized--contextual-home-screen-content) work: [Mural with personalized home screen screenshots](https://app.mural.co/t/adhoccorporateworkspace2583/m/adhoccorporateworkspace2583/1645116475554/b9c0cc05f453a16c5a4a2f444fbbdd544693d892?sender=u98217f9fb71c48553bdb7841)
- [x] Collect examples from additional apps' home screens' designs and document visual design ideas that could be applied to the Personalized Home Screen
- [x] Explore typography approaches based on collected inspiration

## Acceptance Criteria
  
- [x] Visual design discovery board created
- [x] Typography exploration artifact created

## Notes & Open Questions
-  [Personalization: Home = Interaction snapshot (long term vision) wireframes](https://balsamiq.cloud/s4uw4la/pnnwuqv/r47B3)
- [VA Mobile App - Personalization - UX - Home screen work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/design-personalization/ux#personalization---home-screen)
- [VA Mobile App - Personalized Home Screen - Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/product/Personalized_homescreen-Product-Brief-2023.md)

## Ticket Checklist

- [ ] Acceptance criteria defined
- [ ] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic
