### ISSUE TITLE
Personalized Home Screen: Visual Design - initial design explorations

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#7118]
## Description
Explore initial high-level visual design approaches for Personalized Home Screen.

## Tasks
- [x] Create high fidelity mocks exploring various visual design approaches for the Personalized Home Screen (using the high level wires as a guide)—include key screens & states from the wireframes to accurately represent the approach. Use [long term vision wireframes](https://balsamiq.cloud/s4uw4la/pnnwuqv/r47B3) as a starting point, with room to explore enhancements.
    - [x] Home screen (most content, no content, loading state)
    - [x] A category screen (most content, no content, loading state)
    - [x] Other screens or states as needed
- [x] Narrow options to a recommended approach
- [x] Share with PO for feedback

## Acceptance Criteria
  
- [x] High level high fidelity mocks using key screens to represent approach created in Figma
- [x] [Recommended approach identified](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2176-1167&mode=design)

## Notes & Open Questions
- [Personalization: Home = Interaction snapshot (long term vision) wireframes](https://balsamiq.cloud/s4uw4la/pnnwuqv/r47B3)
- [VA Mobile App - Personalization - UX - Home screen work](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/features/design-personalization/ux#personalization---home-screen)
- [VA Mobile App - Personalized Home Screen - Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/design-personalization/product/Personalized_homescreen-Product-Brief-2023.md)

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by wavelaurenrussell** [comment]
Added link to recommended approach - [V4 finalist](https://www.figma.com/file/q4oTyzyLfYrZVz4CACzVLA/Personalization-Visual-Design---Working---VA-Mobile?type=design&node-id=2176-1167&mode=design)
