### ISSUE TITLE
Appointments: Support Product with Eng tickets for in-person

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7209]
## Description 
I will help Product with writing/handing off Eng tickets for the changes we're making to VA in-person appointments.

## Tasks

- [x] Meet with Adam to support ticket writing
- [x] Review tickets created by Adam to ensure copy is reflected accurately

## Acceptance Criteria
  

-  [x] Implementation tickets ready to hand off to Eng (in collaboration with Product)
-  [x] Answers to any question from Engineering

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
