### ISSUE TITLE
App Headings: Content support for Step 1

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7210]
## Description 
Currently, the app doesn't implement headings consistently or in a helpful way, thereby making it hard for users to quickly understand what information they can find on a given screen.

As part of this story we want to:   

- Provide content strategy and support to Step 1 of this project.

## Tasks

- [ ] Attend any kickoff meetings with Product, UX, Eng, and QA
- [ ] Provide input on scope and/or how to break out work

## Acceptance Criteria
  

No actual deliverables

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Closing ticket as I was not needed for Step 1 of this project
