### ISSUE TITLE
Appointments: Support CAIA & Web team with empty state copy alignment

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7286]
## Description 
Collabing with web teams to align on empty state copy in appointments.

## Tasks

- [x] Meet with Laura W and Ciera M on empty states copy
- [x] Connect with Ben on CEI team about testing "not noted"
- [x] Share our null facility name/address/phone copy with Ciera

## Acceptance Criteria
  

No actual deliverables

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
[Slack thread](https://dsva.slack.com/archives/C05Q9HH47PS/p1700059222367639?thread_ts=1700000742.969019&cid=C05Q9HH47PS) asking CIE team to test empty state copy for type of care field.
