### ISSUE TITLE
Appt List & Details content alignment - Online / Video

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7315]
# Project Status Overview

### Project Objective:

During the Appointments V2 integration, we noticed some inconsistencies on how we (mobile) display or do not display information on the appointment list/detail views. Some highlights, to name a few
- Inconsistencies when displaying info such as type of care, reason for care,
- What info is avail for CC vs VA appts etc
- Missing info/instructions for video appts

This epic only focuses on Online / Video. Phone and In Person done in epic [5136](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/5136)
 
**Veteran Pain Points**

1. Missing and confusing appointment information makes the list difficult for Veterans to prepare for their appointments
2. In past research studies, Veterans expressed that missing and or inconsistent appointment details such as type of care, clinic name, physical location, and provider information make it difficult for them to understand their appointments.

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Project not yet prioritized  |  Mobile POs  | will revisit in Q1 2024 quarterly planning |
|  |   |
|  |   |

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

|Step | Timing | 
|-------| ---------| 
| Project prioritized | TBD | 
| Step 1 -  Video - strategize / research | Health | Not yet prioritized |
| Step 2 - Video - define recommendations and draft tickets | Health | Not yet prioritized  |
| Step 3 - Video - implement changes | Health | Not yet prioritized  |

</details>

### Monthly Update 
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Nov'23| None | Created a separate epic for Video and identified some tech debt / code upkeep will be required when doing video based on findings from Phone and In Person | Project is not prioritized |
</details>

# Detailed Project Scope 

### Definition of Done 
<details>
<summary>Following needs to be true</summary>

|Item | Completed | 
|-------| ---------|
| | | 
| | | 

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| | | 
| | | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>

- [Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/appointments/product/AppointmentListEnhancements/AppointmentListEnhancement_ProductBrief.md)
- [Decsion Log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/appointments/product/AppointmentListEnhancements/decisionlog.md)
- [Figma Mapping](https://www.figma.com/file/k0Ny9KoP1prsI7o661Tyf3/%F0%9F%94%8D-Appointments-Content-Inventory-2.0---Working---VAMobile?type=whiteboard&node-id=0-1&t=OtdNGFckhpKwZsKm-0)
</details>

### Team Members

<details>
<summary>Contact List</summary>

| Name | Role |
| :--------- | :--------|
| Rachel Han | Product Owner, VA |
|Ryan Thurlwell | Design Lead, VA |
|  | Sr. Product Manager, Ad Hoc|
| | Sr. Content Designer, Ad Hoc|
| | Sr. UX Designer, Ad Hoc|

</details>

### OKR and Analytic Metrics 
<details>
<summary>Metrics</summary>

No new metrics being added, will  be assessing existing metrics

</details>

### Questions 
<details>
<summary>Open Questions</summary>

</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer |
|--------|----------|
| | |
| | |

</details>

### Change / Decision Log 

Product will need to create on in the Github folder and link it here. 

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] Project Kickoff session
   - [ ] Initiative Scope finalized
   - [ ] Link Product Brief - [Sprint 0 ](https://docs.google.com/document/d/1WHDJ1iCt9J-acLx8_DSL4tkRKoVYqJGaRUqXuFf7ceg/edit# )
   - [ ] Link to Implementation Strategy
       - Implementation Plan
       - UAT Plan
       - Release Plan
       - Metrics Identified (what metrics are we capturing, how do they tie into stakeholder OKRs, etc)

**Pre-Production Readiness**
- [ ] Associate Readiness
  - [ ] Update product guide
  - [ ] Coordinate with contact center support teams
- [ ] What’s New Content
- [ ] App Store/In App messaging (if applicable)
- [ ] Coordinate with Release coordinator
- [ ] App store Content changes required? Y/N
- [ ] App store images needed? Y/N
- [ ] QA Signed off 
- [ ] UAT complete
- [ ] Obtain Go/No Go decision

**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [X] Research needed? No
- [ ] UAT Needed? Yes/No
- [ ] Ticket creation 
- [ ] Demo feature (mid check, end of development)
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>

- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received
- [ ] Complete Design QA
- [ ] Does it require component review?
- [ ] Accessibility review needed?

</details>

<details>
  <summary>Toggle Content Checklist</summary>

- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores 

</details>

<details>
  <summary>Toggle Engineering Checklist</summary>

- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?
- [ ] Do we need to update our in-app review code to include this new feature?

</details>

<details>
  <summary>Toggle QA Checklist</summary>

- [ ] Create test plan
  -  **Template: QA Test Plan**
- [ ] Identify test data needs
- [ ] Gotten & incorporated test plan review
- [ ] QA Complete
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail
- [ ] Added feature cases to appropriate section of active cases in TestRail
- [ ] Spun up a (future) UI automation ticket for new feature
</details>

**Comment by bischoffa** [comment]
duplicate go to 7313
