### ISSUE TITLE
Personalization: Content support for design phase (part 2)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7327]
## Description 
As a Veteran using the VA: Health and Benefits mobile app, I want to get personalized information as soon as I open the app (on the home screen), so that I can manage my information and complete tasks that are most relevant to me without needing to "drill down" further into the app to find this information or complete these tasks.

As part of this story, I will:   

- Provide content support to the next part of the design phase.

## Tasks

- [x] Meetings with UX designer, PM, and/or POs
- [x] Start on [copy deck](https://docs.google.com/spreadsheets/d/1BBSwn0EBnsDy-dfPXVK507wt_wcc_i3bXkcnEcFv2pM/edit#gid=0) to keep all copy variables

## Acceptance Criteria
  

-  [x] [Copy deck](https://docs.google.com/spreadsheets/d/1BBSwn0EBnsDy-dfPXVK507wt_wcc_i3bXkcnEcFv2pM/edit#gid=0) started

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
PDFs of copy deck at this moment in time
[Personalization MVP copy deck - New home screen.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1F6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--325410fc8023fc9cf219d7ba2192677d822afbb2/Personalization%20MVP%20copy%20deck%20-%20New%20home%20screen.pdf)
[Personalization MVP copy deck - Benefits category screen.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1V6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9315d6e516b3b02abb52ddc97580ce2c177611e5/Personalization%20MVP%20copy%20deck%20-%20Benefits%20category%20screen.pdf)

[Personalization MVP copy deck - Health category screen.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1l6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a6cd9905ec1be14455cdbef4f625039e53721ab/Personalization%20MVP%20copy%20deck%20-%20Health%20category%20screen.pdf)

[Personalization MVP copy deck - Payments category screen.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2N6QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--819738a87743cb48cb70ee7e4c1033d5ddaaeef5/Personalization%20MVP%20copy%20deck%20-%20Payments%20category%20screen.pdf)
