### ISSUE TITLE
Push notifications: Document research questions

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#7338]
## Description 
Document research questions for push notifications for research planning & product prioritization purposes.

## Tasks
- Document research questions. Should include (but not be limited to) those related to the success measures established in the Product Brief
- Prioritize questions with PM & PO.
- Identify any questions where the answer is a showstopper/blocker to launch.

## Acceptance Criteria
  

-  [x] List of research questions

## Ticket Checklist

-  [x] Acceptance criteria defined
-  [x] Labels added (front-end, back-end, feature)
-  [x]  Linked to an Epic

**Comment by htcollier** [comment]
WIP: [VA mobile app - Push notification - Research Questions/Planning](https://docs.google.com/document/d/1nysEbMTHwSj5Qv8fGK56EKGIqTeFwA0HDNQsRTkzukk/edit)
