### ISSUE TITLE
Appointments: Support/QA on updates to appointments (part 2)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7459]
## Description 
I will provider support and visual QA on builds for the changes we're making to appointments.

## Tasks

- [ ] Answer any questions that come up during implementation
- [ ] Review builds to QA copy

## Acceptance Criteria
  

No actual deliverables

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
