### ISSUE TITLE
Personalization: Content support for design phase (part 3)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7460]
## Description 
As a Veteran using the VA: Health and Benefits mobile app, I want to get personalized information as soon as I open the app (on the home screen), so that I can manage my information and complete tasks that are most relevant to me without needing to "drill down" further into the app to find this information or complete these tasks.

## Tasks
- [x] Get feedback from Danielle on greeting, headers, descriptive words for headers
- [x] Get feedback on new vs unread in SM
- [x] Determine logic for name in greeting when we don't have preferred name (and document in copy deck)
- [x] Determine what the "active/in-flight thing" is that we're displaying for Rx on Home screen

## Acceptance Criteria
  

-  [x] [Content decision log](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/Content/Decision%20logs/Personalization%20content%20decision%20log.md) started
-  [x] Copy decisions that are made are reflected in the [copy deck](https://docs.google.com/spreadsheets/d/1BBSwn0EBnsDy-dfPXVK507wt_wcc_i3bXkcnEcFv2pM/edit#gid=0) completed

 

## My open questions/thoughts/things that need resolved
- [x] Welcome vs Hi
- [x] Preferred name < legal name < greeting logic
- [x] For Rx on Home screen, can we surface # ready for refill instead of active? May be more helpful than active.
- [ ] Modifier words for headers on Home screen
- [x] Announcement content area
- [x] New vs Unread for Messages (both Home & Health screens)

 

## Decisions made this sprint
- **Greeting**: Welcome on first-time sign in. Welcome back for subsequent sign ins. Use preferred name when we have it. Use legal first name if PN is not available. If no PN or legal first name, omit name and say Welcome
- **COVID-19 updates**: Removing from both Home but keep on Health. VA.gov deprioritized this content. But are data shows it is still being accessed, usually more from the Health screen. Veterans are still interacting with this content: less on the Home screen and more from Health. Health team can revisit removal once it's stood up.
- **Announcements**: We will follow the VA.gov's prominent announcement area, which is currently about PACT Act. CAIA may soon take over this section of VA.gov and the content of this section will also likely be relevant to app users. We will start Personalization MVP with PACT Act. And will monitor this content area of VA.gov and adjust our announcements section to align if/when it changes.
- **Descriptive word for Message count**: We'll use "unread." A Veteran could have an older message that is still unread. "New" conveys more like something that just happened and would be better saved for Notifications. I confirmed with Laura W. on CAIA that web Medications tools is using "unread."
- **Prescriptions**: What will determine the count is prescriptions that a Veteran can refill. We won't be including if there are prescriptions that are tracking due to unreliability of data. Descriptive word for Prescriptions count is still TBD.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
Closing ticket. AC 4 didn't get done as we had to go back to POs to make sure we aligned on scope of work.
