### ISSUE TITLE
TEST epic ticket: VA Health Benefits app

### ISSUE THREAD

**Issue by rachelhanster** [department-of-veterans-affairs/va-mobile-app#7612]
# Project Status Overview

### Project Objective:

- High level description of the project and what we are trying to solve

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal dependency ? |   |
| External dependency ?  |   |
|  |   |

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

|Step | Timing | 
|-------| ---------| 
|Sprint 0 - Discovery |    |
|Step 1 - Strategy |   |
|Step 2 - Design  |   |
|Step 3 - Building / Implementing |   |
| 100% Release |  |
|Step 4 - Post Verification|   |
</details>

### Monthly Update for Stakeholders
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Month Year | 
|Month Year| .....
|Month Year|
|Month Year|
</details>

# Detailed Project Scope 

### Current Veteran Experience 
<details>
<summary>What the Veteran experiences today and its painpoints</summary>

**Veteran Experience**

**Veteran Painpoints**

</details>

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.)
 
 2.) 
 
 3.) 
 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.)
 
 2.) 
 
 3.) 
 
 
</details>

### Definition of Done 
<details>
<summary>Conditions that must be true in order to consider this project completed</summary>

|Item | Completed | 
|-------| ---------|
| | | 
| | | 

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| | | 
| | | 

</details>

### Important Project Links 
<details>
<summary>Links</summary>
 
- Github Epic
- Github VA Mobile Page
- - Product Brief
- Product Canvas
- Design 
   - Discovery
   - Mockups
   - Final Design
   - Figma File
- Research
   - Research Plan
   - Research Results and Findings
-Analytics
-Decision Log 
</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Rachel Han or  Ryan Thurlwell
- **VA OCTO Product Leads:** 
- **External Team 1 & Role:**
- **External Team 1 & Role:**

**Ad Hoc:** 
- **Mobile Team**: Global, Health and Benefits, Design System, QA, API 
- **Mobile Team Lead:** 
- **FE Engineering:**
- **BE Engineering:** 
- **Design:**
- **Content**
- **QA:**
- **Mobile Teams that are involved:** Global, Health and Benefits, Design System, QA, API 

</details>

### OKR and Analytic Metrics 
<details>
<summary>Analytic Information </summary>

**What KPIs / OKRS are the focus of this project?**

1.) 

2.) 

**The link to the project's analytical dashboard**

|What we are measuring | Why | How / Event Name |
|-------| ---------| ----- |
| How will we determine this is a success?  | | |
| How will we determine if this is not a success? | | |

|Analytic Event| What is it measuring | How to use it to measure |
|-------| ---------| ----- |
| | | 
| | | 

</details>

### Questions 
<details>
<summary>Open Questions</summary>
 
 - How are we measuring success? 
 
 - What is MVP and what is out of scope?
   
 - Has there been existing research or work done on this project before?
   
 - Is this work being done within the VA today (ex. web) 
 
</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer | Owner |
|--------|----------|------|
| | | |
| | | |

</details>

### Change / Decision Log 

Product will need to create on in the Github folder and link it here. 

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] PM to create new Github epic and fill out accordingly (Type - Epic, Template - Epic Ticket
       - [ ]  Updated so it is seen in Mobile and External Github Boards - may need to view this epic in Github and not Zenhub
   - [ ] PM to create new Github folder for feature or update existing
       - [ ] Create a separate document for the project's decision log - link it here  
   - [ ] Project Kickoff session to review problem statement, Veteran experience, and goals with stakeholders
   - [ ] Determine team roles, responsibilities, approvers with stakeholders
   - [ ] Determine future cadance reviews with stakeholders 
   - [ ] Review dependencies 
   - [ ] Scope finalized or approved by Mobile POs
   - [ ] PM to create and/ or link Product Brief
   - [ ] Other: 

**Pre-Production Readiness**
- [ ] PM to update [Call Center Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/releases/Call%20Center%20Docs)
    - [ ] Coordinate with contact center support teams to have guide out before feature in production 
- [ ] PM to determine if In-App What’s New feature needs to be used and coordinated with Content / Engineering to complete - tickets needed 
    - [ ] If so, will need to determine content before release 
- [ ] PM to determine if VA, Apple, Google App stores need changes and coordinate with UX / Engineering to complete - tickets needed
    - [ ] Apple Store - Content, Whats New, Phone Images, iPad Images 
    - [ ] Google Playstore - Content, Whats New, Phone Images
    - [ ] [VA App Store - Content, Phone Images](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/VA.Gov%20App%20Store)
- [ ] UAT complete, if applicable
- [ ] Update demo mode to ensure demo mode matches production
- [ ] Complete automation/detox work for new / updated feature
- [ ] Stakeholder demo completed 
- [ ] Release plan - (slow rollout, 100% release, other) - link to plan 
- [ ] Review existing bugs and open tickets to determine if they need to be include in MVP or considered post-mvp work
    - [ ] If post MVP work - create separate epic to store work 
- [ ] Coordinate with Release coordinator from QA and Release Team on when release is expected 
- [ ] Design work to update hi-res internal files
- [ ] Engineering created successful unit tests 
- [ ] UX has completed visual QA
- [ ] Content has completed content QA
- [ ] Accessibility testing has been completed
- [ ] QA sign off 
- [ ] Obtain Go/No Go decision from Mobile POs and / or Octo POs for launch
- [ ] PM fills out and completes Epic's checklists 
- [ ] Post launch monitoring plan / post production follow-up
- [ ] Other: 
  
**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [ ] PO prioritization determined
- [ ] Dependencies resolved 
- [ ] Determine if Veteran Research is needed, if so link Rsearch Plan
- [ ] UAT Needed, if so link UAT plan
- [ ] Steps process completed and documented
- [ ] Waygate / feature flag needed
- [ ] Update demo mode
- [ ] Accessibility needs
- [ ] Where updates need to be communicated (Team of Teams, MHV Weekly Standup, other, etc) 
- [ ] What approvals will we need (ex. Internal POs, External POs, CAIA, external, etc) 
- [ ] How and when are we going to measure success / failure
- [ ] Does In-App App Store Feedback need to be modified for this project
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable 
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received on finalized design - link to approval
- [ ] Design QA / Visual QA approval
- [ ] If QA testing needed, coordinate with QA agent
- [ ] Component review
- [ ] Accessibility review 
- [ ] Design system review
- [ ] Update internal documents
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Content Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App
- [ ] Write copy for app stores' What's New sections.
- [ ] Write copy for updated screenshots in app stores
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Engineering Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?
- [ ] Do we need to update our in-app review code to include this new feature?
- [ ] Determine what analytics are going into production with MVP 
- [ ] Other: 

</details>

<details>
  <summary>Toggle QA Checklist</summary>
 
- [ ] Team PM creates test plan and assigns to Team QA agent-  Template: QA Test Plan
- [ ] QA agent to monitor and speak up on QA needs for the project
- [ ] Document decision in the descision log regarding QA 
- [ ] Identify test data needs
   - [ ] Determine and document test accounts used 
- [ ] Test plan creation and resolution 
- [ ] Successful testing on all MVP tickets 
- [ ] Reviews open bug tickets pre-production
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail - MVP 
- [ ] Added feature cases to appropriate section of active cases in TestRail - MVP 
- [ ] Detox UI / Automation work completed - MVP
- [ ] Other:

</details>

<details>
  <summary>Analytics Checklist</summary>
 
- [ ] Discussion on what can and can't be measured pre-design
- [ ] Determine what analytics work is included in for MVP 
- [ ] Document non-mvp analytic needs in Github 
- [ ] Update Analytics section of this epic 
- [ ] Determine if analytics can be tested by QA - if so coordinate with QA 
- [ ] Modify or create dashboard to account for this feature 
- [ ] Determine how long after production that analytics can be measured and reviewed 
- [ ] Other:
 
</details>

**Comment by EricaRobbins** [comment]
@rachelhanster do we still need this Test issue open or can we close it and move it to "Not Doing"?

**Comment by rachelhanster** [comment]
I'm closing this ticket as this was used to test different users' read/write permissions.
