### ISSUE TITLE
Profile | Settings | Notifications: Spike on changing notification label copy

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#7701]
## Description 
I'd like to update the label copy for turning on notifications for messages and appointments.

<img width="600" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWpCQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6e071063c73917211a6a22265aa943352010b14d/IMG_BC2192ECA966-1.jpg" alt="IMG_BC2192ECA966-1.jpg" />

But we learned in [this ticket](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/7393#event-11469329028) that this copy is coming from the API VEText endpoint (/v0/push/prefs/{endpointSid} in the mobile api). Ideally, we should use the same label copy across web and app. This means I need to look into how complicated it might be to influence that change on VA.gov.

## Tasks/Questions
- [X] Who owns this?
- [X] What are CAIA's thoughts?

## Acceptance Criteria
  

-  [X] A decision as to whether we should leave copy label as is

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Pulling this into the sprint as I'm working on push strategy now.

**Comment by mistymg** [comment]
DSVA Slack asking VANotify team: https://dsva.slack.com/archives/C010R6AUPHT/p1709563924847859

DSVA Slack asking Profile team: https://dsva.slack.com/archives/C909ZG2BB/p1709561429025629

**Comment by mistymg** [comment]
Was able to align with Laura W on CAIA to change toggle labels to "Appointment reminders" and "New secure message". Got VEText team to update API with this copy (see Slack thread above). Confirmed in test user that copy is now how we want it. Will unblock bug 8075 to get accurate copy in demo mode, too.
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHF6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a5fe71e2809604f86e2d93b703568009647e4459/IMG-0209.PNG" alt="IMG-0209.PNG" />
