### ISSUE TITLE
UX - Push Notifications - “Enable push notifications” opt-in flow - Design Phase - MVP

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#7880]
## Description
The Flagship mobile app doesn’t provide any context as to what types of notifications the app will send when it asks users to enable push notifications at app level during the app's first run after install. This runs contrary to industry best practices (see [comparative analysis](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-comparative-analysis-2023.md#how-do-apps-approach-asking-users-to-enable-push-notifications) & [best practices](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-best-practices.md) discovery documents below). 

We believe that setting context will help maintain high opt-in rates (83.13% for iOS and 86.04% for Android), especially as more push notifications are added. In addition, this is another opportunity to provide context to new users about the value the app provides—which is particularly important due to high onboarding drop offs.

**Current high-level experience:** 
- iOS: The standard “Enable push notifications” opt-in modal alert is displayed during the first use of the app. It’s displayed after install, login, and biometrics permissions but before the onboarding carousel. As a result, notifications are either enabled (with all types are toggled on by default) or disabled at app settings level. If they're disabled, it takes multiple steps (within the phone's app settings) to turn notifications on again.
- Android: Consent, to enable notifications, is not asked for at any time; all notifications are toggled on by default.
<img width="992" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1b415da8d318905c031464cba0e9e9ea0ba9594/image.png" alt="image.png" />

As part of this story, we want to **demonstrate the value of the app and provide more context to users (for both Android and iOS) around how the app will use push notifications** before asking them to enable or disable them for the app via push notification opt-in modal alert. 

## Tasks
**Discovery**
- [x] Review Push notifications - Discovery (below) as [well as Figma board](https://www.figma.com/file/cPH4ZieO1Fvl0qGfBnLwpS/Push-Notifications---Discovery---VA-Mobile?type=whiteboard&node-id=0%3A1&t=Km4vneN1OVxo6a0v-1) for best practices/inspiration.
- [x] Document experience for the current first run after install (including push opt-in, onboarding, etc)

**Design**
- [x] Explore and mock up options and locations (first run/onboarding? contextual/anchored to a behavior? double-request pattern?) for setting expectations in the enable push notifications opt-in flow. Consider both iOS and Android. Keep MVP as well as longer term approach in mind.
- [x] Feasibility review & input from ENG, PM
- Content recommendation (to be ticketed separately)

## Acceptance Criteria
- [x] Mock ups (for Android & iOS) containing the following have been created: 
   - Context-setting step (before native opt-in request), including where it goes in the first run flow
   - Native opt-in step

## Notes & Open Questions
**Discovery:**
- [Comparative Analysis: Push Notifications: How do apps approach asking users to enable push notifications?](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-comparative-analysis-2023.md#how-do-apps-approach-asking-users-to-enable-push-notifications)
- [Discovery/Desk Research: Push Notification Best Practices - Permissions & management](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/discovery/push-notification-best-practices.md)

**Strategy:**
- [Push Notifications Design Strategy Worksheet](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/ux/push-notifications-design-strategy-worksheet.md)
- [Push Notification Strategy - Product Brief](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/va-mobile-app/features/Push%20Notifications/product/Push%20Notification%20Product%20Brief.md)

## Ticket Checklist
- [x]  Acceptance criteria defined
- [x]  Labels added (front-end, back-end, feature)
- [x]  Linked to an Epic

**Comment by htcollier** [comment]
[Mapped screen-by-screen logic for current experience in Figjam](https://www.figma.com/file/cPH4ZieO1Fvl0qGfBnLwpS/Push-Notifications---Discovery---VA-Mobile?type=whiteboard&node-id=777-952&t=KjxMBiJqZShAlHna-4)
[Uploading... image.png]

**Comment by htcollier** [comment]
Shared [four approaches (of varying LOE)](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=993-8290&mode=design&t=p5spJcAxJGeVuKc7-4) with UX folks for preliminary feedback.

**Comment by htcollier** [comment]
Shared [four approaches (of varying LOE) ](https://www.figma.com/file/LKmqgew3L2nSBl0qF6YOwI/%F0%9F%94%8D-Home-2.0---Working---VAMobile?type=design&node-id=993-8290&mode=design&t=p5spJcAxJGeVuKc7-4)with ENG, PM for feasibility & product feedback.

**Comment by htcollier** [comment]
Per @TKDickson, 74% of VA H&B mobile app users are on version 13 or later as of Feb 2024: <img width="1416" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTU2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4563c1eb6d1b102ba084c785f6e795c4c986ef99/image.png" alt="image.png" />

**Comment by htcollier** [comment]
@theodur took a look at the Target app on a device running Android 13 and confirmed:
- The notifications native permissions modal appears in the app's onboarding: 
   - It does not show a context-setting screen that iOS does. 
   - After tapping "Allow,' it enables push notifications in the background
- Android uses an alternate version of the double request pattern: 
  - After pushing “Don't allow” in the initial native opt-in (dismissing the prompt), it displays the native opt-in **again** when I navigate to the MyTarget screen.

**Comment by htcollier** [comment]
**UX recommendation for notifications opt-in for Android & iOS:**
- **Onboarding:**
   - **iOS & Android 13 and higher:** Show the context-setting screen in onboarding and use double request pattern design. 
   - **Android 12 and lower:** Keep onboarding flow as-is (turn on automatically, don't show context setting screen) if it's easier, otherwise go ahead & show for all Android versions.
- **Notifications screen:** Implement new state for Notifications screen for all OS versions if Notifications are disabled at device level. "Turn on notifications" button triggers notifications opt-in (on Android & if not opted in yet on iOS) or sends user to app's device settings (if they've previously opted out).

**Reasoning:** 
- The vast majority of VA H&B mobile app users (74%) are on an OS that requires an explicit opt-in for notifications. Just because opt-in isn't restricted in the same way for Android, it doesn't mean that users won't benefit from understanding how push is used in the app (and the value that the app brings).
- Implementing a new state for the notifications screen gives us another opportunity to set context and encourage users to enable push if they haven't yet.

**Comment by htcollier** [comment]
Android opt-in documentation was updated in March to include a more detailed description: 
- [Notification Permission for Opt-In Notifications](https://source.android.com/docs/core/display/notification-perm)
- [Notification runtime permission](https://developer.android.com/develop/ui/views/notifications/notification-permission)
