### ISSUE TITLE
QA - Home screen personalization test cases, pt 1

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#7903]
Ticket for work this sprint to start adding cases for the completed tickets for HS personalization, to the TestRail repository ([in this folder](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=13520)).

With the UI, content and screen appearance logic settling into place, can start writing cases without having to constantly rework.

Should cover: 
* New sections of the homescreen (can use [this ticketing mural](https://www.figma.com/file/bzkg7cMn8iZj9mJGjETGTW/Home-Screen-Grooming?type=whiteboard&node-id=0-1&t=5ekpZSYA5LBvB5wm-0) as a guide) & starting content
* New category screen appearance

**Comment by TKDickson** [comment]
New test cases are (until feature release) in [the home screen personalization folder](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_id=13520&group_order=asc&display_deleted_cases=0) in the upcoming features folder.

**Comment by TKDickson** [comment]
Workable as of Feb20
- [ ] Update Crisis Line CTA Component with New Home Screen Designs #7850
- [ ] Create Activity Section with Populated, Loading, and Empty States#7935
- [ ] Create & Implement Deeplink Home Screen Button Component #7876
- [ ] Create About You Section with Populated, Loading, and Empty States#7968
- [ ] Create and Implement New Veteran Status Card Component #7940
- [ ] Create Disability Rating and Monthly Payment Component#7966
- [ ] Create VA Resources Section with Populated, Loading, and Empty States#7971
- [ ] Link Row Component Creation & Implementation #7599
- [ ] Remove Covid-19 Updates from Home Screen#7853
- [ ] Create Banner for Announcements at Bottom of Home Screen#7852
- [ ] Update Category page template with new home screen personalization UI#7598
- [ ] Update Large Nav Button Component for Category Screen#7936
- [ ] Health Category Screen Counting Logic and Content#7478
- [ ] Benefits Category Screen Counting Logic#7383

Not yet workable as of Feb 20:
- [ ] Activity Section Error and Edgecase#7937
- [ ] Refresh information in home screen activity section (7728)
- [ ] About you section error and edge cases#7967

Tickets that may/may not be written:
- Refresh info in category screen large nav buttons

**Comment by TKDickson** [comment]
Finished initial set of cases and wrote #8030 for further work (not yet workable tickets from above, plus anything else that's added). Closing.
