### ISSUE TITLE
VAHB Availability Framework 2024 Usage and Improvements 

### ISSUE THREAD

**Issue by bischoffa** [department-of-veterans-affairs/va-mobile-app#7916]
# Project Status Overview

### Project Objective:

- Epic overseeing the usage and improvements to VAHB Mobile App's Availability Framework feature. Single place to track usage of AF and improvement ideas for when they are prioritized to make the feature and usage better. 

 
### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>

|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Unclear ownership of who owns AF usage and AF improvements  |   |
|  Immediate use cases that were unplanned given feature was not build with VA problems impacting Mobile; built focused on handling Mobile's problems. Causing complications on ownership, handling, and also showing the feature needs improvements  |   |
|  |   |

</details>

### Project Timeline
<details>
<summary>Milestones</summary>

|Step | Timing | 
|-------| ---------| 
|Launch |    1/30/24 Release 2.20 |
|VA's Redis Situation |   |
|VA's Cerner Situation |   |

</details>

### Monthly Update for Stakeholders
<details>
<summary>Updates</summary>

|Month| Project Health | Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| ---------|--------|---------|
|Jan 2024 |  Green | Feature launched; used for VA Redis issue that was turned boff after hours because VA communicated they postponed the update after hours. Redis situation probed AF worked in production for login | After hour monitoring, having to monitor if VA's timing is actually going to happen |  
|Feb 2024 | Ongoing Epic | New VA use case involving Cerner Facilities due to upstream change negatively impacting Mobile Veteran users. Required AF to make changes in order to facilitate communication to Mobile users which barely got into the sprint given limited notice to Mobile | 
|Month Year|
|Month Year|
</details>

# Detailed Project Scope 

### Current Veteran Experience 
<details>
<summary>Mobile Veteran are going to experience a Mobile feature usage issue our outage due to VA changes that are uncontrollable by Mobile (updates not using maintenance windows, projects that did not plan for Mobile impact, emergency issues, etc) or by Mobile team introducing a bug or an issue , AF enables the ability to plug this gap to improve the user experience by communicating the issue and preventing access until the root cause is solved and implemented.  </summary>

**Veteran Experience**

**Veteran Painpoints**

</details>

### Assumptions 

<details>
<summary>Assumptions that need to be true for this project</summary>

 1.) AF usage will encourage Veterans to update to a different mobile version which has the fix 
 
 2.)  The way Mobile' build AF for their own issue; is usable for applying it upstream VA circumstances that negatively impact Mobile Veterans 
 
 3.) 
 
 
</details>

### Risks 

<details>
<summary>Risks identified and accepted by stakeholders</summary>

 1.) Project MVP built around the use case of handling Mobile's problems not problems VA causes upstream that negatively impact Mobile 
 
 2.) Only applicable for Veterans using the mobile app version of 2.20 and newer ; prior to that version there is no protection 
 
 3.) Could become unmanageable if used in complicated ways such as multiple versions / variations 

 4.) Using AF for something it was not build for 

 5.) Possible bandaiding of the true issue  
 
 
</details>

### Definition of Done 
<details>
<summary>Conditions that must be true in order to consider this project completed</summary>

This is for tracking the usage and updates to AF for 2024. Once 2024 is over the epic is closed. Open work will be migrated to a different feature.  

</details>

### Project Scope
<details>
<summary>Items in and out of scope</summary>

|In Scope | Out of Scope| 
|-------| ---------|
| Usage of AF for Mobile Issue  | | 
| Usage of AF for VA issue | | 
| Capturing possible improvements for AF | | 

</details>

### Team Members

<details>
<summary>Contact List</summary>

**VA:**
- **Mobile OCTO Product Leads:** Rachel Han or  Ryan Thurlwell
- **VA OCTO Product Leads:** 
- **External Team 1 & Role:**
- **External Team 1 & Role:**

**Ad Hoc:** 
- **Mobile Team**: Global, Health and Benefits, Design System, QA, API 
- **Mobile Team Lead:** 
- **FE Engineering:** Jon Binbeutel 
- **BE Engineering:** 
- **Design:**
- **Content**
- **QA:**
- **Mobile Teams that are involved:** Global, Health and Benefits, Design System, QA, API 

</details>

### OKR and Analytic Metrics 
<details>
<summary>Analytic Information </summary>

**What KPIs / OKRS are the focus of this project?**

1.) 

2.) 

**The link to the project's analytical dashboard**

|What we are measuring | Why | How / Event Name |
|-------| ---------| ----- |
| How will we determine this is a success?  | | |
| How will we determine if this is not a success? | | |

|Analytic Event| What is it measuring | How to use it to measure |
|-------| ---------| ----- |
| | | 
| | | 

</details>

### Questions 
<details>
<summary>Open Questions</summary>
 
 - How are we measuring success? 
 
 - What is MVP and what is out of scope?
   
 - Has there been existing research or work done on this project before?
   
 - Is this work being done within the VA today (ex. web) 
 
</details>

<details>
<summary>Closed Questions</summary>

| Question |  Answer | Owner |
|--------|----------|------|
| | | |
| | | |

</details>

### Change / Decision Log 

Product will need to create on in the Github folder and link it here. 

# Checklist

<details>
  <summary>Toggle Product Checklist</summary>

**Project Kickoff & Requirements Gathering**
   - [ ] PM to create new Github epic and fill out accordingly (Type - Epic, Template - Epic Ticket
       - [ ]  Updated so it is seen in Mobile and External Github Boards - may need to view this epic in Github and not Zenhub
   - [ ] PM to create new Github folder for feature or update existing
       - [ ] Create a separate document for the project's decision log - link it here  
   - [ ] Project Kickoff session to review problem statement, Veteran experience, and goals with stakeholders
   - [ ] Determine team roles, responsibilities, approvers with stakeholders
   - [ ] Determine future cadance reviews with stakeholders 
   - [ ] Review dependencies 
   - [ ] Scope finalized or approved by Mobile POs
   - [ ] PM to create and/ or link Product Brief
   - [ ] Other: 

**Pre-Production Readiness**
- [ ] PM to update [Call Center Guide](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/releases/Call%20Center%20Docs)
    - [ ] Coordinate with contact center support teams to have guide out before feature in production 
- [ ] PM to determine if In-App What’s New feature needs to be used and coordinated with Content / Engineering to complete - tickets needed 
    - [ ] If so, will need to determine content before release 
- [ ] PM to determine if VA, Apple, Google App stores need changes and coordinate with UX / Engineering to complete - tickets needed
    - [ ] Apple Store - Content, Whats New, Phone Images, iPad Images 
    - [ ] Google Playstore - Content, Whats New, Phone Images
    - [ ] [VA App Store - Content, Phone Images](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/va-mobile-app/VA.Gov%20App%20Store)
- [ ] UAT complete, if applicable
- [ ] Update demo mode to ensure demo mode matches production
- [ ] Complete automation/detox work for new / updated feature
- [ ] Stakeholder demo completed 
- [ ] Release plan - (slow rollout, 100% release, other) - link to plan 
- [ ] Review existing bugs and open tickets to determine if they need to be include in MVP or considered post-mvp work
    - [ ] If post MVP work - create separate epic to store work 
- [ ] Coordinate with Release coordinator from QA and Release Team on when release is expected 
- [ ] Design work to update hi-res internal files
- [ ] Engineering created successful unit tests 
- [ ] UX has completed visual QA
- [ ] Content has completed content QA
- [ ] Accessibility testing has been completed
- [ ] Demo mode has been updated - MVP
- [ ] QA sign off 
- [ ] Obtain Go/No Go decision from Mobile POs and / or Octo POs for launch
- [ ] PM fills out and completes Epic's checklists 
- [ ] Post launch monitoring plan / post production follow-up
- [ ] Other: 
  
**Feature Go Live**
- [ ] Ensure Waygate/Feature toggle release ticket submitted w/engineering & QA 
  - **Template: Turn on Waygate/Turn off feature flag**
- [ ] Coordinate with content & release coordinator if what’s new in app is required
</details>

<details>
  <summary>Toggle Team Collaboration Checklist</summary>

- [ ] Design Intent & Feasibility discussions
- [ ] PO prioritization determined
- [ ] Dependencies resolved 
- [ ] Determine if Veteran Research is needed, if so link Rsearch Plan
- [ ] UAT Needed, if so link UAT plan
- [ ] Steps process completed and documented
- [ ] Waygate / feature flag needed
- [ ] Update demo mode
- [ ] Accessibility needs
- [ ] Where updates need to be communicated (Team of Teams, MHV Weekly Standup, other, etc) 
- [ ] What approvals will we need (ex. Internal POs, External POs, CAIA, external, etc) 
- [ ] How and when are we going to measure success / failure
- [ ] Does In-App App Store Feedback need to be modified for this project
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Design/UX Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Review problem/opportunity statement
- [ ] Add questions and assumptions to product brief
- [ ] Add research links to product brief
- [ ] Document high-level research/design plans
- [ ] Create lo/hi fi wireframes & user flows if applicable 
- [ ] Add links to Epic & applicable GitHub folders
- [ ] Socialize designs
- [ ] Sign off received on finalized design - link to approval
- [ ] Design QA / Visual QA approval
- [ ] If QA testing needed, coordinate with QA agent
- [ ] Component review
- [ ] Accessibility review 
- [ ] Design system review
- [ ] Update internal documents
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Content Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Review product brief and surface any questions, assumptions & risks
- [ ] Participate in project discovery and kickoff activities/ceremonies
- [ ] Complete comparative analysis/content research activities for net-new content
- [ ] Review current content and determine where app may need to differ and potential improvements to share with web
- [ ] Review past VA research and decisions documentation
- [ ] Support Research & UX Design in research sessions and synthesis
- [ ] Make content recommendations for lo-/hi-fi wireframes in collaboration with UX Design
- [ ] Collaborate with Sitewide Content team for alignment, improvements, and sign-off
- [ ] Participate in FE hand off
- [ ] Complete content QA
- [ ] Write copy for What's New In App, if needed 
- [ ] Write copy for app stores' What's New sections, if needed 
- [ ] Write copy for updated screenshots in app stores, if needed 
- [ ] Other:
      
</details>

<details>
  <summary>Toggle Engineering Checklist</summary>
 
- [ ] If QA testing needed, coordinate with QA agent and assign QA agent to the ticket
- [ ] Are UI designs/ specs available/ready? If yes, they should be attached to  attach specs. (We are assuming the design specs have been approved)
- [ ] Are there any deadlines that need to be met?
- [ ] What is the roll out plan? (Do we need a feature toggle? is this going to be available to every user immediately or do we want to roll out to a few users first)
- [ ] Does this project require api integration? if yes, what api endpoint are we integrating with and what is the expected response body?
- [ ] Do we want to capture analytics for this projects (i.e. update GA, add logs to grafana/datadog etc)?If yes, what metrics would we like to capture?
- [ ] Do we need to update our in-app review code to include this new feature?
- [ ] Ensure demo mode is updated and working properly with the latest change/feature
- [ ] Determine what analytics are going into production with MVP 
- [ ] Other: 

</details>

<details>
  <summary>Toggle QA Checklist</summary>
 
- [ ] Team PM creates test plan and assigns to Team QA agent-  Template: QA Test Plan
- [ ] QA agent to monitor and speak up on QA needs for the project
- [ ] Document decision in the decision log regarding QA 
- [ ] Identify test data needs
   - [ ] Determine and document test accounts used 
- [ ] Test plan creation and resolution 
- [ ] Successful testing on all MVP tickets 
- [ ] Reviews open bug tickets pre-production
- [ ] Waygate tasks complete
- [ ] Added new feature cases to the RC in TestRail - MVP 
- [ ] Added feature cases to appropriate section of active cases in TestRail - MVP 
- [ ] Detox UI / Automation work completed - MVP
- [ ] Other:

</details>

<details>
  <summary>Analytics Checklist</summary>
 
- [ ] Discussion on what can and can't be measured pre-design
- [ ] Determine what analytics work is included in for MVP 
- [ ] Document non-mvp analytic needs in Github 
- [ ] Update Analytics section of this epic 
- [ ] Determine if analytics can be tested by QA - if so coordinate with QA 
- [ ] Modify or create dashboard to account for this feature 
- [ ] Determine how long after production that analytics can be measured and reviewed 
- [ ] Other:
 
</details>

**Comment by kellylein** [comment]
Closing as this ticket is no longer applicable
