### ISSUE TITLE
UX - Create missing Notifications screen state within shipped files

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#7952]
## Description:
In the [shipped files for Profile, Notifications](https://www.figma.com/file/O6sdr5N7xV6GOZhTPcgY5x/%F0%9F%9A%A2-Profile-2.0---Shipped---VA-Mobile?type=design&node-id=873-16769&mode=design&t=v5ogM5UjIixEUVBu-4) is missing the state where the user has opted out of or turned off notifications (pictured below):

<img width="300" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejVEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfc23b66447a8206c258e3a21c18343dfa881297/IMG_4242.PNG" alt="IMG_4242.PNG" />

## Tasks:

- [ ] Create new light & dark mode screens for this case in the Profile section

## ACs:
- [x] Screen state for Profile / Settings / Notifications - opted out in Light & Dark mode are in Figma
 

## Ticket Checklist
- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by brea11y** [comment]
These screens have been added to the shipped files. [They can be found here](https://www.figma.com/file/O6sdr5N7xV6GOZhTPcgY5x/%F0%9F%9A%A2-Profile-2.0---Shipped---VA-Mobile?type=design&node-id=1371-16800&mode=design&t=uL5jLUClOtZNUNry-4).
