### ISSUE TITLE
QA - Home screen personalization, test cases pt. 2

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#8030]
Ticket for work this sprint to start adding cases for the completed tickets for HS personalization, to the TestRail repository ([in this folder](https://dsvavsp.testrail.io/index.php?/suites/view/92&group_by=cases:section_id&group_order=desc&display_deleted_cases=0&group_id=13520)).

With the UI, content and screen appearance logic settling into place, can start writing cases without having to constantly rework.

Initial test case ticket was #7903

This ticket will cover: 
- [x] Activity Section Error and Edgecase #7937 
- [x] (about you Section Error and Edgecas #7967
- [ ] Refresh information in home screen activity section (7728)
- [x] Health category error and edge #7939
- [x] Benefits category error and edge #8038

As well as tickets that may/may not be written:
- Refresh info in category screen large nav buttons
- Retire old message unread indicator
- etc

Not sure how many further tickets will be created & groomed for home screen, so holding off on estimates (and final "ACs" for this ticket) until that's known.

**Comment by TKDickson** [comment]
Confirmed that for all tickets on the home screen MVP requiring testing, I've got my testing plan in the comments (either link to relevant TestRail cases, or written out if short, or both). 

Except the refresh thing. That I will just handle when we figure out what we're doing.

Closing. test plan review is happening at this point and documented in #8140
