### ISSUE TITLE
Push notifications: Review product brief for promotional push

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8162]
## Description 
Product (Ameet) asked that I review the Promotional Push Notifications product brief to give input from a content point of view. 

## Tasks
  

-  [x] Review [Promotional Push Notifications product brief](https://docs.google.com/document/d/1ozJrDUSfCCOlbH0GdLDyAApUNE7GO6hI7o1FPLfIs-g/edit#heading=h.mnq6vtjqteg4)
-  [x] Provide input from a content lens

## Acceptance criteria

- [x] Comments in product brief

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
