### ISSUE TITLE
Video appointments: Content changes from audit

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8165]
## Description 
As a Veteran checking all my video appointments (upcoming, past, canceled) in the mobile app, I want to get only the most important information depending on the type of appointment I'm reviewing, so that I'm prepared for my appointment or I know what next steps I need to (or don't need to) take related to these appointments.

As part of this story, we want to:   

- Use our finding from the content audit from Q3 2023 to update all video appointments in the mobile app.

## Tasks/ACs

- [x] Get back up to speed on what we did for this audit
- [x] Input information into Meko's [use case spreadsheet](https://docs.google.com/spreadsheets/d/1Q_kdxH1zJjmJ0xF5XC7aMUVzlwxtO3wAEvYxFrTACsc/edit#gid=0)
- [x] Sync with UX designer to align on [Figma designs](https://www.figma.com/file/ZIHY63cFlD7pFjqQLA5rFN/%F0%9F%94%8D-Appointments-2.0---Working---VAMobile?type=design&node-id=731-2493&mode=design&t=FPsC5JqzSRVET4fO-0)
- [x] Review screens created by UX designer
- [x] Edit copy on screens as needed
- [x] Share final designs with PM for hand-off to Eng

## Ticket Checklist

- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Pulling this back out as Lauren and I decided to prioritize headings on details screen first to make this work easier eventually

**Comment by mistymg** [comment]
Was able to update spreadsheet and designs with copy for video appts. But after sharing with PM/Eng, we realized we're running into the same problems we encountered with in-person/phone. And that is that we're creating more of a code mess with approaching change by modality instead of by common "components" of information across all details screens. PM decided we would set aside handing off/implementing new copy/designs for video until we can clean up the code first and therefore make future changes easier.
