### ISSUE TITLE
Appointments: Review of Details screen headings

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8182]
## Description 
As part of the appointments content audit last year, we completed updates to the details screen for phone and in-person (VA) appointments. As we started to look at tackling video appointments (home, at VA, ATLAS, GFE), we realized we need to look at how we're handling headings across all Details screens.

Updating the headings in Details screens across all appointment types/modalities will create closer alignment with what web is implementing as well as set us up to more easily implement changes to video appointments (and others, like C&P, CC, and pending).

## Tasks/ACs

- [X] Review all possible fields/headings on details screens across all appointment modalities in collaboration with UX and determine where (1) new headings are needed and (2) if current headings needs updated copy.

## Notes & Open Questions

- Question: Web includes "scheduling facility" on some modalities. Do we want to do that?
- We will need to share this at Appointments SME sync that occurs biweekly on Tuesdays. Next one is on 3/26.
- For ATALS video appointments, we should combine the "How to join" and "Appointment code" sections.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
We sketched out
