### ISSUE TITLE
Appointments: Ongoing work helping UAE create content library in Figma - Part 1

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8323]
## Description 
I'm going to provide ongoing support the Unified Appointments Experience (UAE) to create a content library in Figma across all of UAE (Appt web/mobile app, Check In, Travel). This effort will help identify content gaps and also identify/create reusable content across the experience.

## Tasks
  

-  [x] Chat with Peter about how to approach this project

## Notes

[Slack thread re: initial idea of project](https://dsva.slack.com/archives/C03CGTDLTFF/p1712340208427459)
[Another Slack thread on next steps](https://dsva.slack.com/archives/C03CGTDLTFF/p1714061741076509)

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Moving this to next sprint as I'm not going to be able to start it while trying to plan for quarter.

**Comment by mistymg** [comment]
Peter Russo is going to set up initial structure of library in [this Figma file](https://www.figma.com/file/enGXBfuvpWJOQp0onrWgHs/[DRAFT]-MHV---Unified-Appointments-Content-Library?type=design&node-id=0-1&mode=design&t=70l1KAgcYSItsPt6-0). Timeline is to have it ready to present at next Appt SME meeting on 5/7.

**Comment by mistymg** [comment]
Next touchpoint with this will be on 5/7 at which point I'll know what's required next.
