### ISSUE TITLE
UX: Measure In-App User Satisfaction - Discovery & Design Exploration

### ISSUE THREAD

**Issue by htcollier** [department-of-veterans-affairs/va-mobile-app#8445]
## Description
The VA Health & Benefits mobile app debuted in July 2021, initially relying on industry-standard app store ratings and reviews to gauge user satisfaction and feedback. However, as time progressed, it became evident to the app team the value of implementing a **targeted, in-app feedback tool** that complements the existing user feedback mechanisms in place.

This design & discovery work should explore potential mechanisms for collecting targeted in-app feedback via survey, including UI and display logic, taking existing App/Play store survey prompts into consideration. The actual content and phrasing of the survey questions will be covered by a separate ticket, so a placeholder based on [this Medallia survey](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia) using the following content can be used:
- “How easy was it to complete your task today?” [scale 1-5]
- “Question TBD” [freeform field]

## Tasks
**Discovery:** 

- [x] Review documentation & determine what is included out of the box with chosen survey tool (Medallia)
     - [x] [Medallia User Surveys Overview (Information on VA.gov surveys)](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams/vsp/teams/contact-center/medallia)
     - [x] [Medallia - Product Documentation](https://docs.medallia.com/en)
- [x] Review [comparative analysis on feedback collection mechanisms](https://www.figma.com/file/WpxFED4wlfbKD4LEqP9Pwm/In-app-recruiting-and-feedback---Discovery---VA-Mobile?type=whiteboard&node-id=5-327&t=FV39u0cAYq46SiM7-4)
- [x] Investigate & document appearance logic for current app store rating interaction on iOS & Android

**Design:**
- [x] Decide where/how the entrypoint for collecting user feedback lives in the app
     - [x] Determine format/design for dismissible, contextual intercept feedback survey request using placeholder questions above. 
     - [x] Determine display logic.

#### Open requirements questions:
- Are we required to include all of the PRA-related text that's included under the [standard VA.gov feedback survey](https://www.va.gov/#:~:text=health%20care%20programs.-,Feedback,-Sign%20up%20to)?  If not, what PRA-related info are we required to include?  
- How much introductory text are we required to include?   

#### Related resources:

- [Veteran Satisfaction & Feedback - Product Brief](https://docs.google.com/document/d/15m7pOBi1iY0fidH4XzMcaqf7qQyuQrKvr98v29tGBx0/edit)

**Discovery**   
- [Understanding and measuring your Customer Effort Score (CES)](https://www.hotjar.com/blog/customer-effort-score/). 
- [COMPARATIVE ANALYSIS: FEEDBACK COLLECTION & RECRUITING (Figma)](https://www.figma.com/file/WpxFED4wlfbKD4LEqP9Pwm/In-app-recruiting-and-feedback---Discovery---VA-Mobile?type=whiteboard&node-id=5-327&t=FV39u0cAYq46SiM7-4)
- [VA MOBILE APP: Current related mechanisms](https://www.figma.com/file/WpxFED4wlfbKD4LEqP9Pwm/In-app-recruiting-and-feedback---Discovery---VA-Mobile?type=whiteboard&node-id=5-328&t=QxF5mocM3hOoKenE-4)
- VA.gov CSAT survey [live survey](https://www.va.gov/find-forms/#:~:text=October%2012%2C%202022-,Feedback,-Veteran%20programs%20and) [Figma](https://www.figma.com/file/WpxFED4wlfbKD4LEqP9Pwm/In-app-recruiting-and-feedback---Discovery---VA-Mobile?type=whiteboard&node-id=234-1063&t=QxF5mocM3hOoKenE-4)
- [MEDALLIA IN-APP INTERCEPT SURVEY OPTIONS](https://www.figma.com/file/WpxFED4wlfbKD4LEqP9Pwm/In-app-recruiting-and-feedback---Discovery---VA-Mobile?type=whiteboard&node-id=234-760&t=QxF5mocM3hOoKenE-4)

## Ticket Checklist
- [x] Acceptance criteria defined
- [x] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by htcollier** [comment]
Description


[Veteran Satisfaction & Feedback - Product Brief](https://docs.google.com/document/d/15m7pOBi1iY0fidH4XzMcaqf7qQyuQrKvr98v29tGBx0/edit)

**Comment by htcollier** [comment]
In terms of in-app intercept/"invitation trigger" surveys, Medallia has several options with the In-App SDK, all editable without an app release using the Medallia Command Center.
- There are two "out of the box" in-app survey intercept options: 
  - a [modal banner invite](https://docs-assets.medallia.com/digital/docs-v2/mobile-sdk-docs/index.html#pages/getting-started/getting-started-full/invite-types/invite-types.html) 
  - a [native alert invite](https://docs-assets.medallia.com/digital/docs-v2/mobile-sdk-docs/index.html#pages/getting-started/getting-started-full/invite-types/invite-types.html). 
- There is also the option to design a completely [custom intercept UI & flow](https://docs-assets.medallia.com/digital/docs-v2/mobile-sdk-docs/index.html#pages/getting-started/getting-started-full/custom-intercept/custom-intercept.html)

**"Out of the box" intercept option overview**
<img width="1951" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMis2QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0cc8ea6bf59723a45efa7e8dac8cd18b7a8274b/image.png" alt="image.png" />

Both "out of the box" options are editable using the Medallia Command Center, and can dynamically be changed without an app release. The following elements are customizable:
 - Banner: text, background color, text color, position and view mode, duration, sticky mode on/off, buttons and button settings & colors, swap between predefined fonts, etc
 - Modal alert: button text, invitation text
 - Survey form: text, font & colors, button and button text color
 - Optional thank you prompt: text, font & colors

**"Custom intercept" option overview**
The [custom intercept UI & flow](https://docs-assets.medallia.com/digital/docs-v2/mobile-sdk-docs/index.html#pages/getting-started/getting-started-full/custom-intercept/custom-intercept.html) is an entirely customized intercept UI connected to the SDK eco-system. Mobile team would design, build & have complete control over the invitation UI, flow, and lifecycle
- It's editable using the Medallia Command Center, and can dynamically be changed without an app release. The following elements are customizable:
  - Invitation Title
  - Invitation Description
  - Provide Feedback Text
  - Defer Text
  - Decline Text
- no mandatory fields

**Survey form overview**
I was not able to find (in the Medaillia documentation) what the limitations are with the "out of the box" Survey form in the Medallia Command Center, or if it will allow us to create the exact form we need—we need someone to take a look at the actual software to determine that.

**Conclusion**
We should explore using an "out of the box" intercept & survey option for the CES feedback survey.
- Given that a CES survey is generally a sraightforward rating scale + question with freeform field, the Medallia Command Center survey seems like it will suit our needs (*need to confirm in the Medallia tool — contact VA Medallia team?).
- An intercept that directs the user to a full-page survey (as opposed to a custom UI that appears as a drawer, for example) will give us the most flexibility in terms of displaying required PRA language along with the survey.
- Using an "out of the box" tool will be faster to design & implement
- Given the VA mobile app's position on [limiting the use of modal alerts](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/Flagship%20design%20library/Patterns/confirmation-messages/), the modal banner invite option would be the best fit in terms of intercept format.

**Comment by htcollier** [comment]
Outside the scope of this particular ticket, but wanted to make note:

**Regarding PRA:** Could we use the pre-existing [generic clearance](https://pra.digital.gov/clearance-types/) VA has for the PRA approvals (["Title: Generic Clearance for the Collection of Qualitative Feedback on Agency Service Delivery (VBA, VHA, NCA)"2900-0770](https://www.reginfo.gov/public/do/PRAViewICR?ref_nbr=202307-2900-013))? It apparently [takes 1-2 weeks to get PRA approval](https://adhoc.slack.com/archives/C041CAA6J8L/p1715647536491939?thread_ts=1715633886.837419&cid=C041CAA6J8L) using that one as opposed to the 6-9 month from-scratch process.
