### ISSUE TITLE
Appointments: Support adding med review copy

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8565]
## Description 
As part of an OIG/Congressional request that came in to add some medication-related content to appointment notifications and detail pages for all appointment types on all channels. This impacts the mobile app, VA.gov web appointments, email reminders, text message reminders/pre-check-in, MHV Classic, and My VA Health portals. The objective is to remind Veterans to be ready to talk about any medication, supplement, vitamins, etc that they have been prescribed or are taking from any provider, VA clinic, or local store.

## Tasks

- [x] Chime in on initial content suggestion in [this thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1715179556504149) and [this thread](https://dsva.slack.com/archives/C03CGTDLTFF/p1715695425713289)

## Notes & Open Questions

- Whatever content is developed will somehow need to live on the Details screen for all appointment types (does this include pending? past? canceled?). Unsure of this still
- How will we handle UI? What component? We're suggesting link that opens large panel. Web seems to be going with additional info component.
- Do we need to account for push notification? So far, no.

## Resources

[DSVA Slack thread](https://dsva.slack.com/archives/CMNQT72LX/p1715000840929049)

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by mistymg** [comment]
Reducing to 1 point given changing priorities

**Comment by mistymg** [comment]
Changing points to 2 as I ended up spending more time than estimated.
