### ISSUE TITLE
Appointments: Content QA and Eng support

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8588]
## Description 
As H&B engineers are building appointments work with content updates, I want to be available to answer any questions that come up and to QA all the various edge cases we've accounted for.

## Tasks
  

-  [x] QA screenshots provided by Eng
-  [x] Identify fixes that need to be made
-  [x] Answer additional questions that come up from engineers regarding content model/matrix and mocks

# Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
