### ISSUE TITLE
Appointments: Support adding med review copy, continued

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8677]
## Description 
As part of an OIG/Congressional request that came in to add some medication-related content to appointment notifications and detail pages for all appointment types on all channels. This impacts the mobile app, VA.gov web appointments, email reminders, text message reminders/pre-check-in, MHV Classic, and My VA Health portals. The objective is to remind Veterans to be ready to talk about any medication, supplement, vitamins, etc that they have been prescribed or are taking from any provider, VA clinic, or local store.

Content has already been reviewed and approved by CAIA with my input. This is a continuation of last sprint's ticket in which I will help support UX in fitting content to our UI.

## Tasks

- [x] Ride along with Peter R. and Lauren R. while they mock up med review content for VAHM mobile app UI.

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by mistymg** [comment]
We just had a meeting to talk about setting up another recurring meeting.
