### ISSUE TITLE
Claims: Help finalize approach, support design, etc.

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8768]
## Description 
As VAHB mobile app ramps up to update the Claims experience and align more closely with what the web Claims Status Tools (CST) team has recently redesigned, as a content designer, I want to support the next phase of this project.

## Tasks
  

- [x] Land on descriptions for new 8-steps in collab with Laura W.
- [x] Figure out edge case for closed claim details screens
- [x] Participate in all stakeholder/feasibility meetings
~- [ ] Make stub ticket for adding "decision review" wording where we can~

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Created [copy deck](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=415754586#gid=415754586) as source of truth for this project.
