### ISSUE TITLE
Global - Assets: Update logos and emblems in flagship mobile app

### ISSUE THREAD

**Issue by kellylein** [department-of-veterans-affairs/va-mobile-app#8784]
### Monthly Update for Stakeholders

 
|Date|  Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| --------|---------|
|9/9/24| Not started
|9/17/24| Engineering in progress
|10/1/24| With QA

### What was updated in the Design System?
In **va-mobile-library**, the official VA logos and emblems were updated in version 0.6.0 of the [Assets package](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets) and [Figma library](https://www.figma.com/design/X8gXRl1MaRAE7lKcwgr5Rj/%F0%9F%93%90-Icon-Library---Design-System---VA-Mobile?node-id=212-1739) to be consistent with VA.gov. The new files are:
- [VALogo](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/VALogo)
     - VAOnDark.png
     - VAOnLight.png
- [serviceEmblems](https://github.com/department-of-veterans-affairs/va-mobile-library/tree/main/packages/assets/serviceEmblems)
     - vic-air-force-coat-of-arms.png
     - vic-army-symbol.png
     - vic-cg-emblem.png
     - vic-navy-emblem.png
     - vic-space-force-logo-on-dark.png
     - vic-space-force-logo-on-light.png
     - vic-space-force-logo.png
     - vic-usmc-emblem.png

### What changes are recommended in the Flagship Mobile App?
1. In **va-mobile-app**, the VA logos and emblems in the [VAIcon component](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon) should be updated as follows. After the files are updated, the [vaParentLogo](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/vaParentLogo) and [dodBranch](https://github.com/department-of-veterans-affairs/va-mobile-app/tree/develop/VAMobile/src/components/VAIcon/svgs/dodBranch) files should be removed from the VAIcon component.
     - **Update**: Logo.svg :arrow_right: VAOnDark.png
     - **Update**: AirForce.svg :arrow_right: vic-air-force-coat-of-arms.png
     - **Update**: Army.svg :arrow_right: vic-army-symbol.png
     - **Update**: CoastGuard.svg :arrow_right: vic-cg-emblem.png
     - **Update**: MarineCorps.svg :arrow_right: vic-usmc-emblem.png
     - **Update**: Navy.svg :arrow_right: vic-navy-emblem.png
     - **New**: VAOnLight.png
     - **New**: vic-space-force-logo-on-dark.png
     - **New**:  vic-space-force-logo-on-light.png
     - **New**: vic-space-force-logo.png
2. In **Figma**, the VA logos and emblems should be updated in the shipped files. After the files are updated, the Logo component should be removed from the Flagship Library file.

### Where are these files used in the Flagship Mobile App?
Currently, the logos and service emblems are used on the home screen, profile screen, and Veteran Status.

## Additional resources
- [How to use the Assets package](https://department-of-veterans-affairs.github.io/va-mobile-app/design/About/For%20engineers/assets)
- Documentation on Logos will be available in the coming weeks
- For more information about Service Emblems, reach out to #va-mobile-design-system in Slack.

## Acceptance criteria
- [ ] Logos and emblems are updated in va-mobile-app with the files in va-mobile-library's Assets package
- [ ] Logos and emblems are removed from VAIcon component in va-mobile-app
- [ ] After the above two bullets are completed, pass this ticket to Brea for the remainder of ACs
- [x] Logos and emblems are updated in shipped files in Figma.
- [x] Logos and emblems are removed from the Flagship Library file in Figma.

**Comment by TKDickson** [comment]
@theodur @kellylein @ajsarkar28 - are there no specific tickets for this? We're just.... going to do the work against the epic ticket itself?

**Comment by theodur** [comment]
@TKDickson I believe this was created to work directly off the epic ticket, but correct me if I'm wrong @kellylein @ajsarkar28

**Comment by TKDickson** [comment]
VA icons show appropriately, light and dark mode, on:
- [ ] Initial app load
- [ ] Pre-login screen
- [ ] Log in sync screen
- [ ] Log out sync screen

Military branch icons show appropriately, light and dark mode, on:
- [ ] Home (nametag component)
- [ ] Profile (nametag component)
- [ ] Veteran status card
- [ ] Military history screen....? maybe? Or we may have removed that UI. I'll check there either way.

Also:
- [ ] Can still log into demo mode by multiple taps on the prelogin screen, without assistive tech
- [ ] Can still log into demo mode by multiple taps on the prelogin screen, *with* assistive tech
- [ ] Screenreader announcement of VA icon on home is unchanged & correct
Screenreader announcement of each military branch icon is unchanged and correct:

- [ ] Air force
- [ ] coast guard
- [ ] army
- [ ] Navy
- [ ] Space force
- [ ] Marines

**Comment by TKDickson** [comment]
@brea11y Can you spin up a ticket, and associate it to this epic, for this part of the work (from the ACs)?

> After the above two bullets are completed, pass this ticket to Brea for the remainder of ACs
>  Logos and emblems are updated in shipped files in Figma.
>  Logos and emblems are removed from the Flagship Library file in Figma.

**Comment by TKDickson** [comment]
Although that is probably actually @htcollier work, since @brea11y  is now on QART and not global. Sorry for automatically pinging you per the original AC writeup. @ajsarkar28 as an FYI

**Comment by brea11y** [comment]
@TKDickson Those last two are already complete. We updated all of the logos and emblems when we did the HSP updates to the Flagship Library and shipped files. I'll mark those two AC's off.

**Comment by TKDickson** [comment]
@kellylein @ajsarkar28 FYI closing this epic, all work is complete
