### ISSUE TITLE
Claims: Hand off copy deck as is

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#8838]
## Description 
As VAHB mobile app ramps up to update the Claims experience and align more closely with what the web Claims Status Tools (CST) team has recently redesigned, as a content designer, I want to support the next phase of this project.

## Tasks
  

- [x] "Finalize" and hand off [copy deck](https://docs.google.com/spreadsheets/d/16waC665d7uNRQmM83SJIm9bTDyRePOuB6r9G_aQE8Tw/edit?gid=0#gid=0) prior to going out on PTO
- [x] Answer any questions from Eng/Product

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic
