### ISSUE TITLE
Claims: Content QA (sprint 102)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9047]
## Description 
As H&B engineers are building for claims expansion project, I want to be available to answer any questions that come up and to QA screen/builds.

## Tasks
  

-  [x] QA screenshots provided by Eng
-  [x] Identify fixes that need to be made
-  [x] Answer additional questions that come up from engineers

# Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
