### ISSUE TITLE
Onboarding: Content strategy (part 1)

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9183]
## Description 
For Q3 2024, the VAHB Global team will be starting strategy & design phases to improve/personalize the mobile app's onboarding experience. As the content lead for the mobile app, I want to start strategy work for this project to help inform

## Tasks
  

-  [x] Meet with PM/UX for strategy work
~-  [ ] Meet with (or at least schedule times with) stakeholders to gather insight~
-  [x] Read/skim through resources on product onboarding (Mobbin examples, Better Onboarding book, articles, etc.)
-  [x] Review resources gathered by PM/UX (user reviews to help define value prop, comparative analysis, etc.)
~-  [ ] Gather resources on developing value prop and facilitating workshop~

## Notes & Open Questions

**Per the epic, the project objectives are below.**
Enhance the Mobile app onboarding experience to:
- Improve new users' understanding of what the app can do for them, especially as the app's complexity increases with new features and cross-modality experience
- Make it easier for new users to get to the first instance of deriving value from the app
- Personalize the app so that the app is more relevant for the Veteran, such as opting into push notifications and adding accessibility settings
- Improve new user retention

**My own questions**
- What specific problem are we trying to solve here (as that will help guide the solution we work towards)? One problem I see if that our onboarding carousel is just a content dump of everything in the app. Doesn't really communicate any special or the unique value of the app.
- What percentage of new users end up tapping skip on onboarding carousel?

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Started work on this ahead of schedule. Attended kick-off meeting with PM/UX. Started reading Better Onboarding.

**Comment by mistymg** [comment]
Started mining key words on value prop from past UXR and VA marketing: https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery---VA-Mobile?node-id=10-146&t=Hg8oDi59hQMfFvQH-0

**Comment by mistymg** [comment]
Yesterday: More reading on onboarding

Today: Focusing on adding more details to [Figjam discovery](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery---VA-Mobile?node-id=10-146&t=Hbby6nTDYG7xnJdO-0) posting questions in [DSVA](https://dsva.slack.com/archives/C018V2JCWRJ/p1722949822403689)

**Comment by mistymg** [comment]
Today: Looked through more app reviews for value themes
