### ISSUE TITLE
Copy of Claims: Content QA

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9185]
## Description 
As H&B engineers are building for claims expansion project, I want to be available to answer any questions that come up and to QA screen/builds.

## Tasks
  

-  [ ] QA screenshots provided by Eng
-  [ ] Identify fixes that need to be made
-  [ ] Answer additional questions that come up from engineers

# Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic

**Comment by mistymg** [comment]
ZH is stupid and duplicated too many times
