### ISSUE TITLE
Claims: Content support to improve SE/FR flow

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9186]
## Description 
As a part of the [claims step expansion project](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8688), our team reused the current file/photo upload functionality within the file request flow to enable Veterans to submit evidence for a disability comp claim at any time. We now want to review these 2 flows (and the file/photo upload process) to see if we can make any additional improvements.

## Tasks
  

-  [ ] Collaborate with UX to identify pain points in SE/FR flows
-  [ ] Review current flows for duplicative content or possible content tweaks

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic
