### ISSUE TITLE
Feedback Hub: Update Components to Align With VADS

### ISSUE THREAD

**Issue by brea11y** [department-of-veterans-affairs/va-mobile-app#9357]
Using the [VA Design System](https://design.va.gov/), update the following areas of the [Feedback Hub](https://feedback-hub-e659c24714b9.herokuapp.com/):

- [ ] Remove the "VA Mobile Feedback Hub" heading on each page (since that will be moved to the header) and replace it with descriptive page titles for each page (i.e. Reddit Reviews, Apple App Store Reviews, etc.). Align all copy including headings [with VADS](https://design.va.gov/foundation/typography#headings) guidance.
- [ ] All tables in the Feedback Hub site should be replaced with the [Responsive Stacked Table component](https://design.va.gov/components/table#examples---v1) from VADS. This will ensure that each table is accessible and wraps appropriates (without side-to-side / horizontal scrolling)
- [ ] Replace all date range selectors with the [Date Input component](https://design.va.gov/components/form/date-input)
- [ ] On the App and Play store pages, replace the select box with the [Select component](https://design.va.gov/components/form/select)
- [ ] Replace the query input field(s) with the [Text input component](https://design.va.gov/components/form/text-input)
- [ ] Replace the green "search" button with the [Default - Primary button component](https://design.va.gov/components/button/#default---primary)
- [ ] Replace the blue "Download as .csv" button with the [Default - Primary button component](https://design.va.gov/components/button/#default---primary)
- [ ] The "tabs" on the rating history pages, should be replaced with [Tabs component](https://design.va.gov/components/tabs)
- [ ] Chat GPT:
   - [ ] Replace the input field with the [Text input component](https://design.va.gov/components/form/text-input)
   - [ ] Replace the button with the [Default - Primary button component](https://design.va.gov/components/button/#default---primary) (and update it to include actual copy – i.e. "search", "submit", "send", etc.)
   - [ ] Update all of the fonts to match VADS [Typography](https://design.va.gov/foundation/typography) guidelines
   - [ ] Replace the gray background color with:  **vads-color-gray-light-alt** (#edeff0)
   - [ ] Replace the blue background color with:  **vads-color-hub-burials** (#2378c3)
      - This is slightly darker than the existing blue, but with white copy, it passes accessibility color contrast minimums. It was the closest that we could get to still pass AA guidelines.
- [ ] There are no components within VADS that can be used to replace the data within the "charts" tab and these will also not be accessible without additional content that is used to describe what is seen / displayed within the charts. We should replace the colors used within the charts to align with the [VADS color palette](https://design.va.gov/foundation/color-palette) and the fonts should also be swapped out with [Source Sans Pro](https://design.va.gov/foundation/typography#fonts) (if they are not already).
   - [ ] Replace red with: **vads-color-error** (#d54309)
   - [ ] Replace blue with: **vads-color-hub-health-care** (#3f57a6)
   - [ ] Replace yellow/gold with: **vads-color-warning-dark** (#e5a000)
   - [ ] Replace green with:  **vads-color-success** (#00a91c)
   - [ ] Replace purple with:  **vads-color-hub-records** (#864381)
   - [ ] In monthly average, replace the stroke with:  **vads-color-hub-health-care** (#3f57a6) 
   - [ ] In monthly average, replace the fill with: **vads-color-hub-health-care** (#3f57a6) _at a very similar opacity to what you have now, if possible_
- [ ] The tables used within the "data" tab, should use the [Responsive Stacked Table component](https://design.va.gov/components/table#examples---v1) from VADS. This will ensure that each table is accessible and wraps appropriates (without side-to-side / horizontal scrolling).

**Comment by StacyB2023** [comment]
@ajsarkar28 @dumathane - I will set up call for us for about 45 min this week. Here is the ticket we are planning for implement for feedback hub in the meantime (minus the header/footer). cc: @brea11y @Tonksthebear  FYI- @jperk51

**Comment by TKDickson** [comment]
@DJUltraTom this is an API team project that's getting additional work done by global, and may at some point spin out into its own product. If that doesn't fall into floater, I don't know what does! If the testing work goes beyond this sprint (which it likely will, at this point), we can transition to me.

**Comment by DJUltraTom** [comment]
@TKDickson As this is a web based internal tool, are we looking for more than a VQA pass to validate that the tool aligns with VADS or are you wanting additional functional QA? (and if so, do we have browser requirements for using the tool?)
(very) Rough place holder test case is [HERE](https://dsvavsp.testrail.io/index.php?/cases/view/101756) I can get more granular with the test steps on Monday.

**Comment by timwright12** [comment]
Technically the work is "1:1 validation of the design elements"... _however_, this product badly needs an exploratory functional test as well. Can we look into do that maybe on another ticket if we can't fix it into this one?

**Comment by DJUltraTom** [comment]
Since this is a realworld product with a potential pricetag attached to exercising it, is there existing guidance around using it to make sure we stay under the pay limit threshold?

**Comment by timwright12** [comment]
@DJUltraTom currently I think the app just stops working beyond the rate limit, so we don't need to worry about that quite yet

**Comment by theodur** [comment]
I posted an update on this last week on Slack, but wanted to provide an update here as well. The UI changes have been completed. The only thing remaining is to get the web components working with the Rails form submission. Jason. has been working on that this week. Once that's finished, this will be ready for QA

**Comment by brea11y** [comment]
Hey @theodur (and @Tonksthebear + @StacyB2023 for awareness)  – I just completed the VQA / accessibility audit of the Feedback Hub updates. Listing any issues and/or questions below.

### Links
![Image](https://github.com/user-attachments/assets/c6146a30-cf7b-481b-9ae1-eb812dc9d26d)
1. Verify that the links are pulling in the correct colors. The default and hover states of the link in the body of the site don't look like the right shades of blue (see screenshot above) and the default link color in the header and footer appear to be gray. I know we haven't updated the header and footer yet, but I do feel like we should probably get the links to be the correct colors for now and then can revisit them when we implement the header and footer updates. [Storybook for reference](https://design.va.gov/storybook/?path=/story/components-va-link--default&args=abbr-title:;active:!false&globals=backgrounds.grid:!false).
   - Default should be vads-color-link (#005ea2)
   - Visited should be vads-color-link-visited (#54278f)
   - Active should be vads-color-link-active (#0b4778)
   - Hover should inherit the base font color and have a background color of rgba(0,0,0,0.05)
   - Focus should inherit the default link color, but have the 2px outline using vads-color-action-focus-on-light (#face00)
2. For any external links, is it possible to also add an ARIA label announcing that the links are external? [VADS Guidance](https://design.va.gov/content-style-guide/links#linking-to-external-sites), for reference.
3. For any links that open in a new tab, [VADS guidance](https://design.va.gov/content-style-guide/links#linking-to-external-sites) is that we either remove the option for it to open in a new tab (and force it to open in the same tab) or they want you to add copy at the end of the link that tells a user that it will open in a new tab. I would just remove the _blank target and have them open in the same tab so we aren't cluttering up the site.


### Tabs
1. For the tabs, is it possible to bump that font size within the actual tabs down to be the same as the body font size? Currently, they appear to be 20px, but they feel huge in comparison to the base font size of 16px.
2. In addition, I would also consider bumping down the left and right padding within each of the tabs to 3rem and the margin above and below to .5em.

### Forms
![Image](https://github.com/user-attachments/assets/37e3dabf-b2d2-40fb-b871-d065c754c1fd)
For the Chat GPT text input, on focus, the text box appears to have a blue border (in combination with the yellow outline). Could we adjust the blue border to be the same as the other form fields on focus?

### Other
1. I’m thinking this might be because I am reviewing a branch and not the live site, but I am unable to actually see any of the data. I was hoping to check the table’s responsiveness and the colors used in the charts (since we were updating them to VADS colors), but when I attempt to change the dates and click the search button, it defaults back to today’s date and doesn’t update in the charts and tables. 
2. However, from what I can see, it looks like we are using the [Sortable table](https://design.va.gov/components/table#sortable) from VADS and not the [Responsive Stacked Table](https://design.va.gov/components/table#responsive-stacked-table-v1-default) as planned. Is that right?

**Comment by theodur** [comment]
@brea11y I made all the requested changes you made. You should be good for VQA again ✅. (@Tonksthebear FYI I pushed those changes to the `feat/vads-UI-updates-wip` branch).

In terms of not being able to see the data when searching, I don't think you'll be able to see data locally for the app/play store, just the Reddit search. Not sure if that's the one you've been trying to search in?

As for the responsive stacked table, unfortunately there were some issues with using it, so we had to use the Sortable table in order to be able to sort the data (correct me if I'm wrong @Tonksthebear).

**Comment by brea11y** [comment]
I thought that might be the case! Thanks @theodur. I am totally okay with using the sortable table and I think it actually makes sense to be able to sort the information (especially if you don't plan to download it). I did take a look at it again yesterday (only for a few minutes) to see if the data would show if I submitted for Reddit and the only things that I noticed were:

1. At first glance, the colors in the table didn't seem to be same colors that are used in the [VADS sortable table example](https://design.va.gov/components/table#sortable). I think I remember seeing a pale shade of gray in the table header (top row). Do you mind double checking the colors to verify that they are the same as VADS?
2. The table was stretching outside of the viewport on the left and the right. I'm using a 14" MacBook Pro if that is helpful. Would it be possible to set a forced maximum width for the tables to prevent that from happening? Typically, we want to avoid side-to-side scrolling for accessibility best practices whenever possible.

I was hoping to take a deeper look today and verify that I was able to see all of the updates that you made, but the link to the branch that Jason sent over earlier in the week is giving me a "bad gateway" error.. I likely waited too long to circle back. I'm so sorry about that. Would it possible to get it back up and running on Monday so I can do last looks before we push out the updates?

**Comment by theodur** [comment]
> At first glance, the colors in the table didn't seem to be same colors that are used in the [VADS sortable table example](https://design.va.gov/components/table#sortable). I think I remember seeing a pale shade of gray in the table header (top row). Do you mind double checking the colors to verify that they are the same as VADS?

@brea11y They don't match the default sortable table style, but the [bordered](https://design.va.gov/storybook/?path=/docs/uswds-va-table--docs#bordered) styling instead. We can always remove the border if you want? This is what it looks like borderless for reference:

<details> <summary> Borderless table screenshot </summary>

![Image](https://github.com/user-attachments/assets/9bb38f9d-fa22-4d8f-a885-83d0fcee891d)

</details>

Here's the bordered table we're using right now for comparison:

<details> <summary> Bordered table screenshot </summary>

![Image](https://github.com/user-attachments/assets/e99c8b8d-1f0c-4cd0-a797-903db4343130)

</details>

> The table was stretching outside of the viewport on the left and the right. I'm using a 14" MacBook Pro if that is helpful. Would it be possible to set a forced maximum width for the tables to prevent that from happening? Typically, we want to avoid side-to-side scrolling for accessibility best practices whenever possible.

I made some changes to restrict the width of the table. It looks like some extra padding was being tacked on. In doing so though, the table needed to become scrollable, which seems to be what the USWDS [recommends](https://designsystem.digital.gov/components/table/#scrollable-table-2) for dense data.

This is ready for you to take another look! Let me know if you want us to remove the border on the table.

**Comment by brea11y** [comment]
@theodur – I actually really like the border. I was concerned that it wasn't an exact 1:1 with VADS, but I don't know that it has to be. I just took a look and I really like the way the table looks with the borders. I think it makes the grids clear and that's a bonus in my book. 

I also appreciate you updating the width on the table so that it isn't extending it both on the left and right-hands sides of the screen. If we must have the side-to-side scrolling, I think this is the best way to do it.

Overall, I think everything looks great and didn't spot any additional issues. I think we're good to go on this! Thanks so much for all of your hard work!

**Comment by theodur** [comment]
> I actually really like the border. I was concerned that it wasn't an exact 1:1 with VADS, but I don't know that it has to be. I just took a look and I really like the way the table looks with the borders. I think it makes the grids clear and that's a bonus in my book.

@brea11y I agree, definitely think the borders look better 💯

Thanks for confirming everything looks good! I'll sync with Jason on getting these changes merged

**Comment by theodur** [comment]
Since the `feedback-hub` repo isn't part of our Zenhub workspace, I can't attach this ticket to the PR, so I'm linking it here for reference: https://github.com/department-of-veterans-affairs/feedback-hub/pull/43.

There are some failed unit tests/linting errors that Jason will be looking into. Once that's resolved, we should be good to merge.

**Comment by theodur** [comment]
The PR for this was approved and merged. The changes are live in prod now ✅ Closing this
