### ISSUE TITLE
Onboarding/Product Adoption: Support discovery/documentation + product brief

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9503]
## Description 
As we dig deeper into the Onboarding project, we want to finalize the product brief and our recommendations for a roadmap and priority list of improvements to make. To do so, I need to help UX/Product with use my content expertise to identify where our current onboarding experience needs improvement based on industry best practices.

## Tasks
-  [x] Get up to speed on industry best practices on onboarding/user journey's based on [DRAFT: VA Mobile App - Discovery/Desk Research: Mobile App User Journeys & Onboarding: Best Practices](https://docs.google.com/document/d/17yJHjjjyHH7OS7PdbauTf--yf6NOv0_yfNjUiFB-6so/edit#heading=h.yl5rm31rqvz7)
- [x] Review and add comments/questions/suggestions as needed to [DRAFT: VA Mobile App - Mobile App User Journey & Onboarding: Comparative Analysis](https://docs.google.com/document/d/1to1WulA7SxB2vcCuhh5KhK27qnSxwVpal_XP7Dkdx80/edit)
- [x] Complete quick [content gap analysis of current onboarding journey](https://www.figma.com/board/oaF7dSbwnt1Ga3v6rrVsx8/Onboarding---%F0%9F%A7%AA-Discovery-%26-Research---VA-Mobile?node-id=9-380&node-type=CANVAS&t=UkQHPVO2sOfHCgke-0)
- [x] Add comments/questions/suggestions to [product brief](https://docs.google.com/document/d/1C9Gqt5GhDniOScfyheI9lhbLsWafAGBIrKBPovjjDpQ/edit#heading=h.mnq6vtjqteg4) 

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [X] Linked to an Epic
