### ISSUE TITLE
Governance and process for experience teams initiative

### ISSUE THREAD

**Issue by Hallm13** [department-of-veterans-affairs/va-mobile-app#9573]
# Project Status Overview
### Project Objective:
In the first few weeks of inviting web experience teams to partner more closely with mobile and move into later stages of the collaboration phases, we've surfaced several areas where we need to develop governance and process to manage how these teams work together. 
 

- [ ] Overall initiative brief that clarifies the goals of having experience and mobile teams collaborating. This document would help focus our efforts and guide decisions on how this initiative should be implemented.
- [ ] Criteria for when an experience team is ready to engage the mobile team. Detail the prerequisites for how developed a project should be before an experience team is ready to call for additional assistance from the mobile team. 
- [ ] Criteria for prioritization among experience team projects. Detail how prioritization decisions are weighted.
- [ ] how many current users do we have for shared services? by user, I mean # of people, # of teams, or however else we define user on average, how many "leads" do we get every month (or whichever time frequency we use to track)? by lead, I mean new teams filling out an intake form approximate % of leads who become an actual user?
- [ ] Detail roles and ownership around analytics

### Monthly Update for Stakeholders

 
|Date|  Progress & Key Accomplishments| Issues/Risks/Blockers|
|-------| --------|---------|
|MM/DD/YY| 
|MM/DD/YY|
|MM/DD/YY|
|MM/DD/YY|

### Current Dependencies / Blockers
<details>
<summary>Blockers</summary>
 
|Blocker | Team / Owner | Est to Resolution |
|-------|---------|-------| 
| Internal dependency ? |   |
| External dependency ?  |   |
</details>

### Team Members
<details>
<summary>Contact List</summary>
 
**VA:**
- **Mobile OCTO Product Leads:** Ryan Thurlwell & Don McCaughey
- **VA OCTO Product Leads:** 
- **External Team 1 & Role:**
- **External Team 1 & Role:**
- 
**Ad Hoc:** 
- **Mobile Team**: Leads
- **Mobile Team Lead:** 
- **FE Engineering:**
- **BE Engineering:** 
- **Design:**
- **Content**
- **QA:**
- **Mobile Teams that are involved:** Leads only
</details>
