### ISSUE TITLE
BUG - sev 3 - Claims Subtask screens display bottom navigation

### ISSUE THREAD

**Issue by wavelaurenrussell** [department-of-veterans-affairs/va-mobile-app#9835]
## What happened?
In Claim History, some of the screens within the Fullscreen subtask are displaying the bottom navigation. They shouldn't be, since the user has descended within the navigation stack once pressing the [Review file requests] button.

## Specs
Device: All
OS: All
User Account: All
Accessibility State: All

## Steps to reproduce
- Tap into Claim history, and find an Active Claim with a [More info needed] tag
- Once on Claim details, validate the [Review file requests] button is present. Tap to launch the File request subtask
- Observe/remove the bottom navigation present on these two screens: 
    - File requests (general - screen 1)
    - Request detail (specific - screen 2)

## Desired behavior
Remove bottom navigation from these screens.

## Bug Severity - BE SURE TO ADD THE SEVERITY LABEL
 
See [Bug Tracking](https://department-of-veterans-affairs.github.io/va-mobile-app/docs/QA#issue-severity) for details on severity levels

- Impact: Low 
- Frequency: High 

- 3 - Low

## Screen shot(s) and additional information

<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3N4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--867670c319e792dfd455046b5dbb51a1f04ad47e/FR1%20-%20General.png" alt="FR1 - General.png" />

<img width="240" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3d4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7df1e94a8d2eb69373825845dd19e461615ca284/FR2%20-%20Detail.png" alt="FR2 - Detail.png" />

## Ticket Checklist
- [ ] Steps to reproduce are defined
- [ ] Desired behavior is added
- [ ] Labels added (front-end, back-end, global, Health, relevant feature, accessibility, etc)
- [ ] Estimate of 1 added (for front-end tickets)
- [ ] Added either to the relevant feature epic (if found during new feature implementation), or the relevant team's bug epic ([Global](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8302), [Health & Benefits](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8303), [API](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8304), [QART](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/8305))

**Comment by dumathane** [comment]
@alexandec I think we get this for free with your multi-step subtask work, but please correct me if I'm wrong. If i'm not, feel free to associate both tickets and get the free point.

**Comment by DJUltraTom** [comment]
verified bottom navigation is now no longer present on claims upload screens
QA approves this change

**Comment by DJUltraTom** [comment]
spot checked on the new build and it looks good, reapproving

**Comment by DJUltraTom** [comment]
verified this is functioning as designed on the RC build, closing as deployed
