### ISSUE TITLE
QA epic prep for Q3 to Q4 transition

### ISSUE THREAD

**Issue by TKDickson** [department-of-veterans-affairs/va-mobile-app#9846]
- [x] Come up with recommended priorities for Q4 for QA (my [sheet](https://docs.google.com/spreadsheets/d/1AYvG8ymQDzRViid6ALpfHr2g1oB84ECmX4Gcdneh6uI/edit?usp=sharing) & [doc](https://docs.google.com/document/d/1ItT2NT4OanrUeLxz3dvdz4yaw2dtnK_IfsPGM5F2xsk/edit))
- [x] Check with Rachael and Tom on their recommended priorities 
- [x] Put those in snappy words in the Q4 epic title & list

Then, review all open tickets Q3 QA epic (and maybe also external team onboarding epic?):
- [x]  close ones that should be closed
- [x]  move to Q4 what's a priority for Q4 (based on work above)
- [x]  assign ~3-4 of the Q4 tickets to Tom & move to the 'backlog:ready to work' column for him to pull in on his own schedule/preference
- [x]  create/find 'backlog' epic, and move not-prioritized tickets to that epic
- [x]  close the Q3 epics
- [x]  check if any of the tickets on the accessibility Q3 epic would be beneficial to prioritize in Q4, and pass that along to Brea either way

**Comment by TKDickson** [comment]
Upping my estimate. There are.... many more QART tickets in the backlog, either QA-specific or not labelled with a team, than I had originally thought.

**Comment by TKDickson** [comment]
Have questions out to some folks on remaining QA-specific Q3 epic tickets; I think there are just 3 of those left.
Not going to create a backlog epic (until/unless Sarah wants one) so marking that AC as 'done'
