### ISSUE TITLE
Content Work (continued): Travel Pay

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9959]
## Description 
This is a continuation of work started in [9731](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9731). Due to additional content requirements and feedback from stakeholders, more time is needed to refine content and design before handing off.

## Important Links
- [Travel Pay epic](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9663)
- [Travel Pay research](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/products/health-care/checkin/research/veteran-facing/travel-reimbursement-mvp-remote-test)
- [Product Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product-outline-btsss.md)
- [Mobile & Experience team Collaboration doc](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/health-care/beneficiary-travel/product/initiatives/mobile_collaboration.md)
- [Original request from the Experience team](https://app.zenhub.com/workspaces/va-mobile-60f1a34998bc75000f2a489f/issues/gh/department-of-veterans-affairs/va-mobile-app/9563)
- [Experience team epic](https://app.zenhub.com/workspaces/beneficiary-travel-btsss-65147e21930cd900223d8e64/issues/gh/department-of-veterans-affairs/va.gov-team/91550)

## Web flow explanation/links
- Web starts simple mileage-only travel reimbursement claim from Appointments details screen - [Figma file](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2160-2072&node-type=section&t=jQlAcM7LtmKdOEgO-0) - note no mention of travel on Appointments list view
- They then take users through the claim flow [Figma file](https://www.figma.com/design/RzugGEmu4drhCSHTyQ6hjl/Simple-mileage-only-travel-pay-claim-submission?node-id=2111-5020&node-type=canvas&t=gyMB9P2KYAKWasGK-0)
- Users then can check list of travel reimbursements - [Figma file](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=2111-5020&node-type=canvas&t=64Fgmn7XQGduSDU7-0)
- And users can drill down into a status detail of each claim - [Figma file](https://www.figma.com/design/RJ6OVm0MWD2WprVfO7E3lp/Travel-reimbursement-status-page?node-id=4060-3841&node-type=canvas&t=ghmb132wGHeCGEHZ-0)

## Tasks

- [x] Work with designer to update designs based on stakeholder feedback
- [x] Meet with Ryan and Kristen to review latest designs
- [x] Address any open content questions or concerns

## Acceptance Criteria
  

- [x] SMOC claim content is documented in Figma
- [x] Stakeholders have reviewed designs
- [x] Content is ready for Eng hand off

## Ticket Checklist

- [X] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Worked this morning on refining copy base on meeting yesterday with designer. Will present latest designs later this afternoon to Ryan and Kristen. Additional work may be needed depending on their feedback.

**Comment by mistymg** [comment]
Today: Reviewed Figma prototype

**Comment by mistymg** [comment]
Today: Ryan has signed off on designs/content. Lauren will share links to prototype/mocks to Kristen for any feedback. We will wait to hand off until all clear from Kristen.

**Comment by mistymg** [comment]
Friday: Tweaks to button copy after feedback from Ryan.
Today: Still waiting for all clear from Kristen.
