### ISSUE TITLE
Value prop: Drafting statement

### ISSUE THREAD

**Issue by mistymg** [department-of-veterans-affairs/va-mobile-app#9960]
## Description 
Taking insights from the recent workshop, app store reviews, user research, and discovery phrase, we want to draft a value proposition for the mobile app that can be socialized across VA and applied directly to key parts of the user journey (particularly in marketing and first-run experiences). This is an important piece of work for our onboarding and product adoption strategy. We will share the draft(s) with stakeholders for feedback and alignment. 

## Tasks

- [x] Review workshop notes and Mural
- [x] Review discovery documentation
- [x] Draft and iterate on options
- [x] Document reasoning for word choices, etc.
- [x] Get feedback from team members

## Acceptance Criteria
  

-  [x] Value proposition statement draft(s)
-  [x] Drafts incorporate feedback from both workshop + discovery
-  [x] Drafts include a full statement (1-3 sentences, no more than 50 words)
-  [x] Drafts have explanation for important parts and/or how words tie back to workshop/discovery findings

## Ticket Checklist

- [x] Acceptance criteria defined
- [X] Labels added (front-end, back-end, feature)
- [x] Linked to an Epic

**Comment by mistymg** [comment]
Today I'll be doing a quick affinity map of [discovery findings in Figjam](https://www.figma.com/board/IZBWa7TInAcgMKdQlRVqQR/Value-proposition---%F0%9F%A7%AA-Workspace---VA-Mobile?node-id=2034-401&t=usNKZ7RP1dRUo6I9-4) based on ideas we found in app reviews, etc. Will do this with Megan/UX researcher. Will also set up space to start drafting value props

**Comment by mistymg** [comment]
Today: Started drafting value prop statements

**Comment by mistymg** [comment]
Today: Continued drafting single-sentence value props; explored expanded versions; scheduled time to chat with Ameet tomorrow for feedback

**Comment by mistymg** [comment]
Today: Decided on 2 options (short- and long-form) and noted some rationale behind word choices. Will get feedback from Ameet tomorrow.

**Comment by mistymg** [comment]
Today: Meeting with Ameet to share drafts and get feedback.

**Comment by mistymg** [comment]
Today: Lots of additional drafts of value prop based on feedback from last week. Shared latest versions with internal team to get updated feedback. Will share with Danielle Thierry for her feedback tomorrow.

**Comment by mistymg** [comment]
For transparency, I'm uploading a PDF version of my [value prop drafts doc](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--602128c8d5d30bf984c34ca3e1b61e582ba335b7/Value%20prop%20drafts.pdf) to share my drafting process.

**Comment by mistymg** [comment]
Today: Shared these 2nd/3rd person versions with Danielle. Asked for feedback, especially on "tools." Will continue this work next sprint to get statement finalized.

> The VA health care and benefits tools you use most often—all in one simple app.
> The VA health care and benefits tools Veterans use most often—all in one simple app.
